### ISSUE TITLE
Blackhole example?

### ISSUE THREAD

**Issue by Archerious** [peacey/split-vpn#1]
What would be an example blackhole rule?

I want to make sure br500 (VLAN500) cannot use internet without being VPN'd, even if the script doesn't run on boot for any reason.

**Comment by peacey** [comment]
Hi @Archerious,

You are correct you can do this with blackholes routes. I have outlined the steps for adding blackhole routes in Step 6 of the README [here](https://github.com/peacey/split-vpn#how-do-i-run-this-at-boot). You have to add the 4 blackhole routes in the Unifi Network Settings as instructed in Step 6(a). You do not add them in the script config. 

This is how it works:

1. The system turns on and the UDM/P adds the blackhole routes, and sets up the network. The blackhole routes will block any access to the Internet for ALL clients (not just the ones you forced in the VPN config).
2. The openvpn boot script runs shortly after (a few seconds), and sets up the iptables killswitch and other rules (this is the pre-up line in the boot script). Once the iptables rules are set up, the script deletes the blackhole routes which restores Internet access to all clients. The iptables rules will ensure VPN clients do not have access to the main WAN at this point. 
3. If openvpn fails to connect, the iptables rules that force VPN clients will still not be removed as long as you made sure to set `KILLSWITCH=1` and `REMOVE_KILLSWITCH_ON_EXIT=0` in the `vpn.conf` file. Hence, your VPN devices will not be able to connect to the Internet, but other devices will have access to their default WAN. 
4. If the iptables script fails to run, the blackhole routes will not be removed, and all clients (even non-VPN ones) will not have Internet access until you fix your configuration errors and rerun the script, or you manually remove the blackhole routes through Unifi Network Settings. So please make sure that you are able to run the script once and there are no issues in your configuration so you have a smooth operation.

**Comment by Archerious** [comment]
Thank you so much, my apologies for not seeing that step in the on boot part.

Thanks again for your hard work and help, being able to use openvpn-client like this has been incredible. No more worries about guests doing anything to get me a nasty DMCA letter :D.
