### ISSUE TITLE
Is router (as host/client) connection required?

### ISSUE THREAD

**Issue by OpenSourceGhost** [peacey/split-vpn#100]
I only have 1 client I want to use Split VPN on my UDM, but I don't want the router itself to make connections. I manually create IPTables (that survive reboot with hel of UDM-Utilities) to block all Layer 3 INPUT and OUTPUT for the router itself, but allow FORWARD for all the clients. WAN is eth4:
iptables -I INPUT -i eth4 -j DROP
iptables -I OUTPUT -o eth4 -j DROP

Layer 2 (ARP) connection is of course necessary for any router to function and as such, it isn't blocked. I do all that along with setting WAN DNS IP's to 0.0.0.0 (and creating a rule to drop all "WAN Local" traffic in UDM GUI) to prevent any telemetry (including "anonymized") from being sent to Ubiquiti. This prevents Suricata IPS rules from being downloaded, but I download them manually through a VPN-protected client and apply them via SSH. The same goes for Network Application and/or firmware updates. Only clients have Layer 3-7 access to WAN on my network. UDM itself only has Layer 2 / ARP connection to ISP's local switch.

Is it possible to use your Split-VPN for a single client while maintaining my IPTables that prevent UDM (as a host) from using WAN on Layer 3?  

If not, then would Split-VPN force all UDM INPUT/OUTPUT (including telemetry and Suricata IPS updates? ) go through VPN tunnel?

**Comment by peacey** [comment]
Hi @OpenSourceGhost,

So the UDM is going to need to be able to communicate with the VPN server's WAN IP at the least. There is no going around that. But can't you just add an allow rule to allow traffic to/from the VPN server's WAN IP through your WAN interface? This way the VPN will work and you're still blocking all other WAN communication to non-VPN IP.

Alternatively, there is a way to force all UDM local traffic through the VPN too (via the `FORCED_LOCAL_INTERFACE`option), but it can have unintended side effects and I haven't extensively tested it with all UDM features. So I would only use that if absolutely necessary and be ready to debug if things go wrong.

**Comment by peacey** [comment]
Hi @OpenSourceGhost,

This issue has become stale so I'm closing it. Feel free to re-open if you are still having issues or more questions!
