### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by ryarber** [peacey/split-vpn#104]
I have been having issues with router since I installed. I have decided not to go this route with VPN. How do I uninstall this?

**Comment by peacey** [comment]
Hi @ryarber,

You just have to remove the script directory, and boot script, and then restart. Just run these commands on your UDM:

```sh
rm -rf /mnt/data/split-vpn /data/split-vpn /etc/split-vpn
rm -rf /mnt/data/on_boot.d/99-run-vpn.sh /etc/systemd/system/run-vpn.service
```

Then restart if you're already running the script. Unless you're running the script, it won't affect the UDM and your forced networks.
