### ISSUE TITLE
Make source of peacey/udm-* Dockerfiles available

### ISSUE THREAD

**Issue by Stealthii** [peacey/split-vpn#108]
It would be ideal to make the Dockerfiles used to build [peacey/udm-openconnect](https://hub.docker.com/r/peacey/udm-openconnect) and [peacey/udm-strongswan](https://hub.docker.com/r/peacey/udm-strongswan) available, so that suggestions, fixes, etc. can be offered via PR.

**Comment by peacey** [comment]
Hi @Stealthii,

I will upload them to their own repository later this week. Thank you for telling me.

**Comment by baconlive** [comment]
Did you upload them?

**Comment by peacey** [comment]
Sorry @baconlive. Completely forgot about this. Will try to do it tonight.

**Comment by peacey** [comment]
Sorry for the delay @Stealthii and @baconlive.

I have uploaded the sources to [peacey/udm-openconnect](https://github.com/peacey/udm-openconnect) and [peacey/udm-strongswan](https://github.com/peacey/udm-strongswan) now. 

I have also updated the Docker hub to the latest versions. 

Have a great day!
