### ISSUE TITLE
Change in location of files for UDM Pro on version 1.12.22

### ISSUE THREAD

**Issue by nigels0** [peacey/split-vpn#109]
Note that in version 1.12.22 on a UDMP  the directory that split-vpn is installed to is /data

**Comment by peacey** [comment]
Hi @nigels0,

On the UDM Pro (not UDM SE) on 1.12.22, the data directory is still /mnt/data, not /data. The install script still installs it to /mnt/data. 

Why are you installing it to /data?

**Comment by nigels0** [comment]
Beats me! I just ran the script and found the split-vpn directory in /data! 

Having said that, I ran the install script on top of an existing impelementation because somehow the CA had changed on my OpenVPN server and I couldn’t find the VPNClient.config file…

**Comment by peacey** [comment]
Hmm that's weird. The only time the install script would install it in /data is if /mnt/data didn't exist. 

Can you please verify that /mnt/data exists, and re-run the install command? Then show me the output of the install command. Thanks!

**Comment by nigels0** [comment]
Hmm, I did this and it installed to mnt/data this time. Puzzling…

**Comment by peacey** [comment]
Ya I'm not sure, pretty weird! Maybe /mnt/data didn't exist for a brief moment? Though that should never happen... Anyhow, I will close this issue now but if you have any more problems, feel free to re-open!
