### ISSUE TITLE
IPSet instruction errors

### ISSUE THREAD

**Issue by recrudesce** [peacey/split-vpn#114]
Hey, just a heads up, the README for the ipset configuration is wrong. https://github.com/peacey/split-vpn/blob/main/ipsets/README.md

In section 7, it tells you to edit the 99-run-vpn.sh to add the following line: 
`/mnt/data/split-vpn/ipsets/add-dnsmasq-ipsets.sh`

The directory and the file name are wrong

As per the previous steps, the correct line to add is
`/etc/split-vpn/ipsets/add-dnsmasq-ipset.sh`

This corrects both the directory, and the file name.

Additionally, in step 4, the filename is incorrect, it should end in "ipset" and not "ipsets".

**Comment by peacey** [comment]
Thanks @recrudesce. I have fixed it in the README.
