### ISSUE TITLE
Unable to initialize table 'raw'

### ISSUE THREAD

**Issue by KrautByte** [peacey/split-vpn#117]
Hi there,

sadly the script doesn't seem to work for me and I am not sure what is causing it.

```# /mnt/data/on_boot.d/08-setup-vpn.sh
ln: /bin/bash: File exists
ln: /usr/bin/htop: File exists
ln: /usr/sbin/iftop: File exists
ln: /sbin/resolvconf: File exists
Warning: `/mnt/data/split-vpn/wireguard/apt420/tun0.conf' is world accessible
[#] ip link add tun0 type wireguard
[#] wg setconf tun0 /dev/fd/63
[#] ip -4 address add X.X.X.X/32 dev tun0
[#] ip link set mtu 1390 up dev tun0
[#] wg set tun0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev tun0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
iptables-restore v1.6.2: iptables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try iptables-restore -h or iptables-restore --help for more information.
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev tun0```

**Comment by peacey** [comment]
Hi @KrautByte,

You seem to be using 0.0.0.0/0 in your wireguard config (tun0.conf). That requires the iptables raw module which doesn't exist by default. The alternative is to instead replace 0.0.0.0/0 with `0.0.0.0/1,128.0.0.0/1` which covers the same subnet but doesn't require the raw module. 

If it doesn't work for you, please show me the wireguard config and what you're trying to do. 

Thanks!

**Comment by KrautByte** [comment]
Ok so after looking into it further and testing the recommended solution it's still not working.
It appears that the vpn is now trying to route trough itself and therefore the amount of received bytes is 0.
Are there any things I can do to make debugging easier / things to read up on in order to understand this?

**Comment by peacey** [comment]
@KrautByte, can you please show me your vpn.conf and Wireguard config without the keys? And what are you trying to route through the VPN (a particular network or client)?

**Comment by KrautByte** [comment]
I think I figured out what went wrong, nothing do with your project, sorry for taking up your time.

**Comment by peacey** [comment]
No problem, @KrautByte. You can close this now if you're not having issues anymore, or feel free to ask more questions!
