### ISSUE TITLE
Fatal error when running test script

### ISSUE THREAD

**Issue by Lolcar84** [peacey/split-vpn#118]
Greetings! Currently having an issue when running  giving  split-vpn a test run. I am getting the following error:

Tue Jul 26 23:02:06 2022 /etc/split-vpn/vpn/updown.sh tun0 1500 1584 10.23.0.8 255.255.0.0 init
: not foundvpn/vpn/updown.sh: 4: ./vpn.conf:
Tue Jul 26 23:02:06 2022 WARNING: Failed running command (--up/--down): could not execute external program
Tue Jul 26 23:02:06 2022 Exiting due to fatal error

i verified the updown.sh  is in the right place. currently running Unifi OS v 2.4.12 on a UDM SE.

IF any additional information is needed. let me know!

**Comment by peacey** [comment]
Hi @Lolcar84,

Did you create a vpn.conf and did you cd into the directory with your vpn.conf before running the VPN?

**Comment by Lolcar84** [comment]
hey hey. i did. still getting the same error

**Comment by peacey** [comment]
Did you create the vpn.conf file directly with vim or with a windows text editor and then scp'ed it over? Can you show me your vpn.conf? Also can you show me what commands you are running? Thanks.

**Comment by peacey** [comment]
Hi @Lolcar84,

This issue has become stale so I'm closing it, but if you ever want to continue debugging, feel free to re-open!
