### ISSUE TITLE
Running two instances of OpenVPN

### ISSUE THREAD

**Issue by FreakySnake2** [peacey/split-vpn#119]
Hi, not quite an issue, but I wasn’t sure how else to contact you. I am trying to run two instances of OpenVPN at the same time, and I see that I need to make sure that the options ROUTE_TABLE, MARK, PREFIX, PREF, and DEV are unique for each vpn.conf file.

Are there recommendations for what to change those options to in my second vpn.conf file? Or can they be anything?

**Comment by peacey** [comment]
Hi @FreakySnake2,

You can just increment each value by 1 from the default config. For example, 

```ini
ROUTE_TABLE=102
MARK=0x170
PREFIX="VPN2_"
PREF=99
DEV=tun1
```

The only one you don't have to bother changing is PREF. That's the order preference in the IP rule table. As long as you use unique mathcing rules for the VPN, then the PREF doesn't have to be unique.
