### ISSUE TITLE
client-to-client routing

### ISSUE THREAD

**Issue by martinportmann** [peacey/split-vpn#12]
Split-vpn is working great and it connects to my openVPN server and I can use the internet in a safe way.
I would like to use it also to link site-to-site or user-to-site. This means that I would like that within the OpenVPN servers network (e.g. 10.10.X.X) everybody can communicate. Especially I would like to export also the networks connected to the UDP-Pro to the OpenVPN.

If I ping from another user/site connected to the OpenVPN network the ICMP packet enters the UDM and leaves through the normal WAN interface and gets lost of course.
I tried to add a OPENVPN_NET_IPV4 env variable (would contain "10.10.0.0/16") and create a mangle rule with -d ${ip} but had no success.

Any help .. tips?

**Comment by peacey** [comment]
Hi Martin,

I've been trying to replicate what you're asking, but I'm not sure what you mean. 

If the VPN is on a different subnet than any network on the UDM, then I was able to:
* Ping from UDM forced client (or the UDM itself) to a client on the VPN network (site-to-client)
* Ping from a client on the VPN network to the UDMP's VPN IP (client-to-site)
* Ping from the UDMP to the VPN server's IP and vice-versa (site-to-site)

Is that what you mean? Or are you asking that you want to have a network on the UDM on the same subnet as the VPN network. As in you created a VLAN network with the VPN subnet and then you want clients on this network to have their own VPN assigned IPs that can communicate across the VPN network? Is that what you're asking? 

Sorry just trying to understand better so I can replicate the problem properly.

**Comment by martinportmann** [comment]
Hello Peacey

I have an own OpenVPN server that has a network 10.10.0.0/16 assigned to tun0.
I have an UDM-Pro that has the networks 10.11.100.0/24, 10.11.101.0/24, 10.11.102.0/24, 10.11.103.0/24

What I would like to achieve is:
[1] Connect with mobile/computer to OpenVPN server and use the 10.11.X.X networks transparently
[2] In the future I will have other UDM-Pro installations that would like to join the network for everybody to be able to talk to everybody.

**What works is any routed address behind the UDP-Pro. What does not work is accessing the UDP-Pro (10.11.100.1, 10.11.101.1, etc).**
From the VPN server a ping to 10.11.101.1 I can see the ICMP echo request going out but not coming back.
From the UDP-Pro I see the ping from 10.10.0.1 to 10.11.101.1 coming in on tun0. I see that the reply goes out the WAN interface instead of tun0.

My openvpn.conf on the server is (version: 2.3.4-X)
local X.X.X.X
port X
proto udp
dev tun
tls-server
ca keys/ca.crt
cert keys/hostname.domain.crt
key keys/hostname.domain.key
dh keys/dh2048.pem
tls-auth keys/ta.key 0
server 10.10.0.0 255.255.0.0
ifconfig-pool-persist ipp.txt
keepalive 10 120
auth SHA256
cipher AES-256-CBC
max-clients 1000
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
log /var/log/openvpn.log
mute 20
remote-cert-tls client
hand-window 120
mssfix 1400
fragment 1400
tun-mtu 1500

\# DNS
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

\# Routes
push "route 10.10.0.0 255.255.0.0"
client-to-client
client-config-dir /etc/openvpn/ccd
push "route 10.11.100.0 255.255.255.0"
push "route 10.11.101.0 255.255.255.0"
push "route 10.11.102.0 255.255.255.0"
push "route 10.11.103.0 255.255.255.0"
route 10.11.100.0 255.255.255.0
route 10.11.101.0 255.255.255.0
route 10.11.102.0 255.255.255.0
route 10.11.103.0 255.255.255.0

I have a ccd file hostname.domain for the UDM Pro:
iroute 10.11.100.0 255.255.255.0
iroute 10.11.101.0 255.255.255.0
iroute 10.11.102.0 255.255.255.0
iroute 10.11.103.0 255.255.255.0

**Comment by peacey** [comment]
Thank you Martin. That explained everything. 

So I replicated your setup, but I was successfully able to ping the 10.11.10x.x LAN networks behind the UDM with the same config as yours (including the UDM's IP and connected clients on that subnet) from the VPN server (or even an external client connected to the VPN server). I didn't have to do anything extra.

I'm not sure why it didn't work for you. When you ping from the VPN server to 10.11.100.254 (the UDMP's IP), the tcpdump on the UDMP (`tcpdump -ni any icmp`) should look like:

```
00:32:46.497963 IP 10.10.0.1 > 10.11.100.254: ICMP echo request, id 45, seq 2, length 64
00:32:46.497997 IP 10.11.100.254 > 10.10.0.1: ICMP echo reply, id 45, seq 2, length 64
```

So the ping came in from 10.10.0.1 (tun0) and the reply is going back to 10.10.0.1. The route table on the UDMP contains a route of 10.10.0.0/16 for tun0, so anything destined to 10.10.x.x should go out tun0 and not the WAN interface. So it's weird your pings are going out the WAN interface if they are destined for the VPN subnet.

Can you show me your route table please? Run `ip route show` on the UDMP. Blackout the WAN subnet at the end. 

Thanks!

**Comment by peacey** [comment]
Actually, I think I figured out your problem. You are not using "topology subnet" option in your VPN server config. The default topology is net30, which is not recommended for new servers, and doesn't add subnet routes automatically (instead uses peers). If I don't use the `topology subnet` option, I am also unable to ping the UDMP through the VPN. 

So I recommend you add the `topology subnet` option into your VPN server config and try again. After you add that and you connect to the VPN server on the UDMP, check that the UDMP route table contains the route `10.10.0.0/16 dev tun0`.

**Comment by martinportmann** [comment]
Thanks a lot.
This resolved the issue.
