### ISSUE TITLE
Local UDM-SE traffic through VPN

### ISSUE THREAD

**Issue by FreakySnake2** [peacey/split-vpn#120]
Hello again, @peacey. Thank you for your help before. I have another basic question for you just to make sure I’m doing things correctly. I want the traffic generated by my UDM-SE to go through my OpenVPN tunnel. I believe in the vpn.conf file, I will do this by setting the FORCED_LOCAL_INTERFACE variable. Is that correct? I already have all my clients going through the VPN, and now the UDM-SE itself remains. I want its telemetry, software updates, and other data it produces like ping tests, etc. to go through the VPN. Then once that’s set, I believe all traffic on my network will go out through the VPN.

Also, in the vpn.conf file, you say that FORCED_LOCAL_INTERFACE should be set to eth8 for the WAN1/Ethernet port for the UDM-Pro. I have a UDM-SE, and I’m just trying to verify if eth8 is still correct. Here is a screenshot of what the ports page looks like:
![IMG_0072](https://user-images.githubusercontent.com/10158528/182051601-818eee2e-fd2d-4ec2-8d12-925844345c0e.jpeg)

**Comment by peacey** [comment]
Hi @FreakySnake2,

Sorry for the late reply. Yes you can use FORCED_LOCAL_INTERFACE to force local traffic, and you are using eth8 (port 9 is eth8, port 10 is eth9). However, this feature isn't tested very thoroughly and can break things like remote access and other local traffic features. So if you use it, do test it thoroughly to make sure everything is still working well.

**Comment by peacey** [comment]
Hi @FreakySnake2,

This issue has become stale so I'm closing it, but if you ever want to continue debugging, feel free to re-open!
