### ISSUE TITLE
Fortinet protocol

### ISSUE THREAD

**Issue by baconlive** [peacey/split-vpn#124]
Can you update the docker image with an updated version of openconnect that supports fortinet protocol?

**Comment by peacey** [comment]
Hi there! Sorry for the delay. I have updated it now and it seems to have the fortinet protocol when I check --help. Though I did not test it since I don't have any access to a fortinet VPN server.

So please do test it and report back if you can!

Thanks.

**Comment by baconlive** [comment]
Hello! I confirm the updated image works fine with fortinet protocol-

Thanks.

Guido
