### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by jacobj95** [peacey/split-vpn#125]
Hi! I recently got a UDM setup at my house and have been trying to set this up. I’m definitely not as tech savvy as I thought and I’m having issues and was seeing if you could walk me through it, I was going to try to message you on Reddit but it looks like your account was removed. I would be very grateful, thanks!

**Comment by peacey** [comment]
Hi @jacobj95. You can message me on u/peacey8 on Reddit and I can help you, or you can tell me what issues you're having here.

**Comment by peacey** [comment]
Closing this since we connected on Reddit.
