### ISSUE TITLE
swansong PureVPN Certificate Issue

### ISSUE THREAD

**Issue by sgillott** [peacey/split-vpn#126]
Hello! I'm very much looking forward to getting this working, but I think I have a certificate issue.
Following the instructions, I have downloaded USERTrustRSACertificationAuthority.crt using
`curl -Lo USERTrustRSACertificationAuthority.crt https://raw.githubusercontent.com/peacey/split-vpn/main/examples/strongswan/purevpn/USERTrustRSACertificationAuthority.crt`

running `./run-vpn.sh` I get in the swansong logs:
```
Sep 21 20:26:43 12[ENC] <purevpn|1> received fragment #4 of 4, reassembled fragmented IKE message (4244 bytes)
Sep 21 20:26:43 12[ENC] <purevpn|1> parsed IKE_AUTH response 1 [ IDr CERT CERT AUTH EAP/REQ/ID N(AUTH_FOLLOWS) ]
Sep 21 20:26:43 12[IKE] <purevpn|1> received end entity cert "CN=*.pointtoserver.com"
Sep 21 20:26:43 12[IKE] <purevpn|1> received issuer cert "C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA"
Sep 21 20:26:43 12[IKE] <purevpn|1> no trusted RSA public key found for 'xxx.xxx.xxx.xxx'
Sep 21 20:26:43 12[ENC] <purevpn|1> generating INFORMATIONAL request 2 [ N(AUTH_FAILED) ]
Sep 21 20:26:43 12[NET] <purevpn|1> sending packet: from xxx.xxx.xxx.xxx[yyyy] to xxx.xxx.xxx.xxx[yyyy] (68 bytes)
Sep 21 20:26:47 07[CFG] received stroke: terminate 'purevpn'
Sep 21 20:26:47 07[CFG] no IKE_SA named 'purevpn' found
Sep 21 20:26:47 06[CFG] received stroke: initiate 'purevpn'
```
so, has something has changed certificate-wise which is why it reports **no trusted RSA public key found**, and the [USERTrustRSACertificationAuthority.crt](https://raw.githubusercontent.com/peacey/split-vpn/main/examples/strongswan/purevpn/USERTrustRSACertificationAuthority.crt) is no longer valid?

**Comment by peacey** [comment]
Hi there @sgillott,

The certificate is valid, but if you're using a PureVPN server with the hostname matching *.ptoserver.com instead of *.pointtoserver.com, you need to add `id = pointtoserver.com` to the remote-0 section in your `purevpn.conf` file. See if that works for you.

**Comment by sgillott** [comment]
Thank you! That seems to be much happier now.
