### ISSUE TITLE
Kill specific tunnel

### ISSUE THREAD

**Issue by ionwerz** [peacey/split-vpn#127]
Please update the Readme file:
This command `kill -TERM $(pgrep -f "openvpn.*tun0")` do not work anymore. Tested on UDM-Pro, Network version 7.2.94, `pgrep -f "openvpn.*tun0"` returns empty result.

**Comment by peacey** [comment]
Hello @ionwerz,

That command should still work (I just tested it on latest). 

Are you using tun0 for your tunnel interface? Make sure you change tun0 in that command to whatever your tunnel interface is that you defined in vpn.conf.

If you're still having problems, please show me the output of: 

```sh
ps aux | grep openvpn
```

Thanks!

**Comment by ionwerz** [comment]
Sorry, my bad. I have forgot that I have changed the tun0 to tun2.
