### ISSUE TITLE
No traffic returning from Wireguard

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [peacey/split-vpn#129]
I've been using split-vpn for years successfully, but it randomly stopped working yesterday.  And I mean totally randomly - no updates or changes have occurred.

The connection establishes successfully and the UDM is able to ping via that interface.  The clients listed in `vpn.conf`, however, do not work.  Note that *some* clients (not all) are able to receive return pings from addresses like `1.1.1.1` and `bbc.co.uk`, but only the *first client* to send outbound traffic is able to maintain a connection.

I know this sounds strange because logically, everything is configured correctly.  Thinking it was a routing issue with old IP tables or something, I changed the following variables to unique values:

```
MARK=0x161
PREFIX="VVVPN_"
PREF=94
DEV=wg1
```

When viewing a packet capture from a machine that should be routed out wg1, I can see traffic leaving but no return traffic of any kind, except to an address (in this case, `1.1.1.1` that was the first outbound connection when the tunnel was brought up):

![image](https://user-images.githubusercontent.com/18420782/196761497-f2d8c20e-13bd-4b27-9be2-7df015d0e05b.png)

Another example from another machine:

![image](https://user-images.githubusercontent.com/18420782/196762692-eeb41914-ed80-4be4-bf5d-b13b397bc2b6.png)

I have upgraded the UDM software since then, in an attempt to fix this.  Current versions:

Network 7.2.94
UDM Pro v1.1

wireguard.log:

```
Warning: `/mnt/data/split-vpn/wireguard/mullvad/wg1.conf' is world accessible
[#] ip link add wg1 type wireguard
[#] wg setconf wg1 /dev/fd/63
[#] ip -4 address add 10.64.163.187/32 dev wg1
[#] ip link set mtu 1420 up dev wg1
[#] ip -4 route add 0.0.0.0/1 dev wg1 table 109
[#] sh /etc/split-vpn/vpn/updown.sh wg1 up
[Wed Oct 19 13:11:45 EDT 2022] split-vpn: wg1 up: Loading configuration from /mnt/data/split-vpn/wireguard/mullvad/vpn.conf.
[Wed Oct 19 13:11:45 EDT 2022] split-vpn: Using IPv4 gateway from table 201: via x.x.x.x dev eth8.
```

vpn.conf:
```
FORCED_SOURCE_IPV4="192.168.20.43/32 192.168.20.29/32 192.168.20.25/32"
DNS_IPV4_IP="DHCP"
DNS_IPV4_PORT=53
KILLSWITCH=1
REMOVE_KILLSWITCH_ON_EXIT=0
REMOVE_STARTUP_BLACKHOLES=1
VPN_PROVIDER="external"
GATEWAY_TABLE="auto"
WATCHER_TIMER=1
ROUTE_TABLE=109
MARK=0x161
PREFIX="VVVPN_"
PREF=94
DEV=wg1
```

**Comment by peacey** [comment]
Hi @TokugawaHeavyIndustries ,

That's very odd. Did you try to restart the UDM to see if it still happens? Which UDM version (model and software version) are you on?

Are you using a private VPN or some common VPN provider? Which one? Have you tried a different server?

Also, can you try testing with `KILLSWITCH=0` and `REMOVE_KILLSWITCH_ON_EXIT=1` and `MARK=169`?

Thanks!

**Comment by peacey** [comment]
Hi @TokugawaHeavyIndustries,

This issue has become stale to I'm closing it. If you are still figuring this out, feel free to re-open and ask more questions!
