### ISSUE TITLE
Any plans on porting this for use with wireguard?

### ISSUE THREAD

**Issue by isiahw1** [peacey/split-vpn#13]
This works great and it would be nice if this could be ported for use with wireguard.

**Comment by peacey** [comment]
I've already got this script working with WireGuard with a few tweaks, but the only thing is there are multiple implementations of WireGuard on the UDM/P. There is a software docker implementation and there is a kernel module implementation. So I just want to make it customizable enough that people can choose which implementation to use. 

I will try to get it done in the next week or so.

**Comment by peacey** [comment]
Hi @isiahw1, sorry it took a  bit longer but I finally updated this script with wireguard support. Please check out the README for how to use it with the wireguard kernel module or wireguard-go docker container, and tell me if it works for you and if there any issues. 

Thanks!

**Comment by peacey** [comment]
Hi @isiahw1,

I have implemented this and multiple people have successfully tested the WireGuard support and it seems to be working fine. I will close this feature request now since it is complete, but if you try WireGuard and have any problems, please open a new issue.

Have a nice day!
