### ISSUE TITLE
Split VPN set up with UniFi Site to site connection not working

### ISSUE THREAD

**Issue by smgraver1** [peacey/split-vpn#131]
Hi,

I recently just attempted to set up the split-vpn to try and have a certain website, when being requested, send traffic over the site to site vpn. I followed the instructions and it seems my devices I have set up to work won’t connect to websites and will only ping the ip’s that I have set for exclusion. How do I fix this?

**Comment by peacey** [comment]
Hello @smgraver1,

Please show me your vpn.conf and tell me which type of site-to-site you're using (IPSec or OpenVPN)?

Thanks!

**Comment by smgraver1** [comment]
<img width="637" alt="Screenshot 2022-10-26 at 3 34 44 PM" src="https://user-images.githubusercontent.com/64740260/198122299-215377be-0c54-4909-a584-c18aa412b37f.png">
<img width="687" alt="Screenshot 2022-10-26 at 3 35 30 PM" src="https://user-images.githubusercontent.com/64740260/198122303-0c82f9c3-07e5-4842-9697-96b79c8ac4dc.png">
<img width="726" alt="Screenshot 2022-10-26 at 3 37 26 PM" src="https://user-images.githubusercontent.com/64740260/198122306-60329674-a241-42e8-8108-94526ba7729e.png">
using IPSec

**Comment by smgraver1** [comment]
Even when I have website put in and some ip’s excluded. It won’t reach the internet and connect to any website. I want it so that it uses the vpn when trying to connect to xfinity.com but uses normal network for everything else.

**Comment by smgraver1** [comment]
I have now switched to using the OpenVPN protocol to try that and i'm getting progress. I can ping devices from one device on local network to a device on the remote network and vice versa which is great. But my devices that are on the vpn still can't access any website or internet through its own connection or the vpn connection. Here is my conf now. How do I get my machine that is on the remote network to go through the vpn when trying to access xfinity.com site but go through normal internet when accessing anything else.
<img width="626" alt="Screenshot 2022-10-27 at 2 10 28 PM" src="https://user-images.githubusercontent.com/64740260/198366552-507f2d71-08c7-459e-af4c-cf6aa8c2b709.png">
<img width="620" alt="Screenshot 2022-10-27 at 2 10 49 PM" src="https://user-images.githubusercontent.com/64740260/198366563-08fcaaa9-1ce2-4d28-a7e0-51c95ff0f06d.png">
<img width="619" alt="Screenshot 2022-10-27 at 2 11 05 PM" src="https://user-images.githubusercontent.com/64740260/198366580-cbfc3243-ba6b-4e77-9314-4d8acdb98237.png">

**Comment by peacey** [comment]
It should work on IPSec or OpenVPN. Anyhow, it's working with openvpn so lets use that one. 

Two things. First, the FORCED_* options work independently of each other. FORCED_DESTINATIONS_* forces any source traffic (not just the ones you defined in FORCED_SOURCE_*) going to those destinations to go through the VPN instead. If you want to only force a single device or specific devices for a particular destination, you should use CUSTOM_FORCED_RULES_IPV4 instead (and set any other FORCED_SOURCE_* to empty). For example with your two MACs, just add this to the section after the FORCED_SOURCE_* variables:

```ini
CUSTOM_FORCED_RULES_IPV4="
     -m mac --mac-source 90:DD:5D:F3:AD:F8 -d xfinity.com
     -m mac --mac-source F0:18:98:E8:51:9E -d xfinity.com
"
```

You can also do the same with `CUSTOM_FORCED_RULES_IPV6` if you use IPv6 on your network.

Second, if you want to force a domain name, then I don't advise you just put it in the vpn.conf like this. This is because the IP for the domain is resolved when the VPN starts, and the IPs might change, and those new IPs won't be forced. I recommend you instead use the [instructions here](https://github.com/peacey/split-vpn/tree/main/ipsets) for how to force a domain name by using the UDM's built-in dnsmasq server and ipsets. As long as you are using the built-in dnsmasq server, this way will work much better. Once you set that up, you can also use `CUSTOM_FORCED_RULES_IPV4` to only force specific macs to those domains like:

```ini
CUSTOM_FORCED_RULES_IPV4="
    -m set --match-set VPN_FORCED dst -m mac --mac-source 90:DD:5D:F3:AD:F8
    -m set --match-set VPN_FORCED dst -m mac --mac-source F0:18:98:E8:51:9E
 "
```

**Comment by smgraver1** [comment]
Thanks so much for the help. So all of that is working now except I am getting a location error when trying to watch tv through xfinity stream. Probably because the server that the xfinity stream site reaches out to is not listed under xfinity.com so it knows the location. I led to using nettop in terminal to watch the output of the servers and notice the location name and city of device in a site that ended in (____.comcast.net). I was wondering if there's a way to enter a website like comcast.net to go through the vpn only like xfinity.com but it ends every site with the ending of comcast.net through the vpn. Say it is california.la.comcast.net and newyorkcity.ny.comcast.net I want to redirect all of them to VPN.

**Comment by peacey** [comment]
Did you end up using the domain forcing method woth EXEMPT-_IPSETS or did you just add the domain to EXEMPT_DESTINATIONS? 

If you're using the domain forcing method with ipsets, then adding "comcast.net" will force all subdomains of comcast.net as well. If you're using EXEMPT_DESTINATIONS, then you have to add all the subdomains yourself. 

Also, I would be careful with doing it this way. It's a cat and mouse game trying to figure out what server they're using to stream and force that to the VPN. It might be easier to force the entire device with a separate network or WiFi that you connect to when you want to stream Xfinity. Just a thought in case your other method doesn't work so well.

**Comment by smgraver1** [comment]
I agree that would be an easier way but this way would be better so a lot of the other traffic from the device isn’t also going over the vpn. My set up is I have an Apple TV that is at a different house than the xfinity connection to cable in home with the xfinity stream app and I’d like to watch my xfinity from this other house. The Apple TV also runs the home hub for HomeKit devices and id like most of that to still be over the normal connection not vpn. If this ends up not working I’ll just send the entire Apple TV over the vpn. How would I set the conf to have all device traffic go over the site to site vpn?

**Comment by smgraver1** [comment]
When trying to do the set up for domain forcing with ip set when i run ./add-dnsmasq-ipsets.sh is says it was not found?

**Comment by smgraver1** [comment]
I have everything set up how it is supposed to be now. But the websites I have forced to travel over the vpn get stuck and never load. How do I fix this?

**Comment by peacey** [comment]
@smgraver1, are you able to ping the domains you forced? Are they just not loading over HTTP, but you're able to ping them? If that's the case, that sounds like an MSS clamping issue, and you might want to try reducing MSS_CLAMPING_IPV4 to 1200 or lower for example (try 1200, 1100, 1000). If it works, we can find the correct value with a ping test.

**Comment by smgraver1** [comment]
I cannot ping the addresses at all.

**Comment by peacey** [comment]
Oh that's odd, I thought it was working for pinging IPs. Can you show me your latest vpn.conf configuration?

Also, can you show me the output of these commands on the UDM:

```sh
ip route show dev tun1
ip addr show dev tun1
ping -I tun1 1.1.1.1
```

**Comment by smgraver1** [comment]
![10FA90D9-EB70-49E9-B81D-88D2C934DE60_1_101_o](https://user-images.githubusercontent.com/64740260/198847618-47baa6f9-2bb7-48ff-a21d-9d5d76d61bb7.jpeg)
![317413BE-3380-443A-8D14-8EFF733705E8_1_101_o](https://user-images.githubusercontent.com/64740260/198847623-07d5d94f-d2dc-4c80-8d6a-679083e68849.jpeg)
![EFD6016F-0C63-4580-A8B8-F26D464B7146_1_101_o](https://user-images.githubusercontent.com/64740260/198847625-87861bef-8d72-4bf9-8873-3cb0aa42210e.jpeg)
![F859FC30-79E9-401F-8B3D-713382672C81_1_101_o](https://user-images.githubusercontent.com/64740260/198847627-5a61bb14-a12c-44bd-8325-ce325e161b8a.jpeg)
<img width="647" alt="Screenshot 2022-10-29 at 2 34 48 PM" src="https://user-images.githubusercontent.com/64740260/198847628-263cc32c-0f6d-4fd9-8075-660c205622f1.png">

**Comment by smgraver1** [comment]
I am able to get packets to ping the router on the other side of the site to site tunnel but not external websites through it.

**Comment by peacey** [comment]
On the UDM, you're able to ping the router on the other side or other local devices like:

```sh
ping -I tun1 router_ip
```

But you're not able to do `ping -I tun1 1.1.1.1`?

Do you have any firewall rules on the remote router than can prevent internet access?

**Comment by smgraver1** [comment]
Yes this is the case. I can send you my firewall rules or what rule should I set to let the internet pass through?

**Comment by peacey** [comment]
Can you temporarily disable all your firewall rules to test if it is the firewall and try the ping again?

**Comment by smgraver1** [comment]
How do I temporarily disable all firewall rules?

**Comment by peacey** [comment]
I'm not sure if there's an easy way, I was just thinking to just disable the rules one by one, but if you have too many that might take time. 

You can try running this on your remote UDM to allow all traffic with iptables temporarily:

```sh
iptables -I INPUT 1 -j ACCEPT
iptables -I OUTPUT 1 -j ACCEPT
iptables -I FORWARD 1 -j ACCEPT
```

Then test the pinging from the local UDM through tun1 to 1.1.1.1. Then you can delete the rules when you're done testing, like:

```sh
iptables -D INPUT -j ACCEPT
iptables -D OUTPUT -j ACCEPT
iptables -D FORWARD -j ACCEPT
```

**Comment by smgraver1** [comment]
My remote device is actually a USG not a UDM. How would I do the iptables command for that device?

**Comment by peacey** [comment]
Oh I'm not really sure how to disable it on the USG. 

Maybe can you add an Any/Any (from/to) ACCEPT firewall rule at the beginning of each Internet IN, Internet OUT, Internet Local, LAN IN, LAN OUT, and LAN Local?

**Comment by smgraver1** [comment]
Tried that and still nothing. It seems when I do traceroute on a local computer routing over the vpn to a site that is set it'll go to the ip address I have set for teh site to site 192.168.6.1 but then get stuck there. So the request gets to the remote side of the site to site but never reaches the internet to receive the data.

**Comment by peacey** [comment]
Hmm, that seems like the USG is blocking the traffic. 

Okay can you SSH into the USG and run this? 

```sh
tcpdump -ni any host 1.0.0.1
```
Also on the local UDM, run the same tcpdump in SSH. Then, on another SSH window on the local UDM, run this ping 

```sh
ping -I tun1 1.0.0.1
```

Then show me the output of the two tcpdumps.

**Comment by smgraver1** [comment]
It says on USG tcpdumps is a command that wasn't found

**Comment by peacey** [comment]
Did you write tcpdump or tcpdumps (with the s)? It's supposed to be without the s.

**Comment by smgraver1** [comment]
i copy and pasted exactly what you sent

**Comment by peacey** [comment]
Can you try `sudo tcpdump` instead on the USG?

**Comment by smgraver1** [comment]
![IMG_AB9A30B79BDA-1](https://user-images.githubusercontent.com/64740260/198853446-71b4080c-93b6-4bbd-a3fb-7a98621cbeb0.jpeg)
This is the USG the Remote Site
<img width="648" alt="Screenshot 2022-10-29 at 5 43 00 PM" src="https://user-images.githubusercontent.com/64740260/198853452-0f1a8ef1-c584-4119-98a4-21a897c63654.png">
This is UDM the Local Site

**Comment by peacey** [comment]
Thanks. It does seem like on the USG, either the packets from 192.168.5.1 are not being forwarded to the WAN, or they're not being masqueraded. 

Let's check if they're being forwarded to the WAN interface with a tcpdump on the WAN interface (eth0 I think?). Again run this on the USG?

```sh
tcpdump -ni eth0 host 1.0.0.1
```

Then run the ping through tun1 on the local UDM again.

**Comment by smgraver1** [comment]
![image](https://user-images.githubusercontent.com/64740260/198854662-912dcc0d-02b5-42b7-a6a0-beb0e36359ee.png)

**Comment by peacey** [comment]
Okay, but I'm not sure if eth0 is the wan or lan. Which USG are you using? USG-3P or USG-Pro? Can you show me the output of `ip route` on your USG?

**Comment by smgraver1** [comment]
im using USG-3P. eth0 is my WAN as it shows my wan address when running ip route

**Comment by smgraver1** [comment]
![image](https://user-images.githubusercontent.com/64740260/198854982-b1a412ec-9ccd-4a7c-bccd-19151f498630.png)

**Comment by peacey** [comment]
Okay great to know! So it seems like the problem is the packets aren't being masqueraded out of the WAN (SNATted to change source IP to your WAN IP). The USG must only be setup to masquerade local traffic.

Can you run this on your USG to add a masquerade rule for everything out of eth0?

```sh
configure
set service nat rule 5010 description 'masquerade for WAN'
set service nat rule 5010 outbound-interface eth0
set service nat rule 5010 type masquerade
set service nat rule 5010 protocol all
commit;save;exit
```

Then try the ping and tcpdump again.

**Comment by smgraver1** [comment]
Sites are working now!

**Comment by peacey** [comment]
That's great! And browsing websites is working now?

So the commands I gave you will be wiped at the next provision. You'll need to use a config.gateway.json file on your USG with the following contents so the rule gets added on provision:

```json
{
   "service":{
      "nat":{
         "rule":{
            "5010":{
               "description":"Masquerade for WAN",
               "outbound-interface":"eth0",
               "type":"masquerade"
            }
         }
      }
   }
}
```

Have you used this file before, do you know how to install it for the USG and test it?

**Comment by smgraver1** [comment]
No i have never used it

**Comment by peacey** [comment]
Basically, read the "Creating the config.gateway.json File" instructions from Ubiquiti [here](https://help.ui.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration-Using-config-gateway-json).

I already gave you the contents, so you just have to figure out the location to place the file in (on the same computer or CloudKey with the Network application is running from). 

Then restart the USG so it's fresh, and force a provision to make sure the masquerade is working. Tell me if you run into any issues.

**Comment by smgraver1** [comment]
Thanks! is there a way in the VPN_domains.conf to set all ip's that start with the number 96 to be sent over the VPN?

**Comment by peacey** [comment]
Not in the VPN_domains.conf but you can add that as a subnet in vpn.conf with the FORCED_DESTINATIONS_IPV4 option.

```ini
FORCED_DESTINATIONS_IPV4="96.0.0.0/8"
```

**Comment by peacey** [comment]
Hi @smgraver1,

This issue has become stale to I'm closing it. If you are still figuring this out, feel free to re-open and ask more questions!
