### ISSUE TITLE
use pihole located on another host

### ISSUE THREAD

**Issue by troian** [peacey/split-vpn#135]
hi, thanks a lot for the fantastic project and instructions.

I'm thinking of using pihole located on a dedicated RPI, and wondering if it going to work.

**Comment by peacey** [comment]
Hi @troian,

Yes it will work fine. Just set the pihole internet IP with `DNS_IPV4_IP` in your `vpn.conf`. The traffic will go through the VPN for the DNS requests.

**Comment by troian** [comment]
That's lovely to hear @peacey, thank you.
Is anything special in this case for [ipsets](https://github.com/peacey/split-vpn/tree/main/ipsets) configuration needed or it all remains unchanged?

**Comment by peacey** [comment]
Do you want to use ipsets for domain forcing or just forcing specific list of IPs?

**Comment by troian** [comment]
Domain forcing

**Comment by peacey** [comment]
Oh sorry, in that case you can't use an external pihole, not even on the same local network. The pihole (or dnsmasq, which pihole uses internally) has to be run on the UDM. Pihole/dnsmasq is set up to add IPs that are looked up to an ipset, but it can only add it to an ipset on the system that is running it.

**Comment by troian** [comment]
I see, that makes sense.
Thanks for the details tho.

**Comment by troian** [comment]
sorry for bothering with it, realized I forgot the main reason I want pihole to run an different host.
it is mainly due to this issue 

```
Long-term load (15min avg) larger than number of processors: 4.6 > 4
This may slow down DNS resolution and can cause bottlenecks.
```

have you got any things on tweaking pihole itself?

**Comment by peacey** [comment]
I've never had issues with slow DNS resolutions when I run pihole on the UDM. That seems like a warning that it could impact it, but not sure how terrible the effect is in practice. 

And no you can't use ipsets on the other computer because the UDM forces the ipsets for the configured clients in vpn.conf, but it can't access the ipsets if they're on another computer. So pihole+ipsets needs to be on the UDM. The only way that could work is if you made your computer the network router.

**Comment by peacey** [comment]
Hi @troian,

Closing this as the issue has been resolved I believe. Feel free to re-open if you have any more questions.

**Comment by troian** [comment]
it looks like external DNS is now an [option](https://github.com/peacey/split-vpn/commit/d2d79bc4518534d75f064b2d49a77c556f7ab9ad)?
