### ISSUE TITLE
[Question] Multiple ovpn clients - ROUTE_TABLE, MARK, PREFIX, PREF, DEV

### ISSUE THREAD

**Issue by Sleinous** [peacey/split-vpn#136]
Hello,
Wondering if you'd be able to help me as i'm unable to find any further information on the internet - i'm looking to run a second openvpn instance so i've followed the instructions and created a separate directory with separate vpn.conf. However second ovpn client connection isn't working and I suspect it has something to do with my incrementation of the following :

"Make sure the options ROUTE_TABLE, MARK, PREFIX, PREF, and DEV are unique for each vpn.conf file so the different VPN servers don't share the same tunnel device, route table, or fwmark. If you are using nexthop, DEV does not have to be unique."

I set ROUTE_TABLE=102 ; MARK=0x170 ; PREFIX="VPN2_" ; PREF=99 ; DEV = tun1 (this is the only one i'm 99% sure is OK)

The first 4 I have no idea if incrementing in this fashion is supported nor how i'm meant to increment or make them unique (my first ovpn vpn.conf file is using your defaults). I strongly suspect MARK is wrong in my above config..

If you're able to shed any light on the above i'd be very grateful
Thanks in advance
Sleinous

**Comment by Sleinous** [comment]
Just resolved it, I messed up my incrementation of route_table, meaning I had fwmark 0x169 and 0x170 both listing 101 as route_table in 'ip tables' command...
Case closed

**Comment by Sleinous** [comment]
Scratch that, it's stil not working, as soon as I kill the VPN device has internet connectivity again. Seems this second ovpn entry isn't working, are my options set correctly? 
I set ROUTE_TABLE=102 ; MARK=0x170 ; PREFIX="VPN2_" ; PREF=100 ; DEV = tun1 (this is the only one i'm 99% sure is OK)

**Comment by peacey** [comment]
Hi @Sleinous,

All your increments are correct. Yes you can increment MARK like that. 

What issues are you having? Did the second VPN start? Can you show me the log?

**Comment by Sleinous** [comment]
Thanks for your reply @peacey  This one was a bit of an odd one and I just fixed it (or atleast VPN is now up). Seems I had an ip conflict on openvpn setups, one was using same vpn ip as the other and that seemed to be the issue, as soon as I started one up, the other wouldn't work anymore and vica versa

**Comment by peacey** [comment]
Great to hear @Sleinous. So is everything working now?

**Comment by Sleinous** [comment]
Yep we can close thanks for the great work on this, im running uxg pro

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peacey** [comment]
Feel free to reopen if you have any more questions. Have a nice day!
