### ISSUE TITLE
wireguard kmod -> dns not forced . some destinations not loading

### ISSUE THREAD

**Issue by discorogge** [peacey/split-vpn#138]
### Herro, first time user . nice repo man :)

I want all subnets on the VPN so i added interfaces in force source.
Communications between subets still open, so i exempted my subnets. 
Researched other issues here and changed mss clamp...

dnsleaktest.com shows me the dns server i put on the udmp WANout DNS(dhcp dns not set). If i do not specify i get ISP DNS.
reddit doesnt load. cant use duckduckgo , etc, etc.

Have not touched IP6 much, left everything i could out? Tried with IP6 as well, doesnt change results.

wireguard seems to boot up ok and does not complain.

No idea where to look for trouble, spent some time reading without finding solutions. 
Happy about suggestions :)

vpn.conf:

 Force these sources through the VPN.
 Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
FORCED_SOURCE_INTERFACE="br0 br20 br30 br40"
FORCED_SOURCE_IPV4=""
FORCED_SOURCE_IPV6=""
FORCED_SOURCE_MAC=""

 Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
 Maximum 15 ports per entry.
FORCED_SOURCE_IPV4_PORT=""
FORCED_SOURCE_IPV6_PORT=""
FORCED_SOURCE_MAC_PORT=""

 Force these destinations through the VPN.
 These destinations will be forced regardless of source.
 Format: [IP/nn]
FORCED_DESTINATIONS_IPV4=""
FORCED_DESTINATIONS_IPV6=""

FORCED_LOCAL_INTERFACE=""

 Exempt these sources from the VPN.
 Format: [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
EXEMPT_SOURCE_IPV4=""
EXEMPT_SOURCE_IPV6=""
EXEMPT_SOURCE_MAC=""

 Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
 Maximum 15 ports per entry.
EXEMPT_SOURCE_IPV4_PORT=""
EXEMPT_SOURCE_IPV6_PORT=""
EXEMPT_SOURCE_MAC_PORT=""

 Exempt these destinations from the VPN.
 Format: [IP/nn]
EXEMPT_DESTINATIONS_IPV4="192.168.10.0/24 192.168.20.0/24 192.168.30.0/24 192.168.40.0/24"
EXEMPT_DESTINATIONS_IPV6=""

 Format: [IPSet Name]:[src/dst,src/dst,...]
FORCED_IPSETS=""
EXEMPT_IPSETS=""

 VPN port forwards.
 Format: [tcp/udp/both]-[VPN Port]-[Forward IP]-[Forward Port]
PORT_FORWARDS_IPV4=""
PORT_FORWARDS_IPV6=""

 Example: Get DNS from DHCP
DNS_IPV4_IP="217.64.148.33"
DNS_IPV4_PORT=53
 Set this to the interface (brX) the DNS is on if it is a local IP. Leave blank for
 non-local IPs. Local DNS redirects will not work without specifying the interface.
DNS_IPV4_INTERFACE=""

DNS_IPV6_IP="REJECT"
DNS_IPV6_PORT=53
DNS_IPV6_INTERFACE=""

 Bypass masquerade (SNAT) for these source IPs. This option should only be used if your
BYPASS_MASQUERADE_IPV4=""
BYPASS_MASQUERADE_IPV6=""

 Enabling kill switch drops VPN-destined traffic that doesn't go through the VPN.
KILLSWITCH=1

 Enable this only if you are testing or you don't care about your real IP leaking
 when the vpn client restarts or exits.
REMOVE_KILLSWITCH_ON_EXIT=1

REMOVE_STARTUP_BLACKHOLES=1

 Set the VPN provider.
 "openvpn" for OpenVPN (default), "openconnect" for OpenConnect, "external" for --->wireguard<-----,
 or "nexthop" for an external VPN client.
VPN_PROVIDER="external"

VPN_ENDPOINT_IPV4=""
VPN_ENDPOINT_IPV6=""

GATEWAY_TABLE="auto"

 Set the MSS clamping on packets going out the VPN tunnel. Usually, it is not needed to
 set this manually, but some VPN connections stall if the MSS clamping is not set correctly.
 Typical values range from 1240 to 1460, but it could be lower.
MSS_CLAMPING_IPV4="1420" -> not really sure about these . .
MSS_CLAMPING_IPV6="1420"

 Set this to the timer to use for the rule watcher (in seconds).
 The script will wake up every N seconds to re-add rules if they're deleted by
 the system, or change gateway routes if they changed. Default is 1 second.
WATCHER_TIMER=1

 Options for custom table and chains.
 These options need to be unique for each instance of openvpn if running multiple.
ROUTE_TABLE=101
MARK=0x169
PREFIX="VPN_"
PREF=99
DEV=wg0

Edit :
mss clamp down to 1380  is the solution to the random sites not loading .
DNS is still not forced according as setup in vpn.conf

**Comment by peacey** [comment]
Hi @discorogge,

What is the DNS you're using on the UDM LAN settings? What DNS is your computer getting with DHCP? Is it the UDM itself or some other DNS on your LAN?

Yes for sites not loading you might have to lower the MSS_CLAMP down even more. There is a way to use the ping tool to figure out the exact value, FYI.

**Comment by discorogge** [comment]
Good evening @peacey 

I have dhcp name server = auto. . I assume this is the DNS udm LAN setting, i have found no other nameserver setting.
I set wan name server = dnsserver put into vpn.conf . Though here I assumed "auto" would be forced according to vpn.conf
dns on my PC(as well as wives pc and 1 client on other subnet) = UDM gateway . 192.168.10.1

"Is it the UDM itself or some other DNS on your LAN?" br0 = 192.168.10.0/24 . UDM gateway = 192.168.10.1

I had a pihole->unbound docker container set up on my server before i tried this repo. It is disabled now since a few days.
All DNS setting should be on "auto". , and the nameserver options i have found is for the dhcp server and for the WAn interface. Do not know if you are referring to anything else.

Sidenote. 
I have not really seen anything mentioned about a local recursive dns server such as unbound . Is there any general downside or security reason not to host my own DNS solution?

**Comment by peacey** [comment]
So now when the VPN is on and you check from your forced clients in dnsleaktest, it's not showing you the correct DNS?

**Comment by discorogge** [comment]
Hello. @peacey 

I misspoke. 
My WAN dns server is set to the same server I specify in vpn.conf. 
So on dnsleaktest i get IP "Hello 45.148.17.50" and dns "148.17.50 | 45-148-17-50.pool.ovpn.com. . "
If i change my WANdns setting dnsleaktest will show me different dns results.

So yes, it looks like i am on the VPN service, but DNS_IPV4_IP="217.64.148.33" in vpn.conf is not beein forced.

So i am confused why the dns is not beeing routed based on my vpn.conf.

**Comment by discorogge** [comment]
Or am i simply misunderstanding what the vpn.conf is supposed to do with my router?

**Comment by peacey** [comment]
If you set DNS_* settings in vpn.conf, it should reroute all port 53 traffic for your forced clients to that DNS. So dnsleaktest should show that DNS only. 

Which browser are you using to check with dnsleaktest? Are you sure you don't have any DNS over HTTPs active somehow (OS level, or browser level)? A DNS over HTTPS/TLS would bypass this rule?

Also, in the Unifi network settings for each network you want to force DNS, make sure you haven't enabled any Content Filtering (that would reroute to Unifi's own DNS servers instead).

**Comment by discorogge** [comment]
I have another problem not directly connected to getting this repo to work, is this the right place to discuss that?

I use OVPN for VPNservice. They have the option to open a port in the VPN which i think is connected to my wireguard key. 
While using the UDM as a client to route all my traffic out of my network -> OVPN service I still want to access my server from my phone on the run.
If i wireguard in to my server via my router return packets gonna go through the VPN and get denied so my first idea was to go through an opened port on the OVPN server as seen in my paint picture, that way my phone lands on a docker network witch access to my services and internet access forced to the OVPN.

I have a hard time realizing this because my lack of knowledge, I tried to open necessary ports but i never reach my network..
 Is there an easier solution I should be looking at ? 
 
 If i use Kmod to setup a wireguard server on the udmp for example, how do I get it to multihop through split-vpn -> (my OVPN service) while still accessing my server on homenetwork.

![wireguard map](https://user-images.githubusercontent.com/66623195/202497007-f1da201b-4df7-48e2-97cf-a4364eb182c8.png)
