### ISSUE TITLE
When testing openvpn from step 4, dev0 and errors occur including no internet access to any interface (WAN goes down).

### ISSUE THREAD

**Issue by SystemJargon** [peacey/split-vpn#140]
Hi

When attempting the "how do i use it" step 4 to test, i run the commands as copy and paste (only difference is vpn provider and auth of course) and get errors. I extended the verbose using --verb 4, most of the output I get is all fine and the vpn provider replies back after auth successful connected, but then get this error starting.

```
2022-11-20 17:37:36 sitnl_send: rtnl: generic error (-19): No such device
2022-11-20 17:37:36 ERROR: Linux route add command failed
```

Then any clients ON ANY vlan then have no internet access. the WAN interface on my UDM-PRO then goes down following that.
terminating ctrl+c the step 4 commands then resumes internet.

the only other config changes I made was to vpn.conf, basically force VLAN5 to use the VPN, the rest is a normal WAN out (not use VPN).

dump of that below. everything else I left as default.

``` 
# Force these sources through the VPN.
# Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
FORCED_SOURCE_INTERFACE="br5"
FORCED_SOURCE_IPV4="192.168.5.1/24"
FORCED_SOURCE_IPV6=""
FORCED_SOURCE_MAC=""
```

my ovpn is stock as except 
```
remote [ip-removed]
auth-user-pass [removed]
```

I did toggle vpn.conf to have REMOVE_KILLSWITCH_ON_EXIT=0 and also "1". No luck either way.

So i had a look at section in your README.md, <i>The VPN exited or crashed and now I can't access the Internet on my devices. What do I do?</i> and tried the below;

```
# /etc/split-vpn/vpn/updown.sh tun0 force-down
: not foundvpn/vpn/updown.sh: ./vpn.conf: line 4:

# ls /etc/split-vpn/vpn/
add-vpn-iptables-rules.sh  install-split-vpn.sh       strongswan-updown.sh       vpn.conf.filled.sample     vpn.conf.sample
hooks                      setup-split-vpn.sh         updown.sh                  vpn.conf.minimal.sample    vpnc-script
```

line 4 of vpn.conf looks fine to me

```
# head -15 vpn.conf
### SPLIT VPN OPTIONS ###
# Enter multiple entries separated by spaces.
# Do not enter square brackets around the entries.

# Force these sources through the VPN.
# Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
FORCED_SOURCE_INTERFACE="br5"
FORCED_SOURCE_IPV4="192.168.5.1/24"
FORCED_SOURCE_IPV6=""
FORCED_SOURCE_MAC=""

# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
# Maximum 15 ports per entry.
FORCED_SOURCE_IPV4_PORT=""
FORCED_SOURCE_IPV6_PORT=""
```

so i checked the updown script first few lines, never changed it once, not one bit this script...

```
# head -10  /etc/split-vpn/vpn/updown.sh
#!/bin/sh
# This script adds/removes the VPN routes and calls the iptables vpn script.
# This script is called by openvpn's up and down hooks.

# Set -e shell option to exit if any error is encountered
set -e

### Functions ###

# Helper function to log with prefix
#
```

doesn't look changed from default to me.

Thanks

Using a UDM-PRO, official, not beta/RC/EA firmware.
Unifi network: 7.2.95 and tried 7.2.x all variations from Jan 2022 or so. No luck with the split-vpn :(

**Comment by peacey** [comment]
Hi @SystemJargon,

How did you modify your vpn.conf? Did you modify it directly with vim in terminal or you modified on your computer's text editor and transferred the file over? I ask because this line here shows the file oculdn't be read properly (possibly due to encoding/line ending problems in the file).

> : not foundvpn/vpn/updown.sh: ./vpn.conf: line 4:

**Comment by SystemJargon** [comment]
Thanks Peacey for replying.

Experimenting and seems to work now. Yes evil windows text editors!

Looks like nano on my linux box to the UDM (using nano to edit) *WORKS*

VS notepad++ on my PC and the same filename and file contents to be DOS format despite looking the same. (Windows ffs)

Thanks again! Love you work!
