### ISSUE TITLE
Multi-wan policy based routing

### ISSUE THREAD

**Issue by sjtuross** [peacey/split-vpn#144]
Is there a way to leverage split-vpn for multi-wan policy based routing? For example, I have wan2 which is not the default route, but I'd like some clients to go out through wan2. Even better if wan2 is down, failover to wan.

**Comment by peacey** [comment]
Hi @sjtuross,

It is possible to use this script to route specific clients through a specific WAN. But it's not possible for it to failover if that WAN goes down. It would be a static thing. 

However, before you use this script, you can actually do this directly in Unifi Network using Traffic Routes (a new feature). If you're on a relatively recent version with the new UI, just go to Unifi Network -> Settings -> Traffic Management -> create new route. Choose what to route (all or specific traffic), the tagret to apply this to (the devices that you want to route their traffic), and choose the WAN interface the traffic should leave. 

I don't think the Unifi Traffic Routes supports failover either, though I haven't used them personally. 

I would maybe try the Unifi option first and see if it works for you.

**Comment by sjtuross** [comment]
Hey @peacey, thanks a ton for letting me know this new feature. It works perfectly for my scenario. I really appreciate your education.

**Comment by peacey** [comment]
No problem! Closing this now as it's solved.
