### ISSUE TITLE
UDM Boot Script Issue

### ISSUE THREAD

**Issue by peacey** [peacey/split-vpn#145]
Mr @peacey, what a great work youve done! A UDM newbee as me I thank you and salute you for your good work!

I just have one issue, the boot utility doesnt kick in script 99-run-vpn.sh
`/mnt/data/on_boot.d/99-run-vpn.sh`

If I open the script 99-run-vpn.sh and execute line by line via ssh, Wireguard is connecting flawless.
Can you please help me out with any debug clue?

**Below are commands after a reboot**
I try 'wg' to see if there is any handshake, nope
Try to run run-vpn.sh, nope.
Manually execute script 99-run-vpn.sh line by line, Jackpot!

```
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2022
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  http://www.ui.com

      Welcome to UniFi Dream Machine!
->
# wg
# /etc/split-vpn/run-vpn.sh
-sh: /etc/split-vpn/run-vpn.sh: not found
# rm -f /etc/split-vpn
# ln -sf /mnt/data/split-vpn /etc/split-vpn
# /etc/split-vpn/run-vpn.sh
loading wireguard...
Warning: `/mnt/data/split-vpn/wireguard/mullvad/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
->
[Tue Dec  6 8:44:43 CET 2022] split-vpn: wg0 up: Loading configuration from /etc/split-vpn/wireguard/mullvad/vpn.conf.
[Tue Dec  6 8:44:43 CET 2022] split-vpn: Using IPv4 gateway from table 201: via xx.xxx.xxx.xx dev eth8.


```
Can you please push me in right direction?
Thank you!

_Originally posted by @signed2 in https://github.com/peacey/split-vpn/issues/91#issuecomment-1340029182_

**Comment by peacey** [comment]
Hi @signed2,

It sounds like the boot script isn't even running. Did you confirm that you installed the UDM Boot Utility and that it's working? There might be an issue with the boot utility. Maybe try reinstalling it?

I would do this to debug. First confirm UDM Boot Utility is running and enabled with the following commands:

```sh
unifi-os shell
systemctl enable udm-boot
systemctl start udm-boot
systemctl status udm-boot
```
The last command (status) should say 



Create a new script in in `/mnt/data/on_boot.d/test.sh` with the following contents:

     echo "test" > /mnt/data/test_output

Then either restart the system or run `unifi-os restart` (which restarts the Unifi subsystem which should execute the on boot script).

**Comment by signed2** [comment]
Fabelous Peacy - works flawless with your commands! 

Youre such a star - thank you!!
