### ISSUE TITLE
Dual VPN - How to script for multiple VPN Configurations from OPENVPN Cloud

### ISSUE THREAD

**Issue by michaelbtran** [peacey/split-vpn#146]
Hi All,

I am having issues to script two VPN tunnels to start automatically when rebooting. I have tried to run a cron job or combine the two files but can't seem to get it working. I have the two files:

filename1.ovpn
filename2.ovpn

The only different is the connector name on the two files. The certificate and the subnet routing is exactly the same. 
setenv USERNAME "test/connector/xxxxxxxxxxx"

Both use the same certificate with no password. I would like to run these at the same time when the UDM starts. 
Is there anyway we can script this in? 

I am also finding that my second VPN just shuts down for no reason and doesnt restart. I am using the file script to manually force it but can't seem to get this automated:

cd /mnt/data/split-vpn/openvpn/pia

nohup openvpn --config filename2.ovpn \
              --route-noexec \
              --up /mnt/data/split-vpn/vpn/updown.sh \
              --down /mnt/data/split-vpn/vpn/updown.sh \
              --script-security 2 \
              --ping-restart 15 \
              --mute-replay-warnings &> openvpn.log &

Any help on this would be greatly appreciated. 
Currently running on Unifi OS UDM Pro 1.12.33

**Comment by peacey** [comment]
Hi @michaelbtran,

You'll need to separate out your two configs in different folders. Put one configuration in `/mnt/data/split-vpn/openvpn/pia1` and one in `/mnt/data/split-vpn/openvpn/pia2` for example. Then under each folder you'll have a separate ovpn config, a vpn.conf, and a run-vpn.sh. 

Finally, you call each `/mnt/data/split-vpn/openvpn/pia1/run-vpn.sh` and `/mnt/data/split-vpn/openvpn/pia2/run-vpn.sh` from the master run script in /mnt/data/split-vpn/run-vpn.sh.

**Comment by michaelbtran** [comment]
Thanks peachy. We re-read your instructions as I missed the section of the split-vpn on mutiple and realized we had to make the DEV and MARK all unique. We just working now on the master boot script to auto boot when you reboot. Thanks again as this guide was fantastic and your service is much better than Ubiquiti themselves.

**Comment by peacey** [comment]
Glad you figured it out! If you have any more questions, feel free to ask, else you can close this issue. Thanks!

**Comment by michaelbtran** [comment]
Issue was the separate folders that needed to be created and for the file to be named as vpn.conf (as well as custom settings inside the vpn.conf that had to be unique).
