### ISSUE TITLE
Multiple Wireguard connections

### ISSUE THREAD

**Issue by signed2** [peacey/split-vpn#147]
Mr @peacey ,

I have been playing around with the Vlan config to establish a good network setup, but have hit an obsticle.
I'd like to come up with multiple wireguard connections, where I push a certain Vlan to a certan wireguard connection.

I have managed to get 2 handshakes, wg0 and wg1.
I have duplicated the vpn.conf to a second "vpn1.conf" with changes as below:
FORCED_SOURCE_INTERFACE="br10"
_ROUTE_TABLE=102
MARK=0x170
PREFIX="VPN1__"
PREF=98
DEV=wg1

I have added a second "run-vpn1.sh" to the /etc/split-vpn/wireguard/mullvad 
```
cd /etc/split-vpn/wireguard/mullvad
. ./vpn1.conf
# /etc/split-vpn/vpn/updown.sh ${DEV} pre-up >pre-up.log 2>&1
wg-quick up ./${DEV}.conf >wireguard1.log 2>&1
cat wireguard1.log
```

Also updated `/etc/split-vpn/run-vpn.sh `
```
#!/bin/sh
/etc/split-vpn/wireguard/mullvad/run-vpn.sh
/etc/split-vpn/wireguard/mullvad/run-vpn1.sh
```

I get a second log file, "wireguard1.log" as follow:

_Warning: `/mnt/data/split-vpn/wireguard/mullvad/wg1.conf' is world accessible
[#] ip link add wg1 type wireguard
[#] wg setconf wg1 /dev/fd/63
[#] ip -4 address add hidden dev wg1
[#] ip -6 address add hidden dev wg1
[#] ip link set mtu 1420 up dev wg1
[#] ip -6 route add ::/1 dev wg1 table 102
[#] ip -6 route add 8000::/1 dev wg1 table 102
[#] ip -4 route add 128.0.0.0/1 dev wg1 table 102
[#] ip -4 route add 0.0.0.0/1 dev wg1 table 102
[#] sh /etc/split-vpn/vpn/updown.sh wg1 up
[Wed Dec 14 21:17:34 CET 2022] split-vpn: wg1 up: Loading configuration from /etc/split-vpn/wireguard/mullvad/vpn.conf.
[Wed Dec 14 21:17:34 CET 2022] split-vpn: Using IPv4 gateway from table 201: via hidden dev eth8._

But I don't manage to get the second wg1 connection to hook with vlan10 aka "br10" in vpn1.conf.
I have tried FORCED_SOURCE_IPV4="192.168.10.0/24" instead of "br10" - but no success.
Is the updown.sh my problem? Can you please help me out and push me in right direction?

Thank you!!!

**Comment by michaelbtran** [comment]
I am having the same issue and thanks for this guide. Did you manage to get anywhere on this? We tried using the destination as well and it doesnt seem to work or force the connection.

**Comment by peacey** [comment]
Hi @signed2,

The issue is you can only use one vpn.conf per folder. The script always looks for vpn.conf,  not vpn1.conf, vpn2.conf, etc. 

So make a separate directory for server1 and server2 or whatever you want to call them. So the directory structure should be like this for 2 servers under mullvad: 

- /etc/split-vpn/wireguard/mullvad
    - server1/
        - vpn.conf, wg0.conf, run-vpn.sh
    - server2/
        - vpn.conf, wg1.conf, run-vpn.sh

Your settings are correct otherwise. 

@michaelbtran, what issue are you having?

**Comment by michaelbtran** [comment]
> Hi @signed2,
> 
> The issue is you can only use one vpn.conf per folder. The script always looks for vpn.conf, not vpn1.conf, vpn2.conf, etc.
> 
> So make a separate directory for server1 and server2 or whatever you want to call them. So the directory structure should be like this for 2 servers under mullvad:
> 
> * /etc/split-vpn/wireguard/mullvad
>   
>   * server1/
>     
>     * vpn.conf, wg0.conf, run-vpn.sh
>   * server2/
>     
>     * vpn.conf, wg1.conf, run-vpn.sh
> 
> Your settings are correct otherwise.
> 
> @michaelbtran, let's talk in your issue (#146).

We had same issue as we renamed it to vpn2. we renamed it back to vpn.conf and had it in separate folders with unique settings and this worked. Appreciate the help. Where we had the issue is we running the same .vpn file which was still referencing our PIA original folder.

**Comment by signed2** [comment]
@peacey again - spot on! 👍

just to mention for newbees as myself, dont forget to give the script executable permissions.
In my case `chmod +x /etc/split-vpn/wireguard/mullvad/server1/run-vpn.sh`

Please let me know if there is any way I can donate - as thanks for your superb help!

**Comment by michaelbtran** [comment]
Agreed with signed2. Thank you for the help and let me know if there is a donation link as well to help your cause for all the development you have done
