### ISSUE TITLE
Delayed network setup on boot

### ISSUE THREAD

**Issue by sjrobins** [peacey/split-vpn#149]
My UDM comes up faster than my provider's box on a power loss. As a result, the site to site tunnel doesn't get setup right away, and the on boot script fails.

I tried running it after the network interface came up:

```
# /mnt/data/on_boot.d/99-run-vpn.sh
[Sun Dec 18 12:57:50 XXX 2022] split-vpn: tun1 up: Loading configuration from
/etc/split-vpn/nexthop/target/vpn.conf.
Cannot find device "tun1"
```

The site to site isn't active yet:

```
# ip route
10.4.4.0/24 dev br0 proto kernel scope link src 10.4.4.1
10.5.5.0/24 dev br4 proto kernel scope link src 10.5.5.1
xxx.xx.xx.xx dev ppp0 proto kernel scope link src xxx.xxx.xxx.xxx
```

After some time:

```
# ip route
10.0.1.0/24 via 10.0.1.5 dev tun1
10.0.1.5 dev tun1 proto kernel scope link src 10.4.4.5
10.2.2.0/24 via 10.0.1.5 dev tun1
10.4.4.0/24 dev br0 proto kernel scope link src 10.4.4.1
10.5.5.0/24 dev br4 proto kernel scope link src 10.5.5.1
xxx.xx.xx.xx dev ppp0 proto kernel scope link src xxx.xxx.xxx.xxx
```

Then it loads happily.

Should I setup an arbitrary delay? Is there a recommendation on how to wait until the tunnel becomes available?

**Comment by peacey** [comment]
Hi @sjrobins,

Seems like you found the issue. A delay would be fine if it only happens at startup. 

You can add some code to your run-vpn.sh (in `/etc/split-vpn/nexthop/target/run-vpn.sh`) to wait for tun1 to come up before continuing. Like: 
  
  ```sh
  while ! ip link show dev ${DEV} 1>/dev/null 2>&1; do
	  sleep 5
  done
  ```
  
Make sure to add this code after the `. ./vpn.conf` line (so ${DEV} is defined), but before the updown.sh script is called. This will keep checking if tun1 is up every 5 seconds before continuing with the script. You can modify `sleep 5` to check faster (at the cost of CPU usage of course).
