### ISSUE TITLE
Bad argument `DOMAIN' add-vpn-iptables-rules.sh

### ISSUE THREAD

**Issue by gstever** [peacey/split-vpn#15]
Hi,

having dhcp-options 

    dhcp-option DOMAIN example.domain.ex
    dhcp-option DNS 1.2.3.4

throws an error:
Bad argument `DOMAIN'

Looks like sed always return a value - changing  add-vpn-iptables-rules.sh line 67 to 
    `dns=$(echo "${foreign_option_i}" | sed -En s/".*dhcp-option DNS ([0-9\.]+).*"/"\1"/p)`
works for me.

**Comment by peacey** [comment]
Thank you very much for this fix. The sed was definitely not accounting for other cases. I usually grep for the pattern first, but your fix is more elegant than running grep then sed, so thank you!
