### ISSUE TITLE
[question] Route traffic from a specific host

### ISSUE THREAD

**Issue by alaaalii** [peacey/split-vpn#151]
I thought I'd best ask here.

I'm thinking about purchasing the UXG-Pro.

I currently have a pfSense router, and I route all traffic from a specific source host to an openvpn connection - it's done using a firewall rule to force the gateway when traffic originates from that host - otherwise everything goes out to regular internet.

I want to do the same thing with the UXG-Pro. Is this the "policy based routing" that isn't supported natively, where I would need this `split-vpn` package to accomplish this (using `FORCED_SOURCE_IPV4`)? Couldn't I put this particular host on a separate network VLAN then route that VLAN to the openvpn connection natively in Unifi, or is this still considered the same unsupported "routing" method? Thanks!

**Comment by alaaalii** [comment]
I bought the UXG-Pro and indeed it didn't natively support doing this, even using the new Traffic Management feature, it can only route to WAN ports, but not specifically to the VPN connection.

**Comment by peacey** [comment]
Hi @alaaalii,

Sorry for the late reply, was on vacation. Yes, this is exactly what split-vpn is for. You can use it to route traffic to a VPN on the UXG-Pro. Have you tried to use it?

**Comment by alaaalii** [comment]
No worries! I'll be using it soon. Will open issues if I run into anything.

**Comment by alaaalii** [comment]
Just FYI @peacey, I think some of this functionality might be supported in the upcoming Unifi OS3, see [release notes for UDM](https://community.ui.com/releases/UniFi-OS-Dream-Machine-SE-3-0-13/cf25f68e-6906-4125-9d77-9fce05d6658a) about openvpn and routing.

**Comment by peacey** [comment]
Hey @alaaalii, 

Yup I know they have added routing for OpenVPN. However, they still don't have routing for client-mode wireguard, strongswan, openconnect, or an external VPN on the network. And as you said, this script has way more options for different scenarios that Ubiquiti doesn't cover. 

So definitely this script is still very useful. Though, I really hope Ubiquiti adds as many features as possible in the future. It is much more streamlined to have this all integrated!
