### ISSUE TITLE
UDM to USG3 Site to Site

### ISSUE THREAD

**Issue by karlnewick** [peacey/split-vpn#153]
I have a UDM SE with UniFi 3.0.13 and a USG 3 on latest version.

Setup as follows
UDM
WAN 10.10.1.2
172.20.1.1 - Default
172.20.44.1 - Clients

USG
WAN 10.10.1.3
192.168.1.1 - Default

S2S is up and running, remote networks set to 
UDM Remote network is 
192.168.1.1
USG Remote network is
172.20.1.0/24
172.20.44.0/24
a client connected on the 172.20.44.0/24 can ping across the VPN and get a response from 192.168.1.1

I installed the split-vpn using the site-to-site config example.

when I do a tracert from 172.20.44.X to 8.8.8.8 I get

Tracing route to 8.8.8.8 over a maximum of 30 hops

  1    <1 ms    <1 ms    <1 ms  172.20.44.1
  2     1 ms     1 ms     1 ms  10.10.1.3
  3     *     * 

So, the routes are working and its sending traffic over the VPN as expected but its almost like the route back is not working. 
From the USG 3 I do an ip route
172.20.44.0/24 dev vti64 proto zebra scope link
 from the USG3 I can ping the device on the 172.20.44.0 network. So I know traffic is passing and the routes are good.

Any ideas?
[vpn.conf.txt](https://github.com/peacey/split-vpn/files/10363170/vpn.conf.txt)

**Comment by karlnewick** [comment]
I just read the thread from October and applied the following to the USG
configure
set service nat rule 5010 description 'masquerade for WAN'
set service nat rule 5010 outbound-interface eth0
set service nat rule 5010 type masquerade
set service nat rule 5010 protocol all
commit;save;exit

That gave me a ping response! But DNS is not working and I tried to point it to 8.8.8.8

Partly there!

**Comment by peacey** [comment]
Hi @karlnewick,

Glad you figured out what commands to run on the USG for masquerading. As for DNS not working, check these things: 

1. Make sure you're not using any content filtering on the UDM network. Content filtering will re-route the DNS to Ubiquiti and won't work. 
2. Try to do a tcpdump on the USG when you do a DNS lookup on the UDM network so you can see what's happening to the DNS packets. Are you able to do this or do you need guidance?

**Comment by karlnewick** [comment]
Hi, I should be good, but I got another issue atm. I had to uninstall the script for the moment while i resolved this. I keep you posted.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by karlnewick** [comment]
Just wanted to update you, I reinstalled the script after I resolved my other issue onto a UDM-SE and its working perfectly.

The USG was the issue and I followed the instructions from the other case. The only difference was I had to update my WAN to be pppoe0 not eth0.

Thanks
________________________________

**Comment by peacey** [comment]
I'm glad to hear everything worked out!
