### ISSUE TITLE
Split-VPN (OpenVPN) and simultaneous L2TP Server - WAN IP issue

### ISSUE THREAD

**Issue by mminehanNZ** [peacey/split-vpn#154]
I'm no network expert and I've searched for an answer so please excuse me if this has been addressed elsewhere.
I run a simple L2TP VPN server on my UDMPro so that I can VPN into our home network.  This has been working as expected.
Since installing the split-vpn OpenVPN as per the readme my WAN IP displayed on the controller seems to have changed to the OpenVPN IP (100.122.6.xxx), not the static IP my ISP has assigned me (223.165.xxx.xxx).  When I check the external IP from my default network (WhatsmyIP) i see the correct ISP assigned IP.  But the controlled displays the OpenVPN IP in the 'Internet/Default WAN1' page.
As a consequence, when I try and configure the L2TP VPN server gateway IP the drop down only displays the OpenVPN IP (100.122.6.xxx) and I can no longer connect to my network using L2TP from my devices when away from home.
Is there a simple setting or configuration I need to change?

**Comment by peacey** [comment]
Hi @mminehanNZ,

That's interesting. I've never had this happen to me and I'm not able to recreate the issue.

Have you tried using a different DEV name in your VPN.conf? Like openvpn0 for example. 

Does this happen all the time or just sometimes? If you restart the system does it help temporarily? Or what happens if you disable the split-vpn configuration?

**Comment by mminehanNZ** [comment]
Thanks for looking at this.
I have done some more digging around and it turns out that the console displayed WAN IP is NOT the same as the OpenVPN IP. I'm not sure if this was the IP that was issued by the OpenVPN the very first time I set it up.  But changing OpenVPN config files does not change the console displayed WAN IP.
For the life of me I can't seem to get it to revert back to the static IP issued by my ISP.  It always sets to 100.112.6.xxx.
I will ring my ISP and ask them what the exact static IP settings would be, rather than DHCP.....which issues the same actual WAN IP.

**Comment by peacey** [comment]
Have you checked if that IP shows up anywhere under the command `ip addr`?

If you're not running split-vpn then uninstalling it won't do anything. Just make sure the tunnel device of the VPN is not shown when you run the command `ip link` or `ip addr` on the UDM if you're worried split-vpn is still running.

**Comment by mminehanNZ** [comment]
Thank you for your assistance. It's appreciated.

So I ran `ip addr` and it seems to be associated with eth8.

_eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether f4:92:bf:77:f2:03 brd ff:ff:ff:ff:ff:ff
    inet 100.112.6.253/30 scope global dynamic eth8
       valid_lft 77603sec preferred_lft 77603sec
    inet6 fe80::f692:bfff:fe77:f203/64 scope link
       valid_lft forever preferred_lft forever_

This is WAN1.

**Comment by peacey** [comment]
So eth8 is the Ethernet port and it is WAN1 by default. So Did you not expect eth8/WAN1 to have this IP?

**Comment by mminehanNZ** [comment]
To be honest I am not sure what is going on.  I last VPNd into my network a few weeks ago.  And tried again after installing split-vpn only to discover it is not working.  It may not be related to split-vpn.  And I can't honestly recall what the WAN IP was....I suspect it might be a double NAT issue from the ISP.
I'll check with my ISP first before taking up more of your time.

**Comment by mminehanNZ** [comment]
Can I just confirm that if I bring the split-vpn down (kill), or prevent the auto startup and reboot, that things should be as they were before installing the slpit-vpn (as per the readme instructions)? It's not possible for split-vpn to have changed any of the L2TP server configuration?
I just want to make sure before I ask my ISP to help.

**Comment by peacey** [comment]
Yes it will be like if split-vpn never existed. 

And no, it's not possible for split-vpn to change the L2TP config. 

If you only have one Internet link (Ethernet), and you're seeing a different IP on the link than when you go to a website (without any VPN), then it does seem like you're double NATted. Was this not always like this? 

Does any port forwarding work for you?

**Comment by mminehanNZ** [comment]
I am not sure what the problem with the UDM L2TP setup is but I gave up and ended up installing Wireguard on a spare Pi I had sitting round. It actually works better than L2TP.  So please forgive me for wasting your time as it is not an issue with split-vpn.  Thank you for trying to help out though. Please close (and/or delete) this issue.  :)

**Comment by peacey** [comment]
Happy to see you ended up resolving it! I'll close this for now. Have a great day!
