### ISSUE TITLE
PureVPN new certificate for Dedicated IPs gives "no Trusted RSA Key..."

### ISSUE THREAD

**Issue by x0zerocool0x** [peacey/split-vpn#157]
I received a new dedicated IP from PureVPN. They changed their IPs and certificates for those. I updated the certificate but I am still getting the following error:
Jan 29 22:27:21 12[ENC] <purevpn|4> received fragment #2 of 4, reassembled fragmented IKE message (4244 bytes)
Jan 29 22:27:21 12[ENC] <purevpn|4> parsed IKE_AUTH response 1 [ IDr CERT CERT AUTH EAP/REQ/ID N(AUTH_FOLLOWS) ]
Jan 29 22:27:21 12[IKE] <purevpn|4> received end entity cert "CN=*.pointtoserver.com"
Jan 29 22:27:21 12[IKE] <purevpn|4> received issuer cert "C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limi                                                         ted, CN=Sectigo RSA Domain Validation Secure Server CA"
Jan 29 22:27:21 12[IKE] <purevpn|4> no trusted RSA public key found for '45.83.149.100'

Please help!

**Comment by peacey** [comment]
Hey @x0zerocool0x,

Can you try to add `id = pointtoserver.com` to the remote-0 section in your `purevpn.conf` file?

**Comment by x0zerocool0x** [comment]
Hi @peacey,
I did find that in another post and tried it. It did not work. Any suggestions or files you would like to see? Im in a real bind, my wife cant work while this is down.

**Comment by x0zerocool0x** [comment]
Heres their new certs:
[Ded UDP.txt](https://github.com/peacey/split-vpn/files/10536198/Ded.UDP.txt)
[Ded TCP.txt](https://github.com/peacey/split-vpn/files/10536199/Ded.TCP.txt)

**Comment by peacey** [comment]
@x0zerocool0x, the certificates you linked to seem to be for OpenVPN and are also an OpenVPN configuration. Are they the same ones for IPSeC?

Can you show me your purevpn.conf and your run-vpn.sh?

I will try getting your server working on my end.

**Comment by x0zerocool0x** [comment]
Thank you! 
For IPSeC they dont give me a config file, just the URL which is: us2-ipsec.ptoserver.com

purevpn.conf:
`connections {
        purevpn {
                remote_addrs = us-dux-5.pointtoserver.com
                rekey_time = 4h
                reauth_time = 0s
                dpd_delay = 30s
                local_addrs = %any
                vips = 0.0.0.0
                send_cert = never
                send_certreq = no
                proposals = 3des-sha1-modp1024
                children {
                        purevpn {
                                start_action = start
                                dpd_action = start
                                close_action = start
                                esp_proposals = 3des-sha1
                                local_ts = dynamic
                                remote_ts = 0.0.0.0/0
                                mark_in = %unique
                                mark_out = %unique
                                updown = /etc/split-vpn/vpn/strongswan-updown.sh /etc/split-vpn/strongswan/purevpn/vpn.conf
                        }
                }
                local-0 {
                        auth = eap-mschapv2
                        id = @purevpn##########
                        eap_id = purevpn##########
                }
                remote-0 {
                        id = pointtoserver.com
                        auth = pubkey
                        cacerts = /etc/split-vpn/strongswan/purevpn/USERTrustRSACertificationAuthority.crt
                }
        }
}
pools {
}
authorities {
}
secrets {
        eap-purevpn########## {
                secret = "##########"
                id-0=purevpn##########
        }
}
`
run-vpn.sh: 
`#!/bin/sh
#/etc/split-vpn/strongswan/purevpn/run-vpn.sh
cd "/etc/split-vpn/strongswan/purevpn"
. ./vpn.conf

podman rm -f strongswan-${DEV} &> /dev/null
#/etc/split-vpn/vpn/updown.sh ${DEV} pre-up
podman run -d --name strongswan-${DEV} --network host --privileged \
    -v "./purevpn.conf:/etc/swanctl/conf.d/purevpn.conf" \
    -v "${PWD}:${PWD}" \
    -v "/etc/split-vpn/vpn:/etc/split-vpn/vpn" \
    -e TZ="$(cat /etc/timezone)" \
    -v "/etc/timezone:/etc/timezone" \
    peacey/udm-strongswan

# Make sure VPN disconnects before reboot
initfile="/etc/init.d/S99999stopvpn"
if [ ! -f "$initfile" ]; then
    echo "#!/bin/sh" > "$initfile"
    chmod +x "$initfile"
fi
grep -q "strongswan-${DEV};" "$initfile"
if [ $? -ne 0 ]; then
    echo 'if [ "$1" = "stop" ]; then podman rm -f strongswan-'"${DEV}"'; fi' >> "$initfile"
fi
`

**Comment by x0zerocool0x** [comment]
Oh my word, I dont know what I did to break it but it is working now! Thank you so much! Please send me your venmo or a way to pay you.
