### ISSUE TITLE
Wireguard config getting deleted during setup

### ISSUE THREAD

**Issue by jacobgibbs** [peacey/split-vpn#159]
@peacey I have NordVPN working perfectly through the openvpn implementation (thank you!). I was looking to test out the Wireguard option to see if I could see any speed gains.

I have a working Wireguard config (tested via the Wireguard app) for NordVPN by using https://github.com/sfiorini/NordVPN-Wireguard.

I have gone through the setup (UnifiOS 1.x) instructions - `modprobe wireguard` produces no errors, `wg-quick` returns the help info. I've also ran the setup script from wireguard-kmod.

When I go to run the config with wg-quick, I get the following output and the VPN doesn't come up:
```
# wg-quick up ./wg0.conf
Warning: `/mnt/data/split-vpn/wireguard/nordvpn/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1412 up dev wg0
[#] ip -6 route add ::/1 dev wg0 table 101
RTNETLINK answers: File exists
[#] ip link delete dev wg0
```

wg0.conf:
```
[Interface]
PrivateKey = [REDACTED]
Address = 10.5.0.2/32
PostUp = sh /etc/split-vpn/vpn/updown.sh %i up
PreDown = sh /etc/split-vpn/vpn/updown.sh %i down
Table = 101

[Peer]
PublicKey = [REDACTED]
AllowedIPs = 0.0.0.0/1,128.0.0.0/1,::/1,8000::/1
Endpoint = uk1791.nordvpn.com:51820
```

The only difference to this config compared to the one tested within the Wireguard app is the `[Peer]` section also had this:
```
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
```

My only changes to the vpn.conf:
```
FORCED_SOURCE_MAC="[REDACTED]"
DNS_IPV4_IP="103.86.96.100, 103.86.99.100" #Provided by NordVPN conf
VPN_PROVIDER="external"
```

**Comment by peacey** [comment]
Hi @jacobgibbs,

It looks like something is wrong with the module when adding an IPv6 route. Can I see your setup_wireguard.sh? Did you set LOAD_BUILTIN=1 or 0?

Unrelated but DNS_IPV4_IP in vpn.conf should only contain one IP so pick one. You cannot include two.

**Comment by jacobgibbs** [comment]
Thanks for the speedy response @peacey 

I did originally only have one IP in DNS_IPV4_IP but thought I'd also try two to see if it made a difference. I'll change it back to one now!

LOAD_BUILTIN=1 - should I try setting to 0 and re-running?

Here is my setup_wireguard.sh:
```
#!/bin/sh
# Tusc00 on reddit, @tusc69 on ubnt forums
#
# v4-7-21	Initial release. Updated script to auto load kernel module based on installed firmware version.
# v4-8-21	Build now includes iptables_raw module. This is required for wg-quick when changing routes. Switched to MUSL static library
#		for building wireguard tools and bash given the number of CVEs with glib 2.26. Preliminary support for the UXG.
# v4-10-21	Updated release to include utils such as htop, iftop and qrencode. The last one allows easy import of wireguard configs
#		into your IOS/Android WireGuard client using QR codes.
# v6-23-21	Added support for resolvconf

# Set this to 1 to try to load the built-in wireguard module first. External module will still be loaded if built-in one doesn't exist.
# Set to 0 to only load external module.
LOAD_BUILTIN=1

DATA_DIR="."
if [ -d "/mnt/data" ]; then
	DATA_DIR="/mnt/data"
elif [ -d "/data" ]; then
	DATA_DIR="/data"
fi
WIREGUARD="${DATA_DIR}/wireguard"

ln -sf $WIREGUARD/usr/bin/wg-quick /usr/bin
ln -sf $WIREGUARD/usr/bin/wg /usr/bin
ln -s $WIREGUARD/usr/bin/bash /bin
ln -sf $WIREGUARD/usr/bin/qrencode /usr/bin
ln -s $WIREGUARD/usr/bin/htop /usr/bin
ln -s $WIREGUARD/usr/sbin/iftop /usr/sbin
ln -s $WIREGUARD/sbin/resolvconf /sbin

# create symlink to wireguard config folder
if [ ! -d "/etc/wireguard" ]
then
   ln -sf $WIREGUARD/etc/wireguard /etc/wireguard
fi

# create symlink to resolvconf config file
if [ ! -f "/etc/resolvconf.conf" ]
then
   ln -s $WIREGUARD/etc/resolvconf.conf /etc/
fi

# required by wg-quick
if [ ! -d "/dev/fd" ]
then
   ln -s /proc/self/fd /dev/fd
fi

#load dependent modules
modprobe udp_tunnel
modprobe ip6_udp_tunnel

lsmod|egrep ^wireguard > /dev/null 2>&1
if [ $? -eq 1 ]
then
   ver=`uname -r`
   echo "loading wireguard..."
   if [ "$LOAD_BUILTIN" = "1" -a -e /lib/modules/$ver/extra/wireguard.ko ]; then
      modprobe wireguard
   elif [ -e $WIREGUARD/modules/wireguard-$ver.ko ]; then
     insmod $WIREGUARD/modules/wireguard-$ver.ko
#    iptable_raw required for wg-quick's use of iptables-restore
     insmod $WIREGUARD/modules/iptable_raw-$ver.ko
     insmod $WIREGUARD/modules/ip6table_raw-$ver.ko
   else
     echo "Unsupported Kernel version $ver"
   fi
fi
#
```

**Comment by peacey** [comment]
=1 should be fine honestly, I'm surprised it's doing that. Which 1.x release are you running? 

Well I don't think Nord even uses IPv6, so can you just remove `::/1,8000::/1` from AllowedIPs? So just set it to:

```ini
AllowedIPs = 0.0.0.0/1,128.0.0.0/1
```

Let's see if that works first before trying the external module (which on 1.x messes up with Teleport).

**Comment by jacobgibbs** [comment]
I'm running UniFi OS UDM 1.12.33, which I think is the most recent.

Updating the AllowedIPs and running again gives this output:
```
# wg-quick up ./wg0.conf
Warning: `/mnt/data/split-vpn/wireguard/nordvpn/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1412 up dev wg0
[#] ip -4 route add 128.0.0.0/1 dev wg0 table 101
RTNETLINK answers: File exists
[#] ip link delete dev wg0
```

**Comment by peacey** [comment]
Can I see the output of this command?

`ip route show table 101`

**Comment by peacey** [comment]
Oh, you still have the previous OpenVPN tunnel still running and it's using the same table. Did you mean to keep it running in parallel or do you want to stop it first with `killall -TERM openvpn`? Then check the route table is empty, and wg should work. 

You can also run them in parallel if you need to, but you would need to use separate tables in the config.

**Comment by jacobgibbs** [comment]
Ah, my bad! I didn't even notice the table in the OpenVPN config...
I won't need both in the long run, so I'm happy to stop OpenVPN - which, of course, has meant that the wg-quick command has worked perfectly!

That's for the quick replies and spotting my mistake!
