### ISSUE TITLE
Force Domains doesn't work with AdGuard Home

### ISSUE THREAD

**Issue by putiatin** [peacey/split-vpn#161]
HI!

I installed AdGuard Home and then tried to install split-vpn. If I force full network with br0 VPN works correct, but when I try to force only domain names nothing happens. wg0 is up, domains are set in VPN_domains.conf, add-dnsmasq-ipset.sh is done without errors but I see WAN ip when I visit forced domaines. Also when I make ping domains through wg0 with ping -I wg0 whatismyip.com all is ok.

Configuration files are in attach. Changed extensions to upload them.
[VPN_domains.conf.txt](https://github.com/peacey/split-vpn/files/10679545/VPN_domains.conf.txt)
[vpn.conf.txt](https://github.com/peacey/split-vpn/files/10679546/vpn.conf.txt)

**Comment by peacey** [comment]
Hi @putiatin,

Forced domains is currently limited to pihole or the built-in dnsmasq. It won't work currently with AdGuard Home. However, there might be a workaround if you're willing to try a test version of split-vpn. I recently had someone here wanting to use an external dns server with forced domains and he came up with an idea to use dnsmasq to forward requests to the external server (#155). I believe this can also work for you. 

Please try the following instructions if you're willing to test this:

1. Update the ipsets scripts to the test branch like so. Skip the installation step from the guide.

    ```sh
    cd /etc/split-vpn
    curl -Lo split-vpn.zip https://github.com/peacey/split-vpn/archive/dnsmasq_forward.zip
    unzip -qo split-vpn.zip
    cp -rf split-vpn-dnsmasq_forward/ipsets ./ && rm -rf split-vpn-dnsmasq_forward split-vpn.zip
    chmod +x ipsets/*.sh
    ```

2. Make sure to use the DNSMASQ options in `VPN_domains.conf`.
3. In your `VPN_domains.conf`, set FORWARD_SERVER to your ad guard IP (e.g.: `FORWARD_SERVER=10.0.6.3`). The `FORWARD_SERVER` option was newly added in the sample `VPN_domains.conf.sample`, so you might have to add it to your `VPN_domains.conf` if you already copied the sample previously. 
4. Follow the rest of the ipsets guide as usual to configure split-vpn with the ipsets.
5. Now you have to make your forced devices use the UDM's dnsmasq and not your adguard (dnsmasq will forward all requests to adguard). You can either do any of the following (pick one, don't do all of them):
    a. Change your LAN's DHCP settings to hand out the UDM's IP as the DNS and reconnect your clients so they get the new DNS.
    b. Manually set the DNS on your clients directly to the UDM's IP.
    c. Set `DNS_IPV4_IP/DNS_IPV4_INTERFACE` to your UDM's IP and brX interface in `vpn.conf` to force VPN-forced clients to use dnsmasq if you prefer to only force these forced clients to use dnsmasq. Though for testing please try (a) or (b) first before trying this one.

**Comment by putiatin** [comment]
Thx a lot!

> a. Change your LAN's DHCP settings to hand out the UDM's IP as the DNS and reconnect your clients so they get the new DNS.

That's worked for me. 

One more question: can I use *domain.com to automatically add subdomains or it's not possible?

**Comment by peacey** [comment]
Great to hear it worked! The only downside with this is you have to rely on dnsmasq working correctly and not being misconfigured by Ubiquiti in some future update. So I would just monitor it for stability, and double check that AdGuard Home is receiving the requests from the correct hosts, etc.

For the domain matching, dnsmasq has a snippet from [their manual](https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) that best explains how they process wildcards:

> Matching of domains is normally done on complete labels, so /google.com/ matches google.com and [www.google.com](http://www.google.com/) but NOT supergoogle.com. This can be overridden with a * at the start of a pattern only: /*google.com/ will match google.com and [www.google.com](http://www.google.com/) AND supergoogle.com. The non-wildcard form has priority, so if /google.com/ and /*google.com/ are both specified then google.com and [www.google.com](http://www.google.com/) will match /google.com/ and /*google.com/ will only match supergoogle.com.

> For historical reasons, the pattern /.google.com/ is equivalent to /google.com/. If you wish to match any subdomain of google.com but NOT google.com itself, use /*.google.com/

**Comment by putiatin** [comment]
thx a lot!)
