### ISSUE TITLE
Wireguard setup with Firewall - Packets aren't stateful?

### ISSUE THREAD

**Issue by mylesagray** [peacey/split-vpn#166]
Hey there!

Amazing project, I got it set up quite quickly and it works just fine if all I want is for a VLAN/Subnet to be permanently VPN'd - I'm quite impressed with the throughput on my UDM Base over WG (500+Mbps!).

I wanted to be able to access my other subnets - IoT, services, etc from my `Secure` network (which is permanently VPN'd) and it works fine with no firewall rules - but the reason I have them split out into subnets is because they are usually completely blocked from communicating with the LAN, except for some things like DNS access.

I added your iptables chain rules from here: https://github.com/tusc/wireguard-kmod/issues/34#issuecomment-967728575

But still, the firewall rules in the UDM seem to have an unusual effect - when not using split-vpn, the behaviour is that all "corporate" networks at UniFi calls them are implicitly allowed to each other, so I created rules to block certain subnets (IoT, Services) from talking to LAN, and then selectively allow policies for some items - DNS and UPnP for things like Sonos control. But I can still initiate connections from the LAN/Secure and receive responses because the flows are stateful.

This behaviour doesn't seem to be replicated with `wg0` - there is still an implicit allow from the `Secure` network which is VPN'd, but adding my default "Disallow IoT to Secure" type rule breaks the statefulness of the flow - I'm no longer able to initiate connections from `Secure` to `IoT` like I can with say my `LAN` network which is not under VPN.

Any ideas you might have around this would be very much appreciated!

Debug info below :)

```sh
root@UDM:/data/split-vpn/wireguard/proton# iptables -t mangle -S | grep VPN
-N VPN_FORWARD
-N VPN_OUTPUT
-N VPN_POSTROUTING
-N VPN_PREROUTING
-A PREROUTING -j VPN_PREROUTING
-A FORWARD -j VPN_FORWARD
-A OUTPUT -j VPN_OUTPUT
-A POSTROUTING -j VPN_POSTROUTING
-A VPN_FORWARD -d 192.168.1.1/32 -p udp -m mark --mark 0x169 -m udp --dport 53 -j MARK --set-xmark 0x0/0xffffffff
-A VPN_FORWARD -d 192.168.1.1/32 -p tcp -m mark --mark 0x169 -m tcp --dport 53 -j MARK --set-xmark 0x0/0xffffffff
-A VPN_PREROUTING -i br69 -j MARK --set-xmark 0x169/0xffffffff
-A VPN_PREROUTING -d 10.2.0.2/32 -m mark --mark 0x169 -j MARK --set-xmark 0x0/0xffffffff
-A VPN_PREROUTING -d 172.16.150.0/24 -m mark --mark 0x169 -j MARK --set-xmark 0x0/0xffffffff
-A VPN_PREROUTING -d 192.168.1.0/24 -m mark --mark 0x169 -j MARK --set-xmark 0x0/0xffffffff
-A VPN_PREROUTING -d x.x.x.x/29 -m mark --mark 0x169 -j MARK --set-xmark 0x0/0xffffffff

root@UDM:/data/split-vpn/wireguard/proton# iptables -t nat -S | grep VPN
-N VPN_POSTROUTING
-N VPN_PREROUTING
-A PREROUTING -j VPN_PREROUTING
-A POSTROUTING -j VPN_POSTROUTING
-A VPN_POSTROUTING -o wg0 -m mark --mark 0x169 -j MASQUERADE
-A VPN_PREROUTING ! -s 192.168.1.1/32 ! -d 192.168.1.1/32 -p udp -m mark --mark 0x169 -m udp --dport 53 -j DNAT --to-destination 192.168.1.1:53
-A VPN_PREROUTING ! -s 192.168.1.1/32 ! -d 192.168.1.1/32 -p tcp -m mark --mark 0x169 -m tcp --dport 53 -j DNAT --to-destination 192.168.1.1:53

root@UDM:/data/split-vpn/wireguard/proton# iptables -t filter -S | grep VPN
-N VPN_FORWARD
-N VPN_INPUT
-N VPN_KILLSWITCH
-A INPUT -j VPN_INPUT
-A FORWARD -j VPN_KILLSWITCH
-A FORWARD -j VPN_FORWARD
-A VPN_KILLSWITCH ! -o wg0 -m mark --mark 0x169 -j REJECT --reject-with icmp-port-unreachable

root@UDM:/data/split-vpn/wireguard/proton# ip6tables -t mangle -S | grep VPN
-N VPN_FORWARD
-N VPN_OUTPUT
-N VPN_POSTROUTING
-N VPN_PREROUTING
-A PREROUTING -j VPN_PREROUTING
-A FORWARD -j VPN_FORWARD
-A OUTPUT -j VPN_OUTPUT
-A POSTROUTING -j VPN_POSTROUTING
-A VPN_PREROUTING -i br69 -j MARK --set-xmark 0x169/0xffffffff

root@UDM:/data/split-vpn/wireguard/proton# ip6tables -t nat -S | grep VPN
-N VPN_POSTROUTING
-N VPN_PREROUTING
-A PREROUTING -j VPN_PREROUTING
-A POSTROUTING -j VPN_POSTROUTING
-A VPN_POSTROUTING -o wg0 -m mark --mark 0x169 -j MASQUERADE

root@UDM:/data/split-vpn/wireguard/proton# ip6tables -t filter -S | grep VPN
-N VPN_FORWARD
-N VPN_INPUT
-N VPN_KILLSWITCH
-A INPUT -j VPN_INPUT
-A FORWARD -j VPN_KILLSWITCH
-A FORWARD -j VPN_FORWARD
-A VPN_KILLSWITCH ! -o wg0 -m mark --mark 0x169 -j REJECT --reject-with icmp6-port-unreachable

root@UDM:/data/split-vpn/wireguard/proton# ip route show table 101
0.0.0.0/1 dev wg0 scope link
blackhole default
128.0.0.0/1 dev wg0 scope link
vpn.ip.is.here dev ppp0 scope link
192.168.1.1 dev br0 scope link

root@UDM:/data/split-vpn/wireguard/proton# ip -6 route show table 101
::/1 dev wg0 metric 1024 pref medium
8000::/1 dev wg0 metric 1024 pref medium
blackhole default dev lo metric 1024 pref medium

root@UDM:/data/split-vpn/wireguard/proton# ip rule
0:	from all lookup local
99:	from all fwmark 0x169 lookup 101
32000:	from all lookup main
32500:	from x.x.x.x lookup 201
32766:	from all lookup 201
32767:	from all lookup default

root@UDM:/data/split-vpn/wireguard/proton# ip -6 rule
0:	from all lookup local
99:	from all fwmark 0x169 lookup 101
32000:	from all lookup main
32501:	from fe80::1 lookup 201
32766:	from all lookup 201

root@UDM:/data/split-vpn/wireguard/proton# ps | grep updown.sh
17314 pts/1    00:00:00 updown.sh
17315 pts/1    00:00:00 updown.sh
```

Firewall rules:

![Rule table](https://user-images.githubusercontent.com/609356/220734186-03f922f4-335a-4f1f-b89d-6e752f81cbb8.png)

Example block rule:

![Example rules](https://user-images.githubusercontent.com/609356/220734373-b5cfdbfe-20d2-4182-8478-945d24433127.png)

Attempting to overcome with this allow rule - but no joy:

![image](https://user-images.githubusercontent.com/609356/220734938-682299c8-0e8d-4233-8fa5-f3a5673814a1.png)

**Comment by peacey** [comment]
Hi @mylesagray,

I think you're missing an Allow Established/Related sessions rule (from any local network to any local network) as the first firewall rule in your LAN IN. Without it, I'm not sure how you're even getting communication back from IoT without the VPN...

I just tested it on my end with similar rules and I'm able to communicate fine while on the VPN, and packets are stateful. But if I remove the established/related rule then it doesn't work anymore, as expected.

Just add a LAN IN rule: Accept, Source network Any (or define an RFC1819 group for all local subnets), Destination Network Any (or RFC1819), Advanced (Manual) -> check Match State Established and Match State Related. Make sure to drag the rule to the top of the list so it's the first one. It should work then I believe.

**Comment by mylesagray** [comment]
Well, that rule did the trick!

Interesting though, as I've never had to had that before - because all "corp" networks were always implicitly allowed, and I can only assume that my "Allow" rules from say LAN -> IoT were using Automatic mode for the session filtering and they had those options checked by the FW or such.

In any case - thanks very much for your help and time!
