### ISSUE TITLE
Masquerade Set up

### ISSUE THREAD

**Issue by smgraver1** [peacey/split-vpn#173]

**Comment by smgraver1** [comment]
Hi,

I just upgraded from USG to UDM Pro on my host machine to use S2S vpn. I need to set these masquerade rules on my UDM Pro but I dont know how.

configure
set service nat rule 5010 description 'masquerade for WAN'
set service nat rule 5010 outbound-interface eth0
set service nat rule 5010 type masquerade
set service nat rule 5010 protocol all
commit;save;exit

Could I get some help? Thanks.

**Comment by smgraver1** [comment]
I know I need to use iptables but not sure how exactly.

**Comment by peacey** [comment]
Hi @smgraver1,

Is this related to masquerade with split-vpn, or you're just asking a general question unrelated to split-vpn?

In any case, the UDM already has this masquerade WAN rule added by default. You don't have to add it manually like the USG. You can check it's there with `iptables -t nat -S | grep MASQ`. They look like this:

```sh
-A UBIOS_POSTROUTING_USER_HOOK -o eth8 -m comment --comment 00000001095216660481 -j MASQUERADE
-A UBIOS_POSTROUTING_USER_HOOK -o eth9 -m comment --comment 00000001095216660482 -j MASQUERADE
```

**Comment by smgraver1** [comment]
I’m using a site to site vpn for split vpn to be able to set certain sites to go over the vpn. The vpn.conf and site to site link is correct as I duplicated it from my old USG set up. But now it has the issue where it won’t load the sites that are being transferred to the vpn. I figured that masquerade wasn’t set up because that’s what fixed the issue with my USG last time we set it up. If you could help me figure out why the websites aren’t loading that’d be great!

**Comment by peacey** [comment]
Are you using a route-based S2S? Just double check that route-based is checked in the S2S settings. 

Then test the following:

1. Are you able to ping an IP on the remote S2S subnet from a local UDM client (that's non-VPN forced)?
2. After you enable split-vpn, are you able to ping 1.1.1.1 from a VPN-forced client? 
3. After you enable split-vpn, are you able to ping google.com from a VPN-forced client? 

If you 2 and 3 succeed but you can't browse any websites, then it could be an MSS clamping issue. You'll need to set `MSS_CLAMPING_IPV4="1240" in your vpn.conf and then see if browsing websites work (we can optimize the 1240 to a higher number once it works).

**Comment by smgraver1** [comment]
I can’t find the setting for route based S2S. Is it in the UniFi network portal?

**Comment by peacey** [comment]
Check your S2S VPN settings in the Unifi network portal. If it's set to Auto, then it's already route-based. If it's set to manual, make sure route-based is checked. 

You can also check in SSH by typing `ip route` and seeing if a route exists for the remote subnet with vti64 as the interface for the route.

**Comment by smgraver1** [comment]
There is no auto or manual. Is it because I’m using OpenVPN?

**Comment by peacey** [comment]
Oh, you're using OpenVPN. Then it's route based by default and you don't have to worry. Just try the tests.

**Comment by smgraver1** [comment]
I can only ping the VPN shared remote ip that is forced

**Comment by smgraver1** [comment]
not any device on the network or the local ip of the remote UDM pro at 192.168.1.1

**Comment by peacey** [comment]
Please do these tests with split-vpn off. So you're saying that even with split-vpn off, you cannot ping any remote subnet on the S2S? That should work fine without split-vpn first. Did you add the remote subnets properly to your S2S settings?

**Comment by smgraver1** [comment]
I got it working. Had to reconfigure my remote subnets.

**Comment by smgraver1** [comment]
pinging google and 1.1.1.1 work but they are not a forced destination on my vpn.conf

**Comment by smgraver1** [comment]
Oh. I think sites just started working now after I changed the remote subnet to the correct set.

**Comment by peacey** [comment]
That's good. Everything is working correctly now? If not, show me your vpn.conf.

**Comment by smgraver1** [comment]
Everything seems to be working. Thanks for the help again!

**Comment by peacey** [comment]
I'm glad everything's working now! Feel free to close this issue if you're done, or ask more questions if you have any. 

Have a nice day!
