### ISSUE TITLE
does this work with Cisco AnyConnect Linux client?

### ISSUE THREAD

**Issue by pookguy88** [peacey/split-vpn#18]
does anyone know if this will work with the Cisco AnyConnect client? I _think_ it uses OpenVPN on the backend...??

**Comment by peacey** [comment]
Hello,

Apologies, this script currently only supports OpenVPN or WireGuard clients. However, I was able to run openconnect (the open-source AnyConnect client) through a docker container on the UDM, so it might be possible to add support for it to this script.

I don't have access to an AnyConnect server, so let me create a server and do some testing to see if this is possible.

**Comment by pookguy88** [comment]
no need for apologies man, I'm just grateful this thing exists

appreciate your efforts

**Comment by peacey** [comment]
Thanks! I was able to get the script working with the openconnect client and everything seems to be working well. I just need to put it all together now so it's packaged nicely and test it properly. Will have it done in the next few days!

**Comment by pookguy88** [comment]
sweet, can't wait to try this out!

**Comment by peacey** [comment]
Hey @pookguy88, I added support for OpenConnect now. Please check the README and try it out. Tell me if it works or if you encounter any problems.

Thanks!

**Comment by peacey** [comment]
Hi @pookguy88,

I've tested this successfully several times now, so I am closing this issue. If you encounter any problems setting it up, please reopen the issue and I can help out! 

Have a nice day!
