### ISSUE TITLE
no more SplitVPN if DPI/IPS on

### ISSUE THREAD

**Issue by lowrisk75** [peacey/split-vpn#186]
I experienced some unusual issues with my Dream Machine SE and the SplitVPN. For some reason, I decided to upgrade to UDM SE v3.1.11, but unfortunately, it only made things worse.

After spending hours troubleshooting, I decided to access the Firewall and Security settings. I disabled Device Identification, Traffic Identification, and added blocking. Surprisingly, WireGuard came back online.

When checking the system log and Security detection section, I couldn't find any information regarding my AWS WireGuard server or anything related to the SplitVPN. I understand that the provided information is limited, but I'm curious if this is a known issue.

-- again thank you so much for this script, I coudn't work without it !

**Comment by peacey** [comment]
Did you end up resolving this? Sorry for the delay in answering.

**Comment by lowrisk75** [comment]
> Did you end up resolving this? Sorry for the delay in answering.

No, but something must be wrong with my Dream Machine SE. It often have weird and strange behavior. I will try to back up my WG config & everything else and perform a factory reset when I have some time.
thank you
