### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CodingSpiderFox** [peacey/split-vpn#20]
Hi, could you please add a license to the repo? 

Thanks :)

**Comment by peacey** [comment]
Hi @CodingSpiderFox. Sorry for the oversight, I have added a [GPLv3 LICENSE](https://github.com/peacey/split-vpn/blob/main/LICENSE) now found in the root folder.

**Comment by CodingSpiderFox** [comment]
Thx :)

**Comment by peacey** [comment]
Thank you for telling me! Closing this issue now.
