### ISSUE TITLE
VPN Connects however clients not routed through vpn

### ISSUE THREAD

**Issue by justlookingaround12** [peacey/split-vpn#22]
I followed the guide and got stuck at step 7. The connection is working however no client is going through the vpn (the killswitch isn't being respected either). 

I figured i must have something wrong in the vpn.conf so i added all my vlans not just the one i want in forced source interface as well as the ip of my device i test in forced source ipv4. 

Anything specific i should lookout for?

**Comment by peacey** [comment]
Hi @justlookingaround12,

Can you show me your vpn.conf file?

Also, after you run the VPN, can you show me the output of these commands?

```sh
iptables -t mangle -S
ip rule show | grep fwmark
ip route show table 101
```

Thanks.

**Comment by justlookingaround12** [comment]
Thanks @peacey for getting back to me, if i understood correctly i connected to the vpn, waited a while, disconnected then ran the commands you mentioned. ip rule show and rout show table returned nothing. I have also attached my conf file. (as txt so that it attaches)

`# iptables -t mangle -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N UBIOS_FORWARD_JUMP
-N UBIOS_FORWARD_TCPMSS
-N UBIOS_FORWARD_USER_HOOK
-N UBIOS_INPUT_JUMP
-N UBIOS_INPUT_USER_HOOK
-N UBIOS_OUTPUT_JUMP
-N UBIOS_OUTPUT_USER_HOOK
-N UBIOS_POSTROUTING_JUMP
-N UBIOS_POSTROUTING_SHAPER
-N UBIOS_POSTROUTING_USER_HOOK
-N UBIOS_PREROUTING_JUMP
-N UBIOS_PREROUTING_USER_HOOK
-A PREROUTING -j UBIOS_PREROUTING_JUMP
-A INPUT -j UBIOS_INPUT_JUMP
-A FORWARD -j UBIOS_FORWARD_JUMP
-A OUTPUT -j UBIOS_OUTPUT_JUMP
-A POSTROUTING -j UBIOS_POSTROUTING_JUMP
-A UBIOS_FORWARD_JUMP -j UBIOS_FORWARD_TCPMSS
-A UBIOS_POSTROUTING_JUMP -j UBIOS_POSTROUTING_SHAPER
[vpn.txt](https://github.com/peacey/split-vpn/files/6665633/vpn.txt)
`

**Comment by peacey** [comment]
Thank you for the config. The config looks fine to me. But sorry, I meant to run those command while the connection is up, not after you bring it down. You can either run openvpn in the background, or just open another SSH session in another window and run those commands there.

**Comment by justlookingaround12** [comment]
Just ran those commands again while vpn was connected but still no output. Wonder how I've messed this up lol

**Comment by peacey** [comment]
Uhh, that is weird. Can you show me the openvpn output?

**Comment by justlookingaround12** [comment]
Yup here it is:
`Wed Jun 16 23:44:05 2021 WARNING: file 'username_password.txt' is group or others accessible
Wed Jun 16 23:44:05 2021 OpenVPN 2.4.4 aarch64-buildroot-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AE$Wed Jun 16 23:44:05 2021 library versions: OpenSSL 1.0.2o  27 Mar 2018, LZO 2.10
Wed Jun 16 23:44:05 2021 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Wed Jun 16 23:44:05 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined $Wed Jun 16 23:44:05 2021 NOTE: --fast-io is disabled since we are not using UDP
Wed Jun 16 23:44:05 2021 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authenti$Wed Jun 16 23:44:05 2021 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authenti$Wed Jun 16 23:44:05 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]37.19.212.209:443
Wed Jun 16 23:44:05 2021 Socket Buffers: R=[87380->87380] S=[87380->87380]
Wed Jun 16 23:44:05 2021 Attempting to establish TCP connection with [AF_INET]37.19.212.209:443 [nonblock]
Wed Jun 16 23:44:06 2021 TCP connection established with [AF_INET]37.19.212.209:443
Wed Jun 16 23:44:06 2021 TCP_CLIENT link local: (not bound)
Wed Jun 16 23:44:06 2021 TCP_CLIENT link remote: [AF_INET]37.19.212.209:443
Wed Jun 16 23:44:06 2021 TLS: Initial packet from [AF_INET]37.19.212.209:443, sid=56bc8a12 0d187185
Wed Jun 16 23:44:06 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to pr$`

**Comment by peacey** [comment]
It doesn't seem like the split-vpn script started there. Did you add the --up and --down options to the openvpn commands when you ran it? Like, 

```sh
openvpn --config nordvpn.ovpn \
        --route-noexec \
        --up /mnt/data/split-vpn/vpn/updown.sh \
        --down /mnt/data/split-vpn/vpn/updown.sh \
        --script-security 2
```
Make sure you paste the whole command not just the first line.

**Comment by justlookingaround12** [comment]
Yea i did, I even added the `--auth-user-pass username_password.txt \` as the last line to make sure all the commands are 'going through'

**Comment by peacey** [comment]
Can you show me your openvpn config (ovpn/conf file), and what provider are you using?

**Comment by justlookingaround12** [comment]
I'm using nordvpn, here is the original attached.
[ca-us44.nordvpn.com.tcp443.txt](https://github.com/peacey/split-vpn/files/6665856/ca-us44.nordvpn.com.tcp443.txt)

**Comment by peacey** [comment]
I just tried your config and it worked fine. The problem is your openvpn is not completing the connection. It should say VERIFY OK and many more things if the connection was established.  

Do you have any firewall rules that could prevent this connection from completing?

**Comment by justlookingaround12** [comment]
No none that I know of, but at least now i know what's going wrong maybe I can contact Nordvpn support, thank you so much and I'll post back as soon as I have it figured out!

**Comment by peacey** [comment]
By the way, can you connect to NordVPN with openvpn from your computer instead of the router? Like run openvpn on your computer with this configuration? 

Also, maybe you can try the UDP config files instead of TCP that Nord gives you. UDP is better for VPN anyways.

**Comment by justlookingaround12** [comment]
So it turns out that Openvpn won't work where I'm from, I guess I might have to try and follow the wiregaurd method although it looks very overwhelming. 

PS I tried udp/tcp/scrambled(obfuscated) all with no success. Thank you
