### ISSUE TITLE
Very low Wireguard-go speeds

### ISSUE THREAD

**Issue by justlookingaround12** [peacey/split-vpn#23]
I went through the wireguard-go setup knowing that it's not going to be the fastest connection, however I have a feeling that I'm getting much worse performance than i should on the UDM-Pro. On my 1 gig connection I'm averaging 170 kbps download speed on fast.com and websites load very slowly. I just wanted to check if this is normal/expected?

**Comment by peacey** [comment]
No this is not expected. I'm able to get 200 Mbps on wireguard-go. 

Can you please try your WireGuard configuration on your computer first instead of the router and see what speeds you get there?

**Comment by justlookingaround12** [comment]
I'm trying to install wireguard-go on my Ubuntu VM for just that reason, however the instructions are nowhere near as clear as yours! If there's any other way to test let me know and I'll do that. Through my VPN providers software using the wireguard method gives 30-40 mbps on (relatively weak) wifi

**Comment by peacey** [comment]
Which WireGuard provider and server are you using? Let me try the same one on my end to see how fast it is through the router or on my PC.

**Comment by justlookingaround12** [comment]
Currently using Strongvpn San Francisco server

**Comment by peacey** [comment]
So I just tried it with wireguard-go on the UDMP, and I was able to get around 50 Mbps with a speedtest on that wireguard server (I live in Canada). So I'm not sure why you're getting less than 1 Mbps. 

Can you try other servers? Try to pick the closest server to you at first. 

Also, are you using PPPoE or DHCP for your WAN?

**Comment by peacey** [comment]
Hey @justlookingaround12,

I've double checked on my end and I'm able to get around 50-100 Mbps with wireguard-go. Please try again with another server and if you're still having issues, reopen this issue. I'm closing it for now due to inactivity.

Thanks!
