### ISSUE TITLE
dual vpn

### ISSUE THREAD

**Issue by theeddie** [peacey/split-vpn#24]
Im trying to use 2 connections with the same provider 
[#] ip -4 address add 10.13.128.81/24 dev wg1
[#] ip link set mtu 1420 up dev wg1
RTNETLINK answers: Address already in use

Im sure its something dumb but got any advice

**Comment by peacey** [comment]
Hi @theeddie,

Which provider is this? Can you show me your WireGuard configs for each connection, and the vpn.conf files for each connection? 

Thanks.

**Comment by theeddie** [comment]
torguard 

sure got an email or some other form for me to send them?

**Comment by peacey** [comment]
You can just sanitize them (remove the Keys and any public IPs you have) and upload them to your comment as .txt files. 

By the way, do the two different connections have different keys and different addresses?

**Comment by theeddie** [comment]
yes, 2 different keys and 2 different addresses. 

# 1   wg0.conf 

# TorGuard WireGuard Config
[Interface]

PrivateKey = MINv9EO**********+Zj3zn2PKlcBykw=
ListenPort = 51820
Address = 10.13.128.89/24
PreUp = sh /mnt/data/split-vpn/vpn/updown.sh %i pre-up
PostUp = sh /mnt/data/split-vpn/vpn/updown.sh %i up
PreDown = sh /mnt/data/split-vpn/vpn/updown.sh %i down
Table = 101

[Peer]
PublicKey = 6Mmiesa3MT***********T8Z+kY9fnTbxWg=
Endpoint = *.32.*.2:1443
AllowedIPs = 0.0.0.0/1,128.0.0.0/1,::/1,8000::/1
PersistentKeepalive = 25

vpn.conf

### SPLIT VPN OPTIONS ###                                                                                                                                                         
# Enter multiple entries separated by spaces.                                                                                                                                     
# Do not enter square brackets around the entries.                                                                                                                                
                                                                                                                                                                                  
# Force these sources through the VPN.                                                                                                                                            
# Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.                                                                                                       
FORCED_SOURCE_INTERFACE="br40"                                                                                                                                                    
FORCED_SOURCE_IPV4="10.0.0.7 10.0.0.14"                                                                                                                                           
FORCED_SOURCE_IPV6=""                                                                                                                                                             
FORCED_SOURCE_MAC="18:65:71:e4:6c:67"                                                                                                                                             
                                                                                                                                                                                  
# Force these destinations through the VPN.                                                                                                                                       
# These destinations will be forced regardless of source.                                                                                                                         
# Format: [IP/nn]                                                                                                                                                                 
FORCED_DESTINATIONS_IPV4=""                                                                                                                                                       
FORCED_DESTINATIONS_IPV6=""                                                                                                                                                       
                                                                                                                                                                                  
# Force local UDM traffic going out of these WAN interfaces to go through the                                                                                                     
# VPN instead for both IPv4 and IPv6 traffic.                                                                                                                                     
# This does not include routed traffic, only local traffic generated by the UDM.                                                                                                  
# For UDM-Pro, set to "eth8" for WAN1/Ethernet port, or "eth9" for WAN2/SFP+ port,                                                                                                
# or "eth8 eth9" for both. For UDM Base, set to "eth1" for the WAN port.                                                                                                          
FORCED_LOCAL_INTERFACE=""                                                                                                                                                         
                                                                                                                                                                                  
# Exempt these sources from the VPN.                                                                                                                                              
# Format: [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.                                                                                                                            
EXEMPT_SOURCE_IPV4=""                                                                                                                                                             
EXEMPT_SOURCE_IPV6=""                                                                                                                                                             
EXEMPT_SOURCE_MAC=""                                                                                                                                                              
                                                                                                                                                                                  
# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]                                                                                                            
# Maximum 15 ports per entry.                                                                                                                                                     
EXEMPT_SOURCE_IPV4_PORT=""                                                                                                                                                        
EXEMPT_SOURCE_IPV6_PORT=""                                                                                                                                                        
EXEMPT_SOURCE_MAC_PORT=""                                                                                                                                                         
                                                                                                                                                                                  
# Exempt these destinations from the VPN.                                                                                                                                         
# Format: [IP/nn]                                                                                                                                                                 
EXEMPT_DESTINATIONS_IPV4=""                                                                                                                                                       
EXEMPT_DESTINATIONS_IPV6=""                                                                                                                                                       
                                                                                                                                                                                  
# Force/exempt these IP sets                                                                                                                                                      
# IP sets need to be created before this script is run or the script will error.                                                                                                  
# IP sets can be updated externally and will be matched dynamically.                                                                                                              
# Each IP set entry consists of the IP set name and whether to match on source                                                                                                    
# or destination. src/dst needs to be specified for each IP set field.                                                                                                            
#                                                                                                                                                                                 
# You can also use this option to allow NAT hairpin to work while on the VPN                                                                                                      
# by adding the Unifi IP sets for the interface to the EXEMPT_IPSETS variable.                                                                                                    
# For example, for eth8 WAN, IP sets are UBIOS_ADDRv4_eth8 and UBIOS_ADDRv6_eth8.                                                                                                 
# For prefix delegation, IPv6 WAN addresses are stored in the bridge interfaces,                                                                                                  
# not eth interfaces.                                                                                                                                                             
#                                                                                                                                                                                 
# Format: [IPSet Name]:[src/dst,src/dst,...]                                                                                                                                      
FORCED_IPSETS=""                                                                                                                                                                  
EXEMPT_IPSETS=""                                                                                                                                                                  
                                                                                                                                                                                  
# VPN port forwards.                                                                                                                                                              
# Format: [tcp/udp/both]-[VPN Port]-[Forward IP]-[Forward Port]                                                                                                                   
PORT_FORWARDS_IPV4=""                                                                                                                                                             
PORT_FORWARDS_IPV6=""                                                                                                                                                             
                                                                                                                                                                                  
# Redirect IPv4 and IPv6 DNS to these addresses for VPN-destined traffic.                                                                                                         
# Note that many VPN providers redirect DNS going through their VPN network                                                                                                       
# to their own DNS servers. Redirection to other IPs might not work on all providers,                                                                                             
# except for DNS redirects to a local address, or rejecting DNS traffic completely.                                                                                               
#                                                                                                                                                                                 
# IPV4 Format: [IP] to redirect to IP, "DHCP" if using OpenVPN or OpenConnect to obtain                                                                                           
# DNS from DHCP options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on                                                                                        
# other VPN types like wireguard/external.                                                                                                                                        
#                                                                                                                                                                                 
# Example: Get DNS from DHCP                                                                                                                                                      
DNS_IPV4_IP="10.0.0.4"                                                                                                                                                            
DNS_IPV4_PORT=53                                                                                                                                                                  
# Set this to the interface (brX) the DNS is on if it is a local IP. Leave blank for                                                                                              
# non-local IPs. Local DNS redirects will not work without specifying the interface.                                                                                              
DNS_IPV4_INTERFACE="br0"                                                                                                                                                          
                                                                                                                                                                                  
# IPV6 Format: [IP] to redirect to IP, or "REJECT" to reject IPv6 DNS traffic completely.                                                                                         
# IPV6 Format: [IP] to redirect to IP, "DHCP" if using OpenConnect to obtain DNS from DHCP                                                                                        
# options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on                                                                                                      
# other VPN types.                                                                                                                                                                
DNS_IPV6_IP=""                                                                                                                                                                    
DNS_IPV6_PORT=53                                                                                                                                                                  
DNS_IPV6_INTERFACE=""                                                                                                                                                             
                                                                                                                                                                                  
# Bypass masquerade (SNAT) for these source IPs. This option should only be used if your                                                                                          
# VPN server is setup to know how to route the subnet you do not want to masquerade                                                                                               
# (e.g.: the "iroute" option in OpenVPN).                                                                                                                                         
# Set these options to ALL to disable masquerading completely.                                                                                                                    
# Format: [IP/nn] or "ALL"                                                                                                                                                        
BYPASS_MASQUERADE_IPV4=""                                                                                                                                                         
BYPASS_MASQUERADE_IPV6=""                                                                                                                                                         
                                                                                                                                                                                  
# Enabling kill switch drops VPN-destined traffic that doesn't go through the VPN.                                                                                                
KILLSWITCH=0                                                                                                                                                                      
                                                                                                                                                                                  
# Enable this only if you are testing or you don't care about your real IP leaking                                                                                                
# when the vpn client restarts or exits.                                                                                                                                          
REMOVE_KILLSWITCH_ON_EXIT=0                                                                                                                                                       
                                                                                                                                                                                  
# Enable this if you added blackhole routes in the Unifi Settings to prevent Internet                                                                                             
# access at system startup before the VPN script runs. This option removes the blackhole                                                                                          
# routes to restore Internet access after the killswitch has been enabled.                                                                                                        
# If you do not set this to 1, openvpn will not be able to connect at startup, and your                                                                                           
# Internet access will never be enabled until you manually remove the blackhole routes.                                                                                           
# Set this to 0 only if you did not add any blackhole routes.                                                                                                                     
REMOVE_STARTUP_BLACKHOLES=1                                                                                                                                                       
                                                                                                                                                                                  
# Set the VPN provider.                                                                                                                                                           
# "openvpn" for OpenVPN (default), "openconnect" for OpenConnect, "external" for wireguard,                                                                                       
# or "nexthop" for an external VPN client.                                                                                                                                        
VPN_PROVIDER="external"                                                                                                                                                           
                                                                                                                                                                                  
# If using "external" for VPN_PROVIDER, set this to the VPN endpoint IP so that the                                                                                               
# gateway route can be automatically added for the VPN endpoint.                                                                                                                  
# OpenVPN passes the VPN endpoint IP to the script and will override these values.                                                                                                
# These must be defined if using VPN_PROVIDER="nexthop".                                                                                                                          
VPN_ENDPOINT_IPV4="*.32.*.2"                                                                                                                                                    
VPN_ENDPOINT_IPV6=""                                                                                                                                                              
                                                                                                                                                                                  
# Set this to the route table that contains the gateway route, "auto", or "disabled".                                                                                             
# The Ubiquiti route table are "201" if you're using Ethernet, "202" for SFP+, and                                                                                                
# "203" for U-LTE.                                                                                                                                                                
# Default is "auto" which works with WAN failover and automatically changes the endpoint                                                                                          
# via gateway route when the WAN or gateway routes changes.                                                                                                                       
# Set to "disabled" for nexthop option to connect to a LAN computer.                                                                                                              
GATEWAY_TABLE="auto"                                                                                                                                                              
                                                                                                                                                                                  
# Set this to the timer to use for the rule watcher (in seconds).                                                                                                                 
# The script will wake up every N seconds to re-add rules if they're deleted by                                                                                                   
# the system, or change gateway routes if they changed. Default is 1 second.                                                                                                      
WATCHER_TIMER=1                                                                                                                                                                   
                                                                                                                                                                                  
# Options for custom table and chains.                                                                                                                                            
# These options need to be unique for each instance of openvpn if running multiple.                                                                                               
ROUTE_TABLE=101                                                                                                                                                                   
MARK=0x9                                                                                                                                                                          
PREFIX="VPN_"                                                                                                                                                                     
PREF=99    



This one works great. ^^^^^^



Now the second one 

wg1.conf

# TorGuard WireGuard Config
[Interface]
PrivateKey = 8Dikaceug6*************mw0OpFpkgwlFo=
ListenPort = 51820
Address = 10.13.128.81/24
PreUp = sh /mnt/data/split-vpn/vpn/updown.sh %i pre-up
PostUp = sh /mnt/data/split-vpn/vpn/updown.sh %i up
PreDown = sh /mnt/data/split-vpn/vpn/updown.sh %i down
Table = 100

[Peer]
PublicKey = dJSw5A***************qjfAAmPngmGn2QA=
AllowedIPs = 0.0.0.0/1,128.0.0.0/1,::/1,8000::/1
Endpoint = *.44.*.250:1443
PersistentKeepalive = 25
~

vpn.conf

### SPLIT VPN OPTIONS ###
# Enter multiple entries separated by spaces.
# Do not enter square brackets around the entries.

# Force these sources through the VPN.
# Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
FORCED_SOURCE_INTERFACE=""
FORCED_SOURCE_IPV4=""
FORCED_SOURCE_IPV6=""
FORCED_SOURCE_MAC=""

# Force these destinations through the VPN.
# These destinations will be forced regardless of source.
# Format: [IP/nn]
FORCED_DESTINATIONS_IPV4=""
FORCED_DESTINATIONS_IPV6=""

# Force local UDM traffic going out of these WAN interfaces to go through the
# VPN instead for both IPv4 and IPv6 traffic.
# This does not include routed traffic, only local traffic generated by the UDM.
# For UDM-Pro, set to "eth8" for WAN1/Ethernet port, or "eth9" for WAN2/SFP+ port,
# or "eth8 eth9" for both. For UDM Base, set to "eth1" for the WAN port.
FORCED_LOCAL_INTERFACE=""

# Exempt these sources from the VPN.
# Format: [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
EXEMPT_SOURCE_IPV4=""
EXEMPT_SOURCE_IPV6=""
EXEMPT_SOURCE_MAC=""

# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
# Maximum 15 ports per entry.
EXEMPT_SOURCE_IPV4_PORT=""
EXEMPT_SOURCE_IPV6_PORT=""
EXEMPT_SOURCE_MAC_PORT=""

# Exempt these destinations from the VPN.
# Format: [IP/nn]
EXEMPT_DESTINATIONS_IPV4=""
EXEMPT_DESTINATIONS_IPV6=""

# Force/exempt these IP sets
# IP sets need to be created before this script is run or the script will error.
# IP sets can be updated externally and will be matched dynamically.
# Each IP set entry consists of the IP set name and whether to match on source
# or destination. src/dst needs to be specified for each IP set field.
#
# You can also use this option to allow NAT hairpin to work while on the VPN
# by adding the Unifi IP sets for the interface to the EXEMPT_IPSETS variable.
# For example, for eth8 WAN, IP sets are UBIOS_ADDRv4_eth8 and UBIOS_ADDRv6_eth8.
# For prefix delegation, IPv6 WAN addresses are stored in the bridge interfaces,
# not eth interfaces.
#
# Format: [IPSet Name]:[src/dst,src/dst,...]
FORCED_IPSETS=""
EXEMPT_IPSETS=""

# VPN port forwards.
# Format: [tcp/udp/both]-[VPN Port]-[Forward IP]-[Forward Port]
PORT_FORWARDS_IPV4=""
PORT_FORWARDS_IPV6=""

# Redirect IPv4 and IPv6 DNS to these addresses for VPN-destined traffic.
# Note that many VPN providers redirect DNS going through their VPN network
# to their own DNS servers. Redirection to other IPs might not work on all providers,
# except for DNS redirects to a local address, or rejecting DNS traffic completely.
#
# IPV4 Format: [IP] to redirect to IP, "DHCP" if using OpenVPN or OpenConnect to obtain
# DNS from DHCP options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on
# other VPN types like wireguard/external.
#
# Example: Get DNS from DHCP
DNS_IPV4_IP="10.0.0.4"
DNS_IPV4_PORT=53
# Set this to the interface (brX) the DNS is on if it is a local IP. Leave blank for
# non-local IPs. Local DNS redirects will not work without specifying the interface.
DNS_IPV4_INTERFACE="br0"

# IPV6 Format: [IP] to redirect to IP, or "REJECT" to reject IPv6 DNS traffic completely.
# IPV6 Format: [IP] to redirect to IP, "DHCP" if using OpenConnect to obtain DNS from DHCP
# options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on
# other VPN types.
DNS_IPV6_IP=""
DNS_IPV6_PORT=53
DNS_IPV6_INTERFACE=""

# Bypass masquerade (SNAT) for these source IPs. This option should only be used if your
# VPN server is setup to know how to route the subnet you do not want to masquerade
# (e.g.: the "iroute" option in OpenVPN).
# Set these options to ALL to disable masquerading completely.
# Format: [IP/nn] or "ALL"
BYPASS_MASQUERADE_IPV4=""
BYPASS_MASQUERADE_IPV6=""

# Enabling kill switch drops VPN-destined traffic that doesn't go through the VPN.
KILLSWITCH=0

# Enable this only if you are testing or you don't care about your real IP leaking
# when the vpn client restarts or exits.
REMOVE_KILLSWITCH_ON_EXIT=1

# Enable this if you added blackhole routes in the Unifi Settings to prevent Internet
# access at system startup before the VPN script runs. This option removes the blackhole
# routes to restore Internet access after the killswitch has been enabled.
# If you do not set this to 1, openvpn will not be able to connect at startup, and your
# Internet access will never be enabled until you manually remove the blackhole routes.
# Set this to 0 only if you did not add any blackhole routes.
REMOVE_STARTUP_BLACKHOLES=1

# Set the VPN provider.
# "openvpn" for OpenVPN (default), "openconnect" for OpenConnect, "external" for wireguard,
# or "nexthop" for an external VPN client.
VPN_PROVIDER="external"

# If using "external" for VPN_PROVIDER, set this to the VPN endpoint IP so that the
# gateway route can be automatically added for the VPN endpoint.
# OpenVPN passes the VPN endpoint IP to the script and will override these values.
# These must be defined if using VPN_PROVIDER="nexthop".
VPN_ENDPOINT_IPV4="*.44.*.250"
VPN_ENDPOINT_IPV6=""

# Set this to the route table that contains the gateway route, "auto", or "disabled".
# The Ubiquiti route table are "201" if you're using Ethernet, "202" for SFP+, and
# "203" for U-LTE.
# Default is "auto" which works with WAN failover and automatically changes the endpoint
# via gateway route when the WAN or gateway routes changes.
# Set to "disabled" for nexthop option to connect to a LAN computer.
GATEWAY_TABLE="auto"

# Set this to the timer to use for the rule watcher (in seconds).
# The script will wake up every N seconds to re-add rules if they're deleted by
# the system, or change gateway routes if they changed. Default is 1 second.
WATCHER_TIMER=1

# Options for custom table and chains.
# These options need to be unique for each instance of openvpn if running multiple.
ROUTE_TABLE=100
MARK=0x8
PREFIX="VPM_"
PREF=50
DEV=wg1

**Comment by theeddie** [comment]
im sure its something dumb

**Comment by peacey** [comment]
Oh, these are client configurations right, not servers? Why do you have ListenPort options in your WireGuard configs? That option is only for servers to listen on that port. I don't think clients need that option. It's complaining because both clients are trying to listen on that same port.

**Comment by theeddie** [comment]
you got it thanks!!  removed the listening port and they worked

**Comment by peacey** [comment]
That's great! You can close this issue if that's all the problems you're having.

Have a nice day :)

**Comment by theeddie** [comment]
Also wireguard I'm pulling 250mbps  love it, open VPN was barely 70
