### ISSUE TITLE
Wifi Network Connections

### ISSUE THREAD

**Issue by weswitt** [peacey/split-vpn#26]
is it possible to route all clients on a particular wifi network through the vpn?  if so how can i config this?

**Comment by peacey** [comment]
Hi @weswitt,

Yes that's possible. Create a WiFi network on a separate VLAN first. Do you know how to do that on the UDMP settings?

After you do that, use this script and configure `FORCED_SOURCE_INTERFACE="br5"` in your vpn.conf file. Change br5 to whatever your VLAN is. The format is brX, where X = VLAN number.

**Comment by weswitt** [comment]
perfect and thanks.
