### ISSUE TITLE
Request: restart crashed openvpn process

### ISSUE THREAD

**Issue by midzelis** [peacey/split-vpn#27]
First off, THANK YOU for putting this script together. I had cobbled up something like this, but nowhere near as full featured as what you got here. I'm going to be using this from now on. 

I'm not sure if I'm alone in this, but I found that my openvpn process crashes occasionally. I basically put my openvpn command in a loop. 

i.e. 
```shell
#!/bin/sh
set -e
rm -f /mnt/data/on_boot.d/vpn_log.log
while true; do
    openvpn /mnt/data/on_boot.d/vpn.conf >> /mnt/data/on_boot.d/vpn_log.log 2>&1
    echo "Server crashed with exit code $?. Respawning.." >> /mnt/data/on_boot.d/vpn_log.log
    sleep 1
done
```

However, since I saw your script runs in the background, I was wondering if maybe you could ping an address (or the remote router) to check if the connection is alive, and restart it. I have sometimes found that the openvpn process was not terminated, but running, but in some kind of stuck state. It would be awesome if we could create a little watchdog script to make sure the other end of the script is available, and if it isn't - then bounce the server. Would this be something you could add?

**Comment by peacey** [comment]
Hi @midzelis,

This is definitely a possibility for a last resort. But I just want to first ask, why is the OpenVPN process crashing? Do you have a copy of the openvpn.log file when openvpn crashes? If it is a bug with this script that is causing then we could fix that as well.

The OpenVPN process itself has a `--ping-restart` option which is used by default in the guide. You are saying this option is not working for you as intended, and OpenVPN is simply crashing or stalling and not restarting automatically with this option?

Again, as a last resort, a watcher script is a great idea and we can definitely implement one by doing the same thing that OpenVPN does (pinging an IP through the tunnel and restarting if no response after X times). But it would be good to see why openvpn is crashing too.

**Comment by midzelis** [comment]
I witnessed this once again, and did a little bit of debugging. The problem was not on the client VPN, but rather on the server VPN. Note: I'm using a UDM (1.9.3) as a OpenVPN client and UDM-Pro (1.9.3) as OpenVPN server. And what was super unusual about it all was that the OpenVPN process was still running, but logs didn't show any incoming connections. A telnet from the client to the server port was also never established. I launched tcpdump on the remote server, and didn't see any packets. So I diagnosed further. I did `iptables -L -v -n` on the server, and magically, the existing OpenVPN server process came back to life and a connection was established. 

Have you ever seen packets get lost/hung completely, until issuing an iptables list rules command? Bizzare. 

This doesn't seem to happen to often, but next time it does I'll try to debug further. And if that `iptables` command fixes it, but I can at least create a script to issue it when I don't detect an active connection.

**Comment by peacey** [comment]
Hi @midzelis,

Since the client didn't crash, I think the `--ping-restart` client option would have worked for this scenario to automatically reconnect. That option pings the server and if there are no responses within 15 seconds or whatever you define, then it will reconnect to the server. Have you tried to or can you use this option like this in the openvpn command?

    ```sh
    nohup openvpn --config nordvpn.ovpn \
              --route-noexec \
              --up /mnt/data/split-vpn/vpn/updown.sh \
              --down /mnt/data/split-vpn/vpn/updown.sh \
              ...
              --script-security 2 \
              --ping-restart 15 \
              --mute-replay-warnings &> openvpn.log &
    ```
The ... is for any extra options you might use. The point is to include the `--ping-restart` option as shown in the second last line.

Please try that option and tell me if it works to reconnect.

**Comment by midzelis** [comment]
Thanks for the suggestion, but I was already using --ping-restart. In fact, the client was attempting to connect to the server over and over, but no packets were making to the server (tcpdump on the server didn't display any incoming packets) -- they were getting lost somehow. But when I issued `iptables -L -v -n` on the server it started working again.

**Comment by peacey** [comment]
Oh that's very odd. Your command doesn't even change anything. Maybe it was just chance that it got fixed at the same time you did that command? 

Does your server have some type of power saving active on the Internet adapter or computer, or some type of hibernation? Please double check the server settings for anything that could effect it. 

Also, when this happens, can you ping the server from another computer? Or is all network access on this server inactive when this happens?

Please try to check these settings and watch for this issue again. See if the same command you ran fixes it again, or running different commands.

**Comment by peacey** [comment]
Hi @midzelis,

Given that the OpenVPN client already has a way to restart on failure which is documented, and that you figured out the problem was your server and that the client can't do anything about it, do we still need to have this issue opened?

**Comment by midzelis** [comment]
Sounds good - closing!
