### ISSUE TITLE
Doc: Need to specify route_vpn_gateway when remote openvpn server doesn't use DHCP

### ISSUE THREAD

**Issue by midzelis** [peacey/split-vpn#28]
My remote openvpn server doesn't use DHCP to push default routes. As such, the `${route_vpn_gateway}` variable is not passed to the updown.sh script. I was able to manually set this to the value I specify in my openvpn.conf. In my case, I set `route_vpn_gateway="10.99.99.6"`

I would say, maybe make a note of it, or maybe check for empty `route_vpn_gateway` before using it in the script, to help with debugging and pointing users to an easy way to correct it. 

Client's openvpn config....
```shell
# cat openvpn.conf
verb 3
proto udp
dev-type tun
dev tun_VPN_USA
lport 1196
mode p2p
ifconfig 10.99.99.6 10.99.99.5
remote SECRET.SERVER.DOMAIN 1196
ping-restart 20
ping 4
auth-nocache
script-security 2
up-restart
up-delay
up /mnt/data/on_boot.d/vpn/updown.sh
down /mnt/data/on_boot.d/vpn/updown.sh
route-noexec
management 127.0.0.1 1126
float
cipher AES-256-CBC
<secret>
SECRET!!!!
</secret>
```

Server's openvpn config
```shell
# cat openvpn.conf
verb 3
proto udp
dev-type tun
dev tun300
lport 1196
mode p2p
ifconfig 10.99.99.5 10.99.99.6
remote SECRET.CLIENT.DOMAIN 1196
ping-restart 20
ping 4
auth-nocache
script-security 2
up-restart
up /mnt/data/on_boot.d/vpn-up
down-pre
down /mnt/data/on_boot.d/vpn-down
up-delay
route-nopull
management 127.0.0.1 1126
float
cipher AES-256-CBC
<secret>
SECRET!!!!
</secret>
```

**Comment by peacey** [comment]
Thank you for reporting this @midzelis. I was honestly not aware there was a case when the VPN gateway would not get set by OpenVPN.  

I will add a check for it and warn the user if it does not exist.

**Comment by peacey** [comment]
Hey @midzelis,

So I did some more digging and discovered that OpenVPN has a bug where it doesn't assign the route_net_gateway variable IF the server doesn't push any routes. This can be solved by using the `--redirect-gateway def1` option in command line or `redirect-gateway def1` in the client VPN config, which forces OpenVPN to think there's a route so it can set the route_net_gateway variable.

So I don't think you need to define the route_net_gateway variable yourself. Can you instead remove that, and try to use the `--redirect-gateway def1` command line option and see if it works to automatically detect the gateway route?

Thanks!

**Comment by midzelis** [comment]
Yes, using `redirect-gateway def1` will cause OpenVPN to set `route_net_gateway`

**Comment by peacey** [comment]
I've merged the fix for this now. If you have anymore issues with this, please feel free to reopen it.

Thank you so much for reporting this!
