### ISSUE TITLE
Error: inet address is expected rather than "dev".

### ISSUE THREAD

**Issue by dehness** [peacey/split-vpn#32]
Hi, I've been trying to diagnose this problem when connecting to NordVPN:

> # openvpn --config nordvpn.ovpn \
> >         --route-noexec \
> >         --up /mnt/data/split-vpn/vpn/updown.sh \
> >         --down /mnt/data/split-vpn/vpn/updown.sh \
> >         --script-security 2

vpn.conf:
![1](https://user-images.githubusercontent.com/42713745/124670333-2e4cb700-def7-11eb-8107-61d5e2c9b3e5.png)

nordvpn.ovpn:
![image-4](https://user-images.githubusercontent.com/42713745/124670387-4290b400-def7-11eb-8053-aa81efdff025.png)

Sorry for the images, couldn't figure out the markdown.

**Comment by peacey** [comment]
Hi @dehness,

Why is your DEV br10 in your vpn.conf file? DEV should be the name of your VPN tunnel interface, for example tun0. Please change it to `DEV=tun0`. 

Also, why is your DNS_IPV4_INTERFACE="br0" when you are using DHCP from Nord for DNS? You should set it to empty, i.e.: `DNS_IPV4_INTERFACE=""` You should only set this option if you are redirecting to a local DNS, but you are using Nord's DNS.

If you're still getting the error after these changes, please show me the full openvpn log. 

Thanks!

**Comment by dehness** [comment]
Hi @peacey,  thanks for the quick response.

I've been playing around with it trying to get it to work and forgot to revert those settings but the original problem remains:

<img width="1491" alt="Screen Shot 2021-07-07 at 7 50 48 am" src="https://user-images.githubusercontent.com/42713745/124671787-5d642800-def9-11eb-8f4b-1f204d8d2f95.png">

**Comment by peacey** [comment]
Can you edit `/mnt/data/split-vpn/vpn/updown.sh` and change the first line from `set -e` to `set -xe`? Then rerun the VPN again, the -x flag will tell us which line it failed on. Show me that output. Thanks.

**Comment by dehness** [comment]
<img width="1489" alt="Screen Shot 2021-07-07 at 8 07 03 am" src="https://user-images.githubusercontent.com/42713745/124672433-61447a00-defa-11eb-9814-b95a79b23606.png">
<img width="1481" alt="Screen Shot 2021-07-07 at 8 07 22 am" src="https://user-images.githubusercontent.com/42713745/124672445-64d80100-defa-11eb-9656-673e44957813.png">

**Comment by peacey** [comment]
Oh that's weird, Nord isn't sending the VPN gateway to the script. I use Nord and this didn't happen before. 

Can you add the option `--redirect-gateway def1` to your openvpn command, or add `redirect-gateway def1` to your openvpn config file and run the VPN again? It should force it to set the VPN gateway I bemie. Also change back the `set -xe` we did.

**Comment by dehness** [comment]
My man! I spent hours trying to accomplish what you did in seconds.

Works perfectly now and persists across reboots.

Thanks, mate.

**Comment by peacey** [comment]
Glad it worked! Sorry about that issue, I'm going to add that option to the default command in the documentation and warn in the script if the gateway wasn't found so it's easy to debug. 

Hopefully you don't run into any more problems. 

Regards,
Peacey
