### ISSUE TITLE
Restart Tunnel without rebooting the system

### ISSUE THREAD

**Issue by lethalwallabies** [peacey/split-vpn#37]
I have been trying to figure out which .ovpn file is best for my use case but after setting everything I still need to occasionally swap .ovpn files.

I have configured this to be quite straight forwards but cannot figure out how to kill all the associated openvpn processes. Is it possible for a script to go through and restart the process (so it will pull a new configuration) without having to restart the UDM?

**Comment by peacey** [comment]
Hi @lethalwallabies,

You can already do this and it's mentioned in the documentation. Please look at the FAQ entry "How do I safely shutdown the VPN?".

In summary,

* To kill ALL openvpn instances, run

    ```sh
   killall -TERM openvpn
   ```

* To kill a specific openvpn instance using tun0 for example:

    ```sh
    kill -TERM $(pgrep -f "openvpn.*tun0")
    ```

Afterwards, you can start the VPN by running them with your run script or manually or whatever. You can also just add the killall command to the beginning of your run script so it's easy to restart the VPN. 

Also, if you set `REMOVE_KILLSWITCH_ON_EXIT=0` in your configuration, then you will need to force down the VPN rules as well. This option is set to 1 by default so you don't have to worry about that unless you set it to 0 yourself.

**Comment by lethalwallabies** [comment]
Thanks for the great explanation (despite me missing it in the documentation). I appreciate it. :)
