### ISSUE TITLE
Something amiss with password login

### ISSUE THREAD

**Issue by zakrocki** [peacey/split-vpn#41]
First of all a huge thanks for this amazing tool! I've run into something I'm doing wrong. I've followed all the steps and can get Nord VPN to run perfect in the foreground wherein it asks for me to key in my login and password - that works perfect. Things start to fall apart when I try to run it in the background. Per step 3 I've saved my username and passowrd in a file called username_password.txt, and modified the nordvpn.ovpn by adding auth-user-pass username_password.txt . However, when I run the app in the background it prompts me to # Enter Auth Username:Enter Auth Password: What could I be doing wrong? Thanks!

**Comment by peacey** [comment]
Hi @zakrocki,

Please check your openvpn config file and make sure you do not have two instances of auth-user-pass with one being empty.

You can also remove all instances of auth-user-pass from the config and instead add `--auth-user-pass username_password.txt` to the command line when you run openvpn. 

Also the username_password.txt file should contain the username on the first line and password on the second line. How did you create this file?

If you're still having trouble, please show me your openvpn config (not vpn.conf).

**Comment by peacey** [comment]
So there are two run scripts. 

There is a run script you create in your VPN servers directory: /mnt/data/split-vpn/openvpn/nordvpn/run-vpn.sh

There is a master run script you create in the split-vpn directory: /mnt/data/split-vpn/run-vpn.sh

The master run script just calls the specific VPN server run script. So in your case, the master run script should contain this: 

```sh
#!/bin/sh
/mnt/data/split-vpn/openvpn/nordvpn/run-vpn.sh
```

Afterwards you can chmod +x it and link it to the boot directory.

**Comment by zakrocki** [comment]
Thank you so much for not only the amzing VPN script but also for your time. It works absolutely perfectly!!!!!
