### ISSUE TITLE
ipset: command not found

### ISSUE THREAD

**Issue by 13mralex** [peacey/split-vpn#42]
I am using OpenConnect as a client, everything on that side seems okay. I want to apply rules with forced/exempt domains, but this error keeps coming up when trying to use it.

```
# cat openconnect.log
POST https://xx.xx/
Connected to xx.xx.xx.xx:443
SSL negotiation with xx.xx
Connected to HTTPS on xx.xx with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA512)-(AES-256-GCM)
XML POST enabled
POST https://xx.xx/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as xx.xx.xx.xx, using SSL, with DTLS in progress
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS1.2)-(ECDHE-RSA)-(AES-256-GCM).
Thu Sep 16 07:54:04 2021 split-vpn up: Loading configuration from /etc/split-vpn/config/vpn.conf.
Thu Sep 16 07:54:04 2021 split-vpn: Using IPv4 gateway from table 201: via xx.xx.xx.xx dev eth8.
/etc/split-vpn/vpn/add-vpn-iptables-rules.sh: line 99: ipset: command not found
/etc/split-vpn/vpn/add-vpn-iptables-rules.sh: line 108: ipset: command not found
ERROR: Not adding VPN_FORCED with unknown family: .
/etc/split-vpn/vpn/add-vpn-iptables-rules.sh: line 99: ipset: command not found
/etc/split-vpn/vpn/add-vpn-iptables-rules.sh: line 108: ipset: command not found
ERROR: Not adding VPN_EXEMPT with unknown family: .
```

I have verified that ipset is installed, and does work on normal CLI. My configuration shows:
`PREFIX="VPN_"`

`FORCED_IPSETS="VPN_FORCED:dst"`
`EXEMPT_IPSETS="VPN_EXEMPT:dst"`

CLI Output:
```
# ipset list VPN_FORCED
Name: VPN_FORCED
Type: list:set
Revision: 3
Header: size 8
Size in memory: 176
References: 2
Number of entries: 2
Members:
VPN_FORCED4
VPN_FORCED6
```

When setting the log to verbose, the command being executed appears to be correct:
```
+ ipset=VPN_FORCED
++ echo VPN_FORCED:dst
++ cut -d: -f2
+ map=dst
++ ipset list VPN_FORCED
/etc/split-vpn/vpn/add-vpn-iptables-rules.sh: line 99: ipset: command not found
```

**Comment by peacey** [comment]
Hi @13mralex,

Thank you for reporting this. The ipset binary was missing from the openconnect container. I have added it now and updated the container. 

Please delete the container image first by running: `podman rmi -f udm-openconnect`

Then run your openconnect again and see if it works. 

Regards,
Peacey

**Comment by 13mralex** [comment]
Got it! No more errors. I am struggling though with forced domains. Not sure if I have it configured correctly or not. I have the following in my config:
```
DNS_IPV4_IP="10.15.0.1"
DNS_IPV4_PORT="53"
DNS_IPV4_INTERFACE="br0"

DNS_IPV6_IP="REJECT"
DNS_IPV6_PORT="53"
DNS_IPV6_INTERFACE=""

FORCED_IPSETS="VPN_FORCED:dst"
EXEMPT_IPSETS="VPN_EXEMPT:dst"
```

10.15.0.1 is the IP of the UDMP. My VPN_domains config is pulled straight from the sample. When I load a page from the forced domain list, it just times out. When I kill the VPN, it loads up right away. Am I missing something?

**Comment by peacey** [comment]
No, that should be it if you are using the built-in dnsmasq on the UDM. Let's see what's happening.

First, without forced domains, have you tested if the VPN works by forcing a single client IP or VLAN instead of domains? Specifically, can you browse the internet on the forced client, and does your IP show up as the VPN's IP when you check your IP online? Can you visit the domain you want forced if you force via the client's IP/VLAN, or it still doesn't work?

**Comment by peacey** [comment]
Hi @13mralex,

Since the original issue is fixed (ipset missing), I am going to be closing this issue now. But if you are still having problems or need more guidance, please feel free to re-open this issue! 

Thanks!
