### ISSUE TITLE
Unable to get port forwarding to work

### ISSUE THREAD

**Issue by smileyhogue** [peacey/split-vpn#43]
Hi, first of all, I would like to thank you for this as this was exactly what I have been looking for to allow access to a couple of services from outside my network on carrier grade NAT.

I am having an issue with getting port forwarding to work. The VPN is connected, and if I go to my Dedicated PureVPN IP with Port forwarding, I am able to load port 80 which seems to be directed to the UDM pro. But any port forwarding I put in vpn.conf doesnt seem to be working. I am thinking I am just not understanding some instructions but would appreciate a bit of help on it. 

A bit about my setup: 
* PureVPN with Dedicated Port Forwarding (StrongSwan)
* All ports are open on PureVPN side for debugging currently (dont worry, I will limit that when I am up and running)
* I have 2 servers that I will port forward to that I will need access to from outside the network through the VPN as well as direct local access. (A media server on port 32400, a reverse proxy with Home Assistant and a couple other services behind it on port 80 and 443)

Below is my vpn.conf, please let me know if you need any other additional information. I can clean up my other configuration files if needed but as I do see that the VPN is connected and port 80 is open (to the wrong device), my thought is that it is an issue with how I setup vpn.conf.

Quick note on the below vpn.conf:
I am not forcing the server through the VPN as I do still need to access it on the local network as well. I have tried it with the single device forced through the VPN as well and I get the same results as above. 
If I do need to force traffic through the VPN, do you have a way to be able to access it on the local network as well?
```
### SPLIT VPN OPTIONS ###
# Enter multiple entries separated by spaces.
# Do not enter square brackets around the entries.

# Force these sources through the VPN.
# Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
FORCED_SOURCE_INTERFACE=""
FORCED_SOURCE_IPV4=""
FORCED_SOURCE_IPV6=""
FORCED_SOURCE_MAC=""

# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
# Maximum 15 ports per entry.
FORCED_SOURCE_IPV4_PORT=""
FORCED_SOURCE_IPV6_PORT=""
FORCED_SOURCE_MAC_PORT=""

# Force these destinations through the VPN.
# These destinations will be forced regardless of source.
# Format: [IP/nn]
FORCED_DESTINATIONS_IPV4=""
FORCED_DESTINATIONS_IPV6=""

# Force local UDM traffic going out of these WAN interfaces to go through the
# VPN instead for both IPv4 and IPv6 traffic.
# This does not include routed traffic, only local traffic generated by the UDM.
# Do not enable this unless you want to force UDM local traffic through the VPN.
# For UDM-Pro, set to "eth8" for WAN1/Ethernet port, or "eth9" for WAN2/SFP+ port,
# or "eth8 eth9" for both. For UDM Base, set to "eth1" for the WAN port.
# This option might cause unintended problems, so disable it if you encounter any issues.
FORCED_LOCAL_INTERFACE=""

# Exempt these sources from the VPN.
# Format: [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
EXEMPT_SOURCE_IPV4=""
EXEMPT_SOURCE_IPV6=""
EXEMPT_SOURCE_MAC=""

# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
# Maximum 15 ports per entry.
EXEMPT_SOURCE_IPV4_PORT=""
EXEMPT_SOURCE_IPV6_PORT=""
EXEMPT_SOURCE_MAC_PORT=""

# Exempt these destinations from the VPN.
# Format: [IP/nn]
EXEMPT_DESTINATIONS_IPV4=""
EXEMPT_DESTINATIONS_IPV6=""

# Force/exempt these IP sets
# IP sets need to be created before this script is run or the script will error.
# IP sets can be updated externally and will be matched dynamically.
# Each IP set entry consists of the IP set name and whether to match on source
# or destination. src/dst needs to be specified for each IP set field.
#
# Enable NAT hairpin by exempting UBIOS_ADDRv4_ethX:dst for IPv4 or
# UBIOS_ADDRv6_ethX:dst for IPv6 (where X = 8 for RJ45, or 9 for SFP+ WAN).
# For IPv6 prefix delegation, exempt UBIOS_ADDRv6_brX, where X = VLAN number (0 = LAN).
#
# To allow communication with your VLAN subnets without hardcoding the subnets,
# exempt the UBIOS_NETv4_brX:dst ipset for IPv4 or UBIOS_NETv6_brX:dst for IPv6.
#
# Format: [IPSet Name]:[src/dst,src/dst,...]
FORCED_IPSETS=""
EXEMPT_IPSETS=""

# VPN port forwards.
# Format: [tcp/udp/both]-[VPN Port]-[Forward IP]-[Forward Port]
PORT_FORWARDS_IPV4="both-32400-192.168.1.121-32400 both-80-192.168.1.121-80 both-443-192.168.1.121-443 both-81-192.168.1.121-81"
PORT_FORWARDS_IPV6=""

# Redirect IPv4 and IPv6 DNS to these addresses for VPN-destined traffic.
# Note that many VPN providers redirect DNS going through their VPN network
# to their own DNS servers. Redirection to other IPs might not work on all providers,
# except for DNS redirects to a local address, or rejecting DNS traffic completely.
#
# IPV4 Format: [IP] to redirect to IP, "DHCP" if using OpenVPN or OpenConnect to obtain
# DNS from DHCP options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on
# other VPN types like wireguard/external.
#
# Example: Get DNS from DHCP
DNS_IPV4_IP="DHCP"
DNS_IPV4_PORT=53
# Set this to the interface (brX) the DNS is on if it is a local IP. Leave blank for
# non-local IPs. Local DNS redirects will not work without specifying the interface.
DNS_IPV4_INTERFACE=""

# IPV6 Format: [IP] to redirect to IP, or "REJECT" to reject IPv6 DNS traffic completely.
# IPV6 Format: [IP] to redirect to IP, "DHCP" if using OpenConnect to obtain DNS from DHCP
# options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on
# other VPN types.
DNS_IPV6_IP=""
DNS_IPV6_PORT=53
DNS_IPV6_INTERFACE=""

# Bypass masquerade (SNAT) for these source IPs. This option should only be used if your
# VPN server is setup to know how to route the subnet you do not want to masquerade
# (e.g.: the "iroute" option in OpenVPN).
# Set these options to ALL to disable masquerading completely.
# Format: [IP/nn] or "ALL"
BYPASS_MASQUERADE_IPV4=""
BYPASS_MASQUERADE_IPV6=""

# Enabling kill switch drops VPN-destined traffic that doesn't go through the VPN.
KILLSWITCH=0

# Enable this only if you are testing or you don't care about your real IP leaking
# when the vpn client restarts or exits.
REMOVE_KILLSWITCH_ON_EXIT=1

# Enable this if you added blackhole routes in the Unifi Settings to prevent Internet
# access at system startup before the VPN script runs. This option removes the blackhole
# routes to restore Internet access after the killswitch has been enabled.
# If you do not set this to 1, openvpn will not be able to connect at startup, and your
# Internet access will never be enabled until you manually remove the blackhole routes.
# Set this to 0 only if you did not add any blackhole routes.
REMOVE_STARTUP_BLACKHOLES=1

# Set the VPN provider.
# "openvpn" for OpenVPN (default), "openconnect" for OpenConnect, "external" for wireguard,
# or "nexthop" for an external VPN client.
VPN_PROVIDER="external"

# If using "external" for VPN_PROVIDER, set this to the VPN endpoint IP so that the
# gateway route can be automatically added for the VPN endpoint.
# OpenVPN passes the VPN endpoint IP to the script and will override these values.
# These must be defined if using VPN_PROVIDER="nexthop".
#VPN_ENDPOINT_IPV4=""
#VPN_ENDPOINT_IPV6=""

# Set this to the route table that contains the gateway route, "auto", or "disabled".
# The Ubiquiti route table is "201" if you're using Ethernet, "202" for SFP+, and
# "203" for U-LTE.
# Default is "auto" which works with WAN failover and automatically changes the endpoint
# via gateway route when the WAN or gateway routes changes.
# Set to "disabled" if you are using the nexthop option to connect to a VPN on your LAN.
GATEWAY_TABLE="auto"

# Set the MSS clamping on packets going out the VPN tunnel. Usually, it is not needed to
# set this manually, but some VPN connections stall if the MSS clamping is not set correctly.
# Typical values range from 1240 to 1460, but it could be lower.
MSS_CLAMPING_IPV4=""
MSS_CLAMPING_IPV6=""

# Set this to the timer to use for the rule watcher (in seconds).
# The script will wake up every N seconds to re-add rules if they're deleted by
# the system, or change gateway routes if they changed. Default is 1 second.
WATCHER_TIMER=1

# Options for custom table and chains.
# These options need to be unique for each instance of openvpn if running multiple.
ROUTE_TABLE=101
MARK=0x9
PREFIX="VPN_"
PREF=99
DEV=vti255

# To execute commands when the VPN connects or disconnects, you can use the
# callback functions hooks_pre_up, hooks_up, hooks_down, and
# hooks_force_down. These functions will be invoked in response to VPN events
# pre-up, up, down, and force-down respectively.
#
# For an example on using these hooks, please see vpn.conf.filled.sample.
```
Here is some other information you may find useful. I have redacted my IP addresses from these. 

[iptables-ipRule-ipRoute.txt](https://github.com/peacey/split-vpn/files/7188402/iptables-ipRule-ipRoute.txt)
[podman log.txt](https://github.com/peacey/split-vpn/files/7188403/podman.log.txt)

**Comment by peacey** [comment]
Hi @smileyhogue,

I have tested port forwarding with PureVPN dedicated IP using this script, so I know it should work. Let's start with a few things. 

1. Port forwarding only works on your dedicated server. Are you using the correct server?
2. Port forwarding only works when the dedicated server is giving you the correct dedicated IP (i.e. no one else is using this dedicated IP from your account). If you use the PureVPN app on your computer, it tells you what your Dedicated IP is. When you use this script to connect on the UDM, can you run `ip addr show dev vti255` and check if the IP assigned is the correct Dedicated IP as shown in the app? Make sure the app is disconnected before you run the script. 
3. You must use one of the FORCED options to force the port traffic through the VPN or else the reply traffic will go through the main WAN instead of the VPN. You can use the exempt destinations options to exempt local traffic by subnet so you can still access these ports locally. For example, in your case I would set these in the config:

    ```
    FORCED_SOURCE_IPV4_PORT="both-192.168.1.121-80,81,443,32400"
    EXEMPT_DESTINATIONS_IPV4="192.168.1.0/24 192.168.2.0/24 192.168.3.0/24"
    ```
    * Put your local network subnets in `EXEMPT_DESTINATIONS_IPV4`. I used `192.168.1.0/24 192.168.2.0/24 192.168.3.0/24`above as an example of 3 local networks. You can even do a wider subnet like `192.168.0.0/16` instead of specifying each network.
4. You most likely need to set the MSS_CLAMPING setting in your vpn.conf. When I tested PureVPN, I had to use `MSS_CLAMPING_IPV4="1240"` or some connections stalled.

Please check and try the above and see if it works for you. Thanks!

**Comment by smileyhogue** [comment]
Hi @peacey,
Sorry for a bit delayed response! Thank you for the help!
To answer your questions:

1. Yes, i am using the dedicated server I was assigned

2. Yes, it does look like it is the dedicated IP that is assigned. Verified by me being able to access the UDM pro through port 80 on my dedicated IP
3. I set the FORCED_SOURCE_IPV4_PORT and EXEMPT_DESTINATIONS_IPV4 pretty much exactly as you gave me but I added one more network to EXEMPT_DESTINATIONS_IPV4 (192.168.0.0/24)

4. I set `MSS_CLAMPING_IPV4="1240"` 

I am still unable to access anything but the UDM Pro through the VPN. Which is odd because I am not trying to forward any ports to the UDM Pro.
It does seem that now when I force 192.168.1.121 through the VPN, I am now able to access 192.168.1.121 on the local network now. Perfect! 

Let me know if you have any additional suggestions or need any additional information from me. 

Again, I appreciate your help on this!

**Comment by peacey** [comment]
It's very weird that your VPN IP is leading to the UDMP portal even though nothing is forwarded to the UDMP. I just tested port 80, 81, 443, and 32400 and they all worked for me port forwarding with purevpn. There shouldn't be anything extra to do on the UDMP. 

Do you have any custom firewall rules that could effect the communication? Do you have any firewall on the 192.168.1.121 server itself? Are you testing the port forwards from outside your network (not from within your LAN)?

Let's try to debug by checking if the traffic is arriving and being forwarded. Let's focus on one port first, port 81.

After you run the VPN, can you run this tcpdump on the UDMP? 

```sh
tcpdump -ni any port 81
```

After running the tcpdump, try to access the VPN IP on port 81 from **outside your network**. Try to go to http://VPN_IP:81 in your browser. Then check the tcpdump output and see if any packets arrived. Paste the output here if you received packets. 

Can you also paste the output of `ip route` and `iptables -t mangle -S` and `iptables -t nat -S` after running the VPN? 

Thank you,
Peacey

**Comment by smileyhogue** [comment]
Oh my lord.
I am so sorry for wasting your time after your first comment. I completely spaced and was definitely trying from my phone without turning off wifi.

Everything is working now! Thank you so much for all the help and thanks for the amazing project! Helped me get past carrier grade NAT!

**Comment by peacey** [comment]
Glad you got it working! Honestly was just happy it wasn't a bigger issue that required extensive debugging. So it all worked out!

One tip, sometimes if your UDM abruptly reboots from a power failure, PureVPN will give you another IP when it starts instead of your Dedicated IP (because it thinks the other IP is in use and it takes 5 minutes before you can use your dedicated IP again). You can add this piece of code to the bottom of your `vpn.conf` file so that the VPN keeps restarting until it gets the correct dedicated IP.

```sh
hooks_up() {
	WANTED_IP="172.109.212.66"
	if [ "${PLUTO_MY_SOURCEIP}" != "${WANTED_IP}" ]; then
		echo "ERROR: Got IP ${PLUTO_MY_SOURCEIP} but wanted ${WANTED_IP}. Shutting down VPN."
		ipsec down "${PLUTO_CONNECTION}" >/dev/null 2>&1
	fi
}
```

Just make sure to replace `WANTED_IP="172.109.212.66"` with the dedicated IP that's assigned to you.

**Comment by smileyhogue** [comment]
Oh, good to know! I just added that, thank you for the help! Everything working very well since  my last comment! 

Is there anywhere I can donate or anything?
