### ISSUE TITLE
can't execute 'openvpn': Permission denied

### ISSUE THREAD

**Issue by Xandir150** [peacey/split-vpn#44]
When I try execute 
`nohup openvpn --config .....`
or just 
`openvpn --config ....`

Have the msg: `can't execute 'openvpn': Permission denied`
UDM Pro 1.10

**What I do wrong?**

**Comment by peacey** [comment]
Hi @Xandir150,

openvpn comes pre-installed on the UDM and this script doesn't change it. So it's weird that you're having issues running openvpn, as it should work fine on stock. Did you do any modifications to the openvpn binary? You are running openvpn on the base OS, not unifi-os container right?

Can you please show me the output of these commands?

```sh
which openvpn
ls -lh /usr/sbin/openvpn
openvpn --version
```
Have you also tried to re-upgrade your firmware (not factory reset, just ubnt-upgrade to the same firmware so it reinstalls the base OS including openvpn)?

**Comment by peacey** [comment]
Hi,

This issue has become inactive so I'm closing it for now. If you try again and you're still having the same problem, please feel free to re-open it. 

Thanks!
