### ISSUE TITLE
Unable to get IPv6 working through OpenVPN

### ISSUE THREAD

**Issue by RomaDomor** [peacey/split-vpn#45]
So, my VDS server has IPv6 address and I want to use it for OpenVPN.
UDM Pro gets a IPv6 address from OpenVPN server, but when I try to ```curl -6 ifconfig.co``` from device in my LAN I get a curl error.
Device's ifconfig output:
```
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.8.42  netmask 255.255.255.0  broadcast 192.168.8.255
        inet6 fe80::d63d:7eff:febf:6fa  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::d63d:7eff:febf:6fa  prefixlen 64  scopeid 0x20<link>
```

So what is wrong?

### Here is my configuration:

**_server.conf (OpenVPN server)_**
```
proto udp

dev tun

ca ca.crt
cert server.crt
key server.key 

dh dh2048.pem

topology subnet

server 10.8.8.0 255.255.255.0

ifconfig-pool-persist /var/log/openvpn/ipp.txt

client-config-dir ccd

push "redirect-gateway def1 bypass-dhcp"

push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"

keepalive 10 120

tls-auth ta.key 0

cipher AES-256-CBC

user nobody
group nogroup

persist-key
persist-tun

status /var/log/openvpn/openvpn-status.log

verb 3

explicit-exit-notify 1

# IPv6 config
server-ipv6 2001:0db8:ee00:abcd::/64
tun-ipv6
push tun-ipv6
```

_**ccd/client (OpenVPN Server)**_
```
ifconfig-push 10.8.8.6 255.255.255.0
ifconfig-ipv6-push 2001:0db8:ee00:abcd::4
```

_**client.ovpn (UDM Pro)**_
```
client

dev tun

proto udp

remote IP 1194

resolv-retry infinite

nobind

user nobody
group nogroup

persist-key
persist-tun

remote-cert-tls server

cipher AES-256-CBC

verb 3

// Certificates go here...
```

_**vpn.conf (UDM Pro)**_ 
```
FORCED_SOURCE_INTERFACE=""
FORCED_SOURCE_IPV4="192.168.8.0/24"
FORCED_SOURCE_IPV6="fe80::b4e2:28ff:feb2:4ee/64"
FORCED_SOURCE_MAC=""

EXEMPT_SOURCE_IPV4=""
EXEMPT_SOURCE_IPV6=""
EXEMPT_SOURCE_MAC=""

EXEMPT_SOURCE_IPV4_PORT=""
EXEMPT_SOURCE_IPV6_PORT=""
EXEMPT_SOURCE_MAC_PORT=""

EXEMPT_DESTINATIONS_IPV4="192.168.1.0/24 192.168.8.0/24"
EXEMPT_DESTINATIONS_IPV6="fe80:0000:0000:0000:0000:0000:0000:0000/16"

PORT_FORWARDS_IPV4="tcp-80-192.168.8.42-80 tcp-443-192.168.8.42-443"
PORT_FORWARDS_IPV6=""

DNS_IPV4_IP="DHCP"
DNS_IPV4_PORT=53
DNS_IPV4_INTERFACE=""

DNS_IPV6_IP=""
DNS_IPV6_PORT=53
DNS_IPV6_INTERFACE=""

KILLSWITCH=0

REMOVE_KILLSWITCH_ON_EXIT=1

REMOVE_STARTUP_BLACKHOLES=1

ROUTE_TABLE=104
MARK=0x6
PREFIX="VPNUC_"
PREF=96
DEV=tun3
```

**Comment by peacey** [comment]
Hi @RomaDomor,

Does your UDMP network have IPv6 enabled under Settings -> Network -> Select Network -> IPv6? If IPv6 is disabled on the network, then your computer will not know how to route IPv6 packets because the UDMP will not tell it the IPv6 gateway address. You need to either set IPv6 to prefix delegation (if your ISP supports IPv6), or static (if your ISP does not have IPv6 support). 

Prefix delegation is straightforward if your ISP supports it, but for static you should set the IPv6 gateway/subnet to some ULA like fd62::1/64 (or any fdxx.. address) and enable DHCPv6. Then your computer should get an IPv6 address (either a global one like 2001:... if using prefix delegation, or fd62::... if using static)

Then after you confirm the computer got an IPv6 address, you should most likely force by the computer's MAC address instead because the IPv6 might change. Forcing by MAC address will force all IPv4 and IPv6 traffic from this mac address regardless of source IP, so it's much more convenient. 

Please check these and see how it goes.

**Comment by RomaDomor** [comment]
Still doesn't work:

`curl -6 ifconfig.co` times out

traceroute also times out on the first hop:
```
# traceroute -6 cloudflare-dns.com
traceroute to cloudflare-dns.com (2606:4700::6810:f9f9), 30 hops max, 80 byte packets
 1  fd08::1 (fd08::1)  0.260 ms  0.213 ms  0.243 ms^C
```

In UDM-Pro settings I have:
```
IPv6 Gateway Subnet: fd08::1/64
DHCPv6: enabled
DHCPv6 range: fd08::2 - fd08::7d1
``

Device got a local IPv6 address:
```
inet6 fd08::7c8  prefixlen 128  scopeid 0x0<global>
``

vpn.conf now has:
```
FORCED_SOURCE_IPV6="fd08::/64"
```

**Comment by RomaDomor** [comment]
And device is now also inaccessible from another VLAN, while I can still connect to another device in LAN I am trying to configure IPv6.
Strange...

**Comment by peacey** [comment]
@RomaDomor, for inter-vlan access, you need to add the LAN subnets you want access to EXEMPT_DESTINATIONS. Did you do that?

Are you able to ping the server's VPN IPv6 from your device? Have you enabled IPv6 forwarding on your VDS server?

**Comment by peacey** [comment]
I replicated your openvpn server config and I was able to ping/curl IPv6 addresses fine. Just some notes:

1. On you openvpn server, make sure you enabled IPv6 forwarding and added a masquerade NAT rule for your IPv6 Internet interface. For my linux system, I needed to run (replace enp67s0 with your WAN/router interface)

    ```sh
    sudo sysctl -w net.ipv6.conf.all.forwarding=1
    sudo ip6tables -t nat -A POSTROUTING -o enp67s0 -j MASQUERADE
    ```

2. Why are you using a 2001 global address for your VPN server's IPv6 pool? It is better to use a unique local address like fdxx... to avoid conflicts (this address isn't publicly routable anyways). In my case, I used fd22::/64. So my openvpn server had `server-ipv6 fd::/64` in the server config and `ifconfig-ipv6-push fd22::4` in the CCD for the client. 

3. You should also add a redirect-gateway for IPv6 to the openvpn server's config. Not necessary for the script but better it's there if you want that behaviour. 

    ```
    push "redirect-gateway ipv6 def1"
    ```

If you've done confirmed these (especially 1) and it still doesn't work, we can try some tcpdump debugging.

**Comment by RomaDomor** [comment]
I do have IPv6 forwarding configured. Here is the beginning of /etc/ufw/before6.rules:
```
# START OPENVPN RULES
# NAT table rules
*nat
:POSTROUTING ACCEPT [0:0]
# Allow traffic from OpenVPN client to eth0
-A POSTROUTING -s fd22::/64 -o eth0 -j MASQUERADE
COMMIT
# END OPENVPN RULES
```

I am able to ping OpenVPN server's address from device.
But when I try to ping `Cloudflare-dns.com` It still times out.


And talking about inter-vlan access, I do have exempt destinations configured:
```
EXEMPT_DESTINATIONS_IPV4="192.168.10.0/24 192.168.1.0/24 192.168.8.0/24 192.168.101.0/24"
EXEMPT_DESTINATIONS_IPV6="f000::/4"
```
But I still can't ping my device (192.168.8.42) in 192.168.8.0/24 subnet from 192.168.10.0/24 subnet. However I am able to ping another device (192.168.8.44) in that same subnet.

**Comment by RomaDomor** [comment]
Managed to get IPv6 working. It turns out VDS had IPv6 address linked to a different interface. Fixed before6.rules and it started working.

But the problem with inter-vlan access still persists.

**Comment by peacey** [comment]
Great you got IPv6 working. Let's fix the inter-VLAN now. 

EXEMPT_DESTINATIONS should be all that's needed. Did you make sure to restart the VPN script after adding your new configuration? 

First as a sanity check, you are able to ping a device on the 192.168.10.0/24 subnet from the 192.168.8.0/24 subnet when the VPN is turned off?

After you run the VPN, please show me the output of this command on the UDMP: 

```sh
iptables -t mangle -S
```
Also what about the 192.168.101.0/24 and 192.168.1.0/24 subnets you added as well. Are you able to ping those subnet from 192.168.8.0/24 with the VPN on?

**Comment by RomaDomor** [comment]
Got it working. The problem was in iptables. Most likely, during numerous modifications to vpn.conf, I faced multiple VPN crashes, that led to up-down.sh not executing correctly, therefore leaving iptables entries that were killing inter-vlan.
UDM Pro reboot fixed it all.

Thanks for the help

**Comment by peacey** [comment]
Glad it all worked out! If you have any more issues, please feel free to open another issue.

Have a nice day!
