### ISSUE TITLE
Force local traffic for specific port through VPN

### ISSUE THREAD

**Issue by clarkewing** [peacey/split-vpn#48]
Hi there!

Thanks for the awesome work on this package, I'm using it to set up VoIP (UniFi Talk) through a CG-NAT connection (Starlink) and it's almost working perfectly.

I've managed to get port forwarding working over a Wireguard VPN so inbound traffic works great.

However, I'm struggling a bit more with getting outbound traffic to route through the VPN. Essentially what I'm trying to do is force traffic from/to SIP and signaling ports (5060, 5061, and 6767) to go through the VPN, but leave media traffic intact.

I'm using the following rule:
```
FORCED_SOURCE_IPV4_PORT="both-localhost-5060,5061,6767 both-192.168.1.1-5060,5061,6767 both-10.0.0.0/8-5060,5061,6767"
```

Should I be doing something differently?

Also, I'd be happy to sponsor the awesome work you've been doing @peacey, are you planning on setting up GitHub Sponsors?

**Comment by clarkewing** [comment]
Thanks for getting back to me so quickly.

To be honest with you, I myself am still trying to figure out how UniFi Talk functions from a network standpoint. My understanding is that phones make requests to the UDMP which then in turn handles SIP communication with the SIP trunk server over ports 5060, 5061, and 6767. I added multiple IP sets to cover all my bases (`192.168.1.1` is the UDMP and `10.0.0.0/8` is the subnet housing the phones).

For port forwarding, I'm using the following:
```
PORT_FORWARDS_IPV4="both-5060-192.168.1.1-5060 both-5061-192.168.1.1-5061 both-6767-192.168.1.1-6767"
```

My understanding is the following:
When making an outbound call, the phone sends packets over port 5060 or 5061 to the UDMP which then sends packets to the SIP server over port 6767 (called the static signaling port).
When receiving an inbound call, the SIP server sends packets over port 6767 to the UDMP which then sends packets over port 5060 or 5061 to the phone.
The packets over these ports are purely used for signaling (messages which allow the phone/UDMP/SIP server to initiate calls, hang up, etc), other ports are used for actual voice media (and I want to keep those out of the VPN for better latency).

I believe that forcing local traffic over the SIP ports through the VPN should resolve the issues I am experiencing.

Let me know if I can clarify in any way!

**Comment by clarkewing** [comment]
Hi @peacey,

My apologies for taking so long to get back to you. I got caught up in other projects with higher priority.

Those commands work great, I actually have to use `--sport` as 6767 is a source port but that's perfect. Our outbound calls are working great now!

As for the media ports, we _could_ forward these as well, to have everything go through a common IP, but this poses the issue of introducing more latency, as the RTP media traffic would have to hop through the VPN in addition to the Starlink connection. For the best VoIP experience, we chose to go the route of using Starlink CG-NAT IP for RTP because of that and it is working without issue thanks to symmetric RTP.

**Comment by clarkewing** [comment]
As for inbound calling, I was able to isolate the issue which causes calls to drop after 30 seconds. However, in order to resolve it, we'd have to be able to a) modify UniFi Talk's underlying FreeSWITCH config (it's hidden away and Ubiquity support has been no help) ; or b) intercept SIP messages and replace the Starlink IP in the body with the VPN IP before transmission (which I don't believe is even possible).

For now, we're going the route of just calling people back if the call exceeds 30 seconds (and looking forward to dedicated IPv6 on Starlink).

**Comment by peacey** [comment]
Thanks for the update @clarkewing. Glad you could get most of it to work. I'll be closing this issue now since the original problem has been fixed. But feel free to re-open it if you have any more questions!

Have a nice day!
