### ISSUE TITLE
bc not found - issue on UDM Pro SE

### ISSUE THREAD

**Issue by nigels0** [peacey/split-vpn#51]
Hi,

I successfully installed on a UDMP, but trying the same on the UDMPSE, I'm not finding bc.

The version of the OS is 
```
uname -a
Linux Olla-UDM-Pro 4.19.152-ui-alpine #4.19.152 SMP Wed Aug 4 12:51:31 CST 2021 aarch64 GNU/Linux
```

note:
```
/usr/bin/bc -h
-bash: /usr/bin/bc: No such file or `directory`

```

I fixed it by downloading the command:

`sudo apt-get install bc`

**Comment by drallgood** [comment]
I had the same issue on a brand new UDM. Solution: upgrade to the latest version of the OS.
