### ISSUE TITLE
update-resolv-conf missing

### ISSUE THREAD

**Issue by traktuner** [peacey/split-vpn#6]
Hello,
thank you for this wonderful script! I followed your instructions but at step 6 I get the following error:
Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
Options error: Please correct this error.
Use --help for more information.

I use ProtonVPN, and the .ovpn file includes these lines:
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf

My UDM-Pro is running on 1.9.0
Any idea how to fix this? 
Thank you very much in advance! :)

EDIT:
Got it working!
removed those lines from the config file, now it's working!

**Comment by brendandebeasi** [comment]
This can also be fixed by updating the path to update-resolv-conf. In my case Mullvad provided this, so I had to change the path to the file in the .conf and `chmod +x update-resolv-conf`

**Comment by peacey** [comment]
Hi @traktuner,

You can remove the up/down lines from the config since we set them directly in the OpenVPN command line to point to the split-vpn script. You shouldn't have the lines pointing to resolvconf since that's not even used.
