### ISSUE TITLE
UpDown Error: Invalid Gateway Address

### ISSUE THREAD

**Issue by everythingguy** [peacey/split-vpn#61]
I have been using split-vpn on my UDM Pro for almost a year now and it has been working fine until recently. The VPN is no longer connecting on boot. I tried manually running the openvpn command and the same error occurs. My openvpn.log file looks like this. 

```
2021-12-27 15:14:23 DEPRECATED OPTION: --cipher set to 'aes-256-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-256-cbc' to --data-ciphers or change --cipher 'aes-256-cbc' to --data-ciphers-fallback 'aes-256-cbc' to silence this warning.     
2021-12-27 15:14:23 OpenVPN 2.5.2 aarch64-buildroot-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 21 2021
2021-12-27 15:14:23 library versions: OpenSSL 1.0.2u  20 Dec 2019, LZO 2.10
2021-12-27 15:14:23 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-12-27 15:14:23 CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
<REDACTED>
-----END X509 CRL-----

2021-12-27 15:14:23 RESOLVE: Cannot resolve host address: us-newyorkcity.privacy.network:1197 (Temporary failure in name resolution)
2021-12-27 15:14:23 RESOLVE: Cannot resolve host address: us-newyorkcity.privacy.network:1197 (Temporary failure in name resolution)
2021-12-27 15:14:23 Could not determine IPv4/IPv6 protocol
2021-12-27 15:14:23 SIGUSR1[soft,init_instance] received, process restarting
2021-12-27 15:14:28 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-12-27 15:14:28 TCP/UDP: Preserving recently used remote address: [AF_INET]138.199.13.132:1197
2021-12-27 15:14:28 UDP link local: (not bound)
2021-12-27 15:14:28 UDP link remote: [AF_INET]138.199.13.132:1197
2021-12-27 15:14:28 [newyork419] Peer Connection Initiated with [AF_INET]138.199.13.132:1197
2021-12-27 15:14:28 sitnl_send: rtnl: generic error (-101): Network is unreachable
2021-12-27 15:14:28 TUN/TAP device tun0 opened
2021-12-27 15:14:28 net_iface_mtu_set: mtu 1500 for tun0
2021-12-27 15:14:28 net_iface_up: set tun0 up
2021-12-27 15:14:28 net_addr_v4_add: 10.1.110.116/24 dev tun0
2021-12-27 15:14:28 /mnt/data/split-vpn/vpn/updown.sh tun0 1500 1553 10.1.110.116 255.255.255.0 init
Mon Dec 27 15:14:28 2021 split-vpn up: Loading configuration from /mnt/data/split-vpn/openvpn/pia/vpn.conf.
Error: Invalid gateway address.
2021-12-27 15:14:29 WARNING: Failed running command (--up/--down): external program exited with error status: 2
2021-12-27 15:14:29 Exiting due to fatal error
```

**Comment by peacey** [comment]
Hi @everythingguy,

Can I see your vpn.conf? Also, can you update to the latest version and try again (if you haven't updated yet)?

Thanks.

**Comment by everythingguy** [comment]
Just updated today to try to resolve the issue. 
I followed my full write-up that I created back in June when I first got it working.
That can be found here:
https://blog.kevingyorick.com/2021/06/12/unifi-dream-machine-pro-network-wide-openvpn-client/
To "update" I redid the steps within the split-vpn section. 

Thanks for the help.

here is my conf

### SPLIT VPN OPTIONS ###
# Enter multiple entries separated by spaces.
# Do not enter square brackets around the entries.

# Force these sources through the VPN.
# Format: [brX] for interface. [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
FORCED_SOURCE_INTERFACE="br90 br30"
FORCED_SOURCE_IPV4=""
FORCED_SOURCE_IPV6=""
FORCED_SOURCE_MAC=""

# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
# Maximum 15 ports per entry.
FORCED_SOURCE_IPV4_PORT=""
FORCED_SOURCE_IPV6_PORT=""
FORCED_SOURCE_MAC_PORT=""

# Force these destinations through the VPN. 
# These destinations will be forced regardless of source.
# Format: [IP/nn]
FORCED_DESTINATIONS_IPV4=""
FORCED_DESTINATIONS_IPV6=""

# Force local UDM traffic going out of these WAN interfaces to go through the
# VPN instead for both IPv4 and IPv6 traffic.
# This does not include routed traffic, only local traffic generated by the UDM.
# Do not enable this unless you want to force UDM local traffic through the VPN.
# For UDM-Pro, set to "eth8" for WAN1/Ethernet port, or "eth9" for WAN2/SFP+ port, 
# or "eth8 eth9" for both. For UDM Base, set to "eth1" for the WAN port.
# This option might cause unintended problems, so disable it if you encounter any issues.
FORCED_LOCAL_INTERFACE=""

# Exempt these sources from the VPN. 
# Format: [IP/nn] for IP. [xx:xx:xx:xx:xx:xx] for mac.
EXEMPT_SOURCE_IPV4=""
EXEMPT_SOURCE_IPV6=""
EXEMPT_SOURCE_MAC=""

# Format: [tcp/udp/both]-[IP/MAC Source]-[port1,port2:port3,port4,...]
# Maximum 15 ports per entry.
EXEMPT_SOURCE_IPV4_PORT=""
EXEMPT_SOURCE_IPV6_PORT=""
EXEMPT_SOURCE_MAC_PORT=""

# Exempt these destinations from the VPN. 
# Format: [IP/nn]
EXEMPT_DESTINATIONS_IPV4="10.0.0.0/8"
EXEMPT_DESTINATIONS_IPV6=""

# Force/exempt these IP sets
# IP sets need to be created before this script is run or the script will error.
# IP sets can be updated externally and will be matched dynamically.
# Each IP set entry consists of the IP set name and whether to match on source
# or destination. src/dst needs to be specified for each IP set field.
#
# Enable NAT hairpin by exempting UBIOS_ADDRv4_ethX:dst for IPv4 or
# UBIOS_ADDRv6_ethX:dst for IPv6 (where X = 8 for RJ45, or 9 for SFP+ WAN).
# For IPv6 prefix delegation, exempt UBIOS_ADDRv6_brX, where X = VLAN number (0 = LAN).
#
# To allow communication with your VLAN subnets without hardcoding the subnets,
# exempt the UBIOS_NETv4_brX:dst ipset for IPv4 or UBIOS_NETv6_brX:dst for IPv6.
#
# Format: [IPSet Name]:[src/dst,src/dst,...]
FORCED_IPSETS=""
EXEMPT_IPSETS=""

# VPN port forwards.
# Format: [tcp/udp/both]-[VPN Port]-[Forward IP]-[Forward Port]
PORT_FORWARDS_IPV4=""
PORT_FORWARDS_IPV6=""

# Redirect IPv4 and IPv6 DNS to these addresses for VPN-destined traffic.
# Note that many VPN providers redirect DNS going through their VPN network
# to their own DNS servers. Redirection to other IPs might not work on all providers,
# except for DNS redirects to a local address, or rejecting DNS traffic completely.
#
# IPV4 Format: [IP] to redirect to IP, "DHCP" if using OpenVPN or OpenConnect to obtain
# DNS from DHCP options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on
# other VPN types like wireguard/external.
#
# Example: Get DNS from DHCP
DNS_IPV4_IP="DHCP"
DNS_IPV4_PORT=53
# Set this to the interface (brX) the DNS is on if it is a local IP. Leave blank for
# non-local IPs. Local DNS redirects will not work without specifying the interface.
DNS_IPV4_INTERFACE=""

# IPV6 Format: [IP] to redirect to IP, or "REJECT" to reject IPv6 DNS traffic completely.
# IPV6 Format: [IP] to redirect to IP, "DHCP" if using OpenConnect to obtain DNS from DHCP
# options, or "REJECT" to reject all DNS traffic. "DHCP" is not supported on
# other VPN types.
DNS_IPV6_IP=""
DNS_IPV6_PORT=53
DNS_IPV6_INTERFACE=""

# Bypass masquerade (SNAT) for these source IPs. This option should only be used if your 
# VPN server is setup to know how to route the subnet you do not want to masquerade 
# (e.g.: the "iroute" option in OpenVPN).
# Set these options to ALL to disable masquerading completely.
# Format: [IP/nn] or "ALL"
BYPASS_MASQUERADE_IPV4=""
BYPASS_MASQUERADE_IPV6=""

# Enabling kill switch drops VPN-destined traffic that doesn't go through the VPN.
KILLSWITCH=0

# Enable this only if you are testing or you don't care about your real IP leaking
# when the vpn client restarts or exits.
REMOVE_KILLSWITCH_ON_EXIT=1

# Enable this if you added blackhole routes in the Unifi Settings to prevent Internet
# access at system startup before the VPN script runs. This option removes the blackhole 
# routes to restore Internet access after the killswitch has been enabled. 
# If you do not set this to 1, openvpn will not be able to connect at startup, and your 
# Internet access will never be enabled until you manually remove the blackhole routes. 
# Set this to 0 only if you did not add any blackhole routes.
REMOVE_STARTUP_BLACKHOLES=1

# Set the VPN provider.
# "openvpn" for OpenVPN (default), "openconnect" for OpenConnect, "external" for wireguard,
# or "nexthop" for an external VPN client.
VPN_PROVIDER="openvpn"

# If using "external" for VPN_PROVIDER, set this to the VPN endpoint IP so that the
# gateway route can be automatically added for the VPN endpoint.
# OpenVPN passes the VPN endpoint IP to the script and will override these values.
# These must be defined if using VPN_PROVIDER="nexthop".
VPN_ENDPOINT_IPV4=""
VPN_ENDPOINT_IPV6=""

# Set this to the route table that contains the gateway route, "auto", or "disabled".
# The Ubiquiti route table is "201" if you're using Ethernet, "202" for SFP+, and
# "203" for U-LTE.
# Default is "auto" which works with WAN failover and automatically changes the endpoint
# via gateway route when the WAN or gateway routes changes.
# Set to "disabled" if you are using the nexthop option to connect to a VPN on your LAN.
GATEWAY_TABLE="auto"

# Set the MSS clamping on packets going out the VPN tunnel. Usually, it is not needed to
# set this manually, but some VPN connections stall if the MSS clamping is not set correctly.
# Typical values range from 1240 to 1460, but it could be lower.
MSS_CLAMPING_IPV4=""
MSS_CLAMPING_IPV6=""

# Set this to the timer to use for the rule watcher (in seconds).
# The script will wake up every N seconds to re-add rules if they're deleted by
# the system, or change gateway routes if they changed. Default is 1 second.
WATCHER_TIMER=1

# Options for custom table and chains.
# These options need to be unique for each instance of openvpn if running multiple.
ROUTE_TABLE=101
MARK=0x9
PREFIX="VPN_"
PREF=99
DEV=tun0

# To execute commands when the VPN connects or disconnects, you can use the 
# callback functions hooks_pre_up, hooks_up, hooks_down, and 
# hooks_force_down. These functions will be invoked in response to VPN events 
# pre-up, up, down, and force-down respectively.
#
# For an example on using these hooks, please see vpn.conf.filled.sample.

**Comment by peacey** [comment]
Can you please modify `/mnt/data/split-vpn/vpn/updown.conf` and change the first uncommented line from `set -e` to `set -xe`? That will make the output verbose. Then start the VPN again and show me the openvpn.log.

**Comment by everythingguy** [comment]
2021-12-27 16:13:14 DEPRECATED OPTION: --cipher set to 'aes-256-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-256-cbc' 
to --data-ciphers or change --cipher 'aes-256-cbc' to --data-ciphers-fallback 'aes-256-cbc' to silence this warning.
2021-12-27 16:13:14 OpenVPN 2.5.2 aarch64-buildroot-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 21 2021    
2021-12-27 16:13:14 library versions: OpenSSL 1.0.2u  20 Dec 2019, LZO 
2.10
2021-12-27 16:13:14 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-12-27 16:13:14 CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
<REDACTED>
-----END X509 CRL-----

2021-12-27 16:13:14 TCP/UDP: Preserving recently used remote address: [AF_INET]138.199.13.141:1197
2021-12-27 16:13:14 UDP link local: (not bound)
2021-12-27 16:13:14 UDP link remote: [AF_INET]138.199.13.141:1197      
2021-12-27 16:13:14 [newyork419] Peer Connection Initiated with [AF_INET]138.199.13.141:1197
2021-12-27 16:13:14 sitnl_send: rtnl: generic error (-101): Network is 
unreachable
2021-12-27 16:13:14 TUN/TAP device tun0 opened
2021-12-27 16:13:14 net_iface_mtu_set: mtu 1500 for tun0
2021-12-27 16:13:14 net_iface_up: set tun0 up
2021-12-27 16:13:14 net_addr_v4_add: 10.10.110.86/24 dev tun0
2021-12-27 16:13:14 /mnt/data/split-vpn/vpn/updown.sh tun0 1500 1553 10.10.110.86 255.255.255.0 init
+ CONFIG_FILE=
+ '[' -z  ]
+ CONFIG_FILE=/mnt/data/split-vpn/openvpn/pia/vpn.conf
+ source ./vpn.conf
+ FORCED_SOURCE_INTERFACE='br90 br30'
+ FORCED_SOURCE_IPV4=
+ FORCED_SOURCE_IPV6=
+ FORCED_SOURCE_MAC=
+ FORCED_SOURCE_IPV4_PORT=
+ FORCED_SOURCE_IPV6_PORT=
+ FORCED_SOURCE_MAC_PORT=
+ FORCED_DESTINATIONS_IPV4=
+ FORCED_DESTINATIONS_IPV6=
+ FORCED_LOCAL_INTERFACE=
+ EXEMPT_SOURCE_IPV4=
+ EXEMPT_SOURCE_IPV6=
+ EXEMPT_SOURCE_MAC=
+ EXEMPT_SOURCE_IPV4_PORT=
+ EXEMPT_SOURCE_IPV6_PORT=
+ EXEMPT_SOURCE_MAC_PORT=
+ EXEMPT_DESTINATIONS_IPV4=10.0.0.0/8
+ EXEMPT_DESTINATIONS_IPV6=
+ FORCED_IPSETS=
+ EXEMPT_IPSETS=
+ PORT_FORWARDS_IPV4=
+ PORT_FORWARDS_IPV6=
+ DNS_IPV4_IP=DHCP
+ DNS_IPV4_PORT=53
+ DNS_IPV4_INTERFACE=
+ DNS_IPV6_IP=
+ DNS_IPV6_PORT=53
+ DNS_IPV6_INTERFACE=
+ BYPASS_MASQUERADE_IPV4=
+ BYPASS_MASQUERADE_IPV6=
+ KILLSWITCH=0
+ REMOVE_KILLSWITCH_ON_EXIT=1
+ REMOVE_STARTUP_BLACKHOLES=1
+ VPN_PROVIDER=openvpn
+ VPN_ENDPOINT_IPV4=
+ VPN_ENDPOINT_IPV6=
+ GATEWAY_TABLE=auto
+ MSS_CLAMPING_IPV4=
+ MSS_CLAMPING_IPV6=
+ WATCHER_TIMER=1
+ ROUTE_TABLE=101
+ MARK=0x9
+ PREFIX=VPN_
+ PREF=99
+ DEV=tun0
+ '[' -z openvpn ]
+ '[' -z 1 ]
+ '[' -z auto ]
+ '[' openvpn '=' openvpn -a -n tun0 ]
+ tun=tun0
+ '[' openvpn '=' openvpn -a -n up ]
+ state=up
+ '[' openvpn '=' openvpn -a -n 138.199.13.141 ]
+ VPN_ENDPOINT_IPV4=138.199.13.141
+ '[' openvpn '=' openvpn -a -n  ]
+ '[' openvpn '=' openconnect ]
+ nickname=
+ '[' openvpn '=' nexthop ]
+ dirname /mnt/data/split-vpn/vpn/updown.sh
+ iptables_script=/mnt/data/split-vpn/vpn/add-vpn-iptables-rules.sh    
+ ip_rule='fwmark 0x9 lookup 101 pref 99'
+ startup_blackholes='0.0.0.0/1 128.0.0.0/1 ::/1 8000::/1'
+ gateway_ipv4=undefined
+ gateway_ipv6=undefined
+ '[' -n /mnt/data/split-vpn/openvpn/pia/vpn.conf ]
+ date '+%a %b %d %H:%M:%S %Y'
+ echo 'Mon Dec 27 16:13:14 2021 split-vpn up: Loading configuration from /mnt/data/split-vpn/openvpn/pia/vpn.conf.'
Mon Dec 27 16:13:14 2021 split-vpn up: Loading configuration from /mnt/data/split-vpn/openvpn/pia/vpn.conf.
+ '[' up '=' force-down ]
+ '[' up '=' pre-up ]
+ '[' up '=' up ]
+ add_blackhole_routes
+ '['  '=' 1 ]
+ ip route replace blackhole default table 101
+ ip -6 route replace blackhole default table 101
+ '[' openvpn '=' openvpn -a init '!=' restart ]
+ add_openvpn_routes
+ delete_vpn_routes
+ ip route show table 101
+ grep -v blackhole
+ xargs '-I{}' sh -c 'ip route del {} table 101'
+ ip -6 route show table 101
+ xargs '-I{}' sh -c 'ip -6 route del {} table 101'
+ grep -v blackhole
+ '['  '!=' 1 ]
+ ip route replace 0.0.0.0/1 via 10.10.110.1 dev tun0 table 101        
+ ip route replace 128.0.0.0/1 via 10.10.110.1 dev tun0 table 101      
+ ip -6 route replace ::/1 dev tun0 table 101
+ ip -6 route replace 8000::/1 dev tun0 table 101
+ seq 1 1000
+ eval echo '$route_network_1'
+ echo
+ route_network_i=
+ eval echo '$route_gateway_1'
+ echo
+ route_gateway_i=
+ eval echo '$route_netmask_1'
+ echo
+ route_netmask_i=
+ '[' -z  ]
+ break
+ seq 1 1000
+ eval echo '$route_ipv6_network_1'
+ echo 2000::/3
+ route_ipv6_network_i=2000::/3
+ eval echo '$route_ipv6_gateway_1'
+ echo ::
+ route_ipv6_gateway_i=::
+ '[' -z 2000::/3 ]
+ '[' -n :: ]
+ ip -6 route replace 2000::/3 via :: dev tun0 table 101
Error: Invalid gateway address.
2021-12-27 16:13:14 WARNING: Failed running command (--up/--down): external program exited with error status: 2
2021-12-27 16:13:14 Exiting due to fatal error

**Comment by peacey** [comment]
Oh, PIA is reporting the $route_ipv6_gateway_* variable as :: instead of empty. Never seen that before. I've implemented a fix in the ipv6_gateway_fix branch. Can you update to it by running the following command and try again?

```sh
curl -LSsf https://raw.githubusercontent.com/peacey/split-vpn/main/vpn/install-split-vpn.sh | sed s/"main"/"ipv6_gateway_fix"/g | sh
```

**Comment by everythingguy** [comment]
That worked thank you!

**Comment by peacey** [comment]
Great. Have a great day and a happy new year!
