### ISSUE TITLE
strongswan-updown.sh: not found

### ISSUE THREAD

**Issue by smileyhogue** [peacey/split-vpn#65]
Hello,

After running split-van for a while after the initial bit of help, I had to reinstall and remake all of my files and I am running into a very weird issue. 

When I run run-vpn.sh, everything seems to work except for routing? Upon checking the podman log, I have found that it is somehow unable to fine Strongswan-updown.sh. I have triple checked and the path is correct, and the file is accessible. Any tips?

`Dec 31 17:01:40 14[CHD] <purevpn|43> updown: /bin/sh: 1: /etc/split-vpn/vpn/strongswan-updown.sh: not found`

<img width="665" alt="Screen Shot 2021-12-31 at 5 04 27 PM" src="https://user-images.githubusercontent.com/12057196/147841377-bcd02534-361c-43f4-a347-58d0f27bd1e1.png">

Quick edit incase it is useful
```
# ls -l strongswan*
-rwxr-xr-x    1 root     root          1315 Dec 29 13:31 strongswan-updown.sh
```

**Comment by peacey** [comment]
Hi @smileyhogue,

In your run script (probably at `/etc/split-vpn/strongswan/purevpn/run-vpn.sh`), did you change it to also use the correct location? With the moving of the paths, you need to change that script too. Please copy the new run-vpn.sh script from Step 5 of the StrongSwan instructions.

Sorry for the confusion! Tell me if it works.

**Comment by peacey** [comment]
Hi @smileyhogue,

Have you managed to get this working?

**Comment by peacey** [comment]
Closing this now, but if you have further issues, feel free to re-open.
