### ISSUE TITLE
Wireguard set MTU and/or MSS

### ISSUE THREAD

**Issue by ad5030** [peacey/split-vpn#67]
Hi Peacey,

Thank for your job. It works very fine, but I have somes  little pb ;-) 

I try to use it with openvpn (with ProtonVPN & IVPN) and Wireguard (with IVPN).

Everything is OK with OpenVPN, but I have a pb with IVPN over Wireguard .

I "think" that my wg0.conf and vpn.conf files are good, the WG VPN connection "seem" to be ok. For example Outlook mail, Teams, and some web url work (such as google, GitHub, fast.com ...) fine.
But some other  web url don't work. For exemple https://duckduckgo.com, https://mail.protonmail.com, https://protonvpn.com ...) don't work.

My wg0.conf : 
> [Interface]
> PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxx
> Address = xxx.xxx.xxx.xxx/32
> PostUp = sh /etc/split-vpn/vpn/updown.sh %i up
> PreDown = sh /etc/split-vpn/vpn/updown.sh %i down
> Table = 101
> 
> 
> [Peer]
> PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxx
> AllowedIPs = 0.0.0.0/1,128.0.0.0/1
> Endpoint = aaa.bbb.ccc.ddd:2049

wg:
> interface: wg0
>   public key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
>   private key: (hidden)
>   listening port: 32902
> 
> peer: xxxxxxxxxxxxxxxxxxxxxxxxxxx
>   endpoint: aaa.bbb.ccc.ddd:2049
>   allowed ips: 0.0.0.0/1, 128.0.0.0/1
>   latest handshake: 39 seconds ago
>   transfer: 21.54 MiB received, 15.21 MiB sent

I read (here https://keremerkan.net/posts/wireguard-mtu-fixes/) that WireGuard needs some extra setting. Either MSSFix or MSS or MTU. I don't sure that my pb is due to this.

Do you think this could be the reason?
And do you know how I can configure this key to set either on my UDM PROD SE, or on the wg0.conf file or maybe in the vpn.conf file?

Thank you in advance for your support

Best regard
Alexandre

**Comment by peacey** [comment]
Hi @ad5030,

Have you tried to set the MSS clamping via the MSS_CLAMPING_IPV4 or MSS_CLAMPING_IPV6 options in your vpn.conf file (options are found close to the bottom)?

**Comment by ad5030** [comment]
@peacey thank a lot 
With MSS_CLAMPING_IPV4="1380" in vpn.conf my IVPN over Wireguard work fine now.

**Comment by peacey** [comment]
No problem @ad5030! Happy you got it working :-) 

Have a great day!
