### ISSUE TITLE
Forced destination port option?

### ISSUE THREAD

**Issue by dadcoachengineer** [peacey/split-vpn#69]
Excellent project! I would love to make DNS queries a lil more private. Is there an option to tunnel traffic based on destination port?

Thank you!

Jason

**Comment by peacey** [comment]
Hi @jasonshearer,

For DNS specifically, you can use the option `DNS_IPV4_IP` (or `DNS_IPV6_IP`) to DNAT all port 53 DNS traffic from your forced clients to the specified IP (which goes through the VPN tunnel by default unless you change it with `DNS_IPV4_INTERFACE`). Do you need to do more than that?

If you do need to force a specific destination port, you can use the `CUSTOM_FORCED_RULES_*` option (see [Configuration Variables](https://github.com/peacey/split-vpn#configuration-variables)), which allows you to construct any matching criteria with iptables syntax. 

For example, to force port 53 destination traffic to go through the VPN regardless of source (even for unforced clients), you can add this anywhere in your `vpn.conf` (option doesn't exist in the default config, so you'll have to enter it manually):

```sh
CUSTOM_FORCED_RULES_IPV4="
    -p udp --dport 53
    -p tcp --dport 53
"
```

Note the opening and closing quotes. Each line is a new rule. If you want to restrict this rule only for forced clients, then also add `-m mark --mark ${MARK}` to each line in the option (but make sure you add this snippet after you define the MARK option).

Is that good or is there something more specific you want to accomplish?

**Comment by jasonshearer** [comment]
Thanks @peacey 

It looks like the custom forced rules option is working well. My internal DNS server is running in docker so there really isn't a great way to send all source requests from the server. Non-authoritative requests get forwarded to NextDNS with linked IP so I think I just need to add a quick curl command to my master run-vpn.sh script to set that linked IP to the VPN egress address.

Once again, coming from an enterprise networking background, this is a great add-on to the UDMP.

**Comment by peacey** [comment]
You're welcome, @dadcoachengineer (did you change your username? Lol). 

I still don't get why you can't just use the DNS_IPV4_IP DNAT option. I also have my pihole running on a docker container, and I can forward all DNS rqeuets to it perfectly fine like this:

```sh
DNS_IPV4_IP="192.168.6.3"
DNS_IPV4_PORT="53"
DNS_IPV4_INTERFACE="br12"
```

192.168.6.3 is my pihole and br12 is the VLAN interface it's on. You'll have to make sure to set your pihole/NextDNS on a completely different VLAN than all other devices (or you'll also need to add a masquerading rule and you'll lose source information). 

You can also have you custom rules to force the NextDNS server to lookup requests through the VPN. 

This isn't what you're trying to do? Just trying to understand better.

**Comment by dadcoachengineer** [comment]
Hmm....maybe we are doing the same thing just with different routing rules?

The flow I am trying to achieve is this:

[Internal LDAP DNS server] --> VPN --> Public NextDNS resolvers (45.90.xx.xx)

I primarily moved to NextDNS from and on-prem pihole server in order to provide content filtering for my kids when they are off-net.

I also had to comment out the following to keep from using my VPN provider's resolvers.

DNS_IPV4_IP="DHCP"
DNS_IPV4_PORT=53

Thoughts?

PS - I did change my username today to match my reddit handle :)

**Comment by peacey** [comment]
Actually after re-thinking this, adding the custom rules as you did might be the best way to force DNS traffic through the VPN. But you should also set the DNS_IPV4_IP variable to your local DNS server so that DNS traffic to other DNS servers will be DNATed to this local server.

> I also had to comment out the following to keep from using my VPN provider's resolvers.

Yes, `DNS_IPV4_IP="DHCP"` gets the DNS from your VPN provider and DNATs all traffic to there. 

So in my case, I used these settings (my local DNS is 10.0.5.3 which is on VLAN 4 = br4): 

```sh
DNS_IPV4_IP="10.0.5.3"
DNS_IPV4_PORT=53
DNS_IPV4_INTERFACE="br4"

CUSTOM_FORCED_RULES_IPV4="
    -p udp -s 10.0.5.3 --dport 53
    -p tcp -s 10.0.5.3 --dport 53
"
```

You also have to make that your DNS server is on a different VLAN than all other devices to DNAT traffic properly. It's better you add the `-s dns_ip` to the custom forced rules so that only traffic from this DNS server gets routed through the VPN.

Also, you're only doing this for forced clients right? The DNAT will only be applied to the clients/subnets you forced in the FORCED_* options.

**Comment by dadcoachengineer** [comment]
This is perfect. The other component I just found is that NextDNS has a resolver that installs on UnifiOS.

https://github.com/nextdns/nextdns/wiki/UnifiOS

Thank you for thinking all of this through with me :)

**Comment by peacey** [comment]
No problem, @dadcoachengineer. I am closing this issue now but if you have any more problems, feel free to re-open this issue or start a new one!

Have a great day.
