### ISSUE TITLE
Chipher is deprecated

### ISSUE THREAD

**Issue by oranheim** [peacey/split-vpn#78]
During startup openvpn reports:

```
2022-02-12 19:27:19 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
```

**Comment by peacey** [comment]
Hi @oranheim,

Is this warning causing any issues in your connection, or everything is working fine? It's just a warning about deprecated ciphers, which is the responsibility of the server, not the client or the split-vpn script. We can't really do anything about that. But if it's not affecting your connection, then it's not really an issue right now. 

So is everything working even with this warning?

**Comment by peacey** [comment]
FYI, you can also add `--data-ciphers-fallback AES-256-CBC` to the OpenVPN command line to silence that error as it explains.

**Comment by oranheim** [comment]
Hi @peacey!

Ok, understand. My connection is working fine! I added the fallback options and it silenced the deprecation warning.

Thank you for making the split-vpn! :)

**Comment by oranheim** [comment]
Fixed.
