### ISSUE TITLE
rm: '/etc/split-vpn' is a directory

### ISSUE THREAD

**Issue by lowrisk75** [peacey/split-vpn#79]
I'm probably doing something wrong 

the file seems here 
```
# cd /etc/split-vpn
# ls
split-vpn  wireguard
```

I have UDM / UDMPro Boot Script but I'm not sure what to do next.

if I run the install script (/mnt/data/split-vpn/vpn/setup-split-vpn.sh) It's doesn't seems to work 

```
# /mnt/data/split-vpn/vpn/setup-split-vpn.sh
rm: '/etc/split-vpn' is a directory
```

I also have an error creating the config 

```
# /mnt/data/split-vpn/vpn/setup-split-vpn.sh
rm: '/etc/split-vpn' is a directory
# mkdir -p /etc/split-vpn/wireguard/mullvad
# cd /etc/split-vpn/wireguard/mullvad
# cp /etc/split-vpn/vpn/vpn.conf.sample /etc/split-vpn/wireguard/mullvad/vpn.conf
cp: can't stat '/etc/split-vpn/vpn/vpn.conf.sample': No such file or directory
# 
```

(/etc/split-vpn/ > split-vpn  wireguard -- /etc/split-vpn/split-vpn/vpn
-- vim wg0.conf > empty I suppose  vim vpn.conf instead

**Comment by peacey** [comment]
Hi @lowrisk75,

You must have created /etc/split-vpn before linking it with the script first. It should only be a symbolic link. 

Just delete the folder yourself then re-link split-vpn, which will create the /etc/split-vpn link.

```sh
rm -rf /etc/split-vpn
/mnt/data/split-vpn/vpn/setup-split-vpn.sh
```

Then it should be good to go. If you don't use a boot script, make sure you always run the setup-split-vpn.sh first when you boot. The boot script takes care of that automatically if you do use one.
