### ISSUE TITLE
Killswitch with multiple tun devices.

### ISSUE THREAD

**Issue by r3claim** [peacey/split-vpn#8]
Hi peacey,

Thanks for your work! I am using the UDM-Pro (FW. 1.9.2) with internet connection over PPoE.
When i use your script with only a single VPN-Tunnel on tun0 it works fine.
However, I want to route various clients to different VPN servers.
At the moment i am using 2 NordVPN Servers, one at tun101 and one at tun102.

With this configuration the clients aren´t able to connect to the internet (killswitch is turned on)
I think there is a issue with your killswitch rules.

With iptables -S i get:
````
-A VPN_CH_KILLSWITCH ! -o tun0 -m mark --mark 0x8 -j REJECT --reject-with icmp-port-unreachable
-A VPN_CH_KILLSWITCH ! -o tun102 -m mark --mark 0x8 -j REJECT --reject-with icmp-port-unreachable
-A VPN_GN_KILLSWITCH ! -o tun0 -m mark --mark 0x9 -j REJECT --reject-with icmp-port-unreachable
-A VPN_GN_KILLSWITCH ! -o tun101 -m mark --mark 0x9 -j REJECT --reject-with icmp-port-unreachable
````
The tun interfaces with route -n:
````
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.8.1.0        0.0.0.0         255.255.255.0   U     0      0        0 tun101
10.8.3.0        0.0.0.0         255.255.255.0   U     0      0        0 tun102
````
As you can see there is some "-o tun0" but i don´t have a running tunnel on tun0.

Please let me know if you need other information.

Thanks in advance!

**Comment by peacey** [comment]
Hi @r3claim,

When you use the killswitch, the rules are not removed after you exit OpenVPN. I think those rules with tun0 were added when you ran the script with tun0 then you changed it to the other tun devices. 

Can you stop the VPN, then run

```sh
iptables -t mangle -F
ip6tables -t mangle -F```

Then start the VPN with your new configuration and see if the tun0 entries are still there, and if connection doesn't work.

**Comment by r3claim** [comment]
I followed your instructions, additionally i also have reboot the UDM.
The 4 Killswitch rules appears after running the start script and the clients still can not connect to the Internet.

Thanks!

**Comment by peacey** [comment]
Thank you for trying. Can you show me your boot script that runs the VPNs?

**Comment by r3claim** [comment]
Sure,
````
#!/bin/sh

# Load configuration and run openvpn for guest network
cd /mnt/data/openvpn/nordvpn_gaeste
source ./vpn.conf
/mnt/data/openvpn/updown.sh ${DEV} pre-up &> pre-up.log
nohup openvpn --config nordvpn_ge.ovpn \
              --route-noexec \
              --up /mnt/data/openvpn/updown.sh \
              --down /mnt/data/openvpn/updown.sh \
              --dev-type tun --dev ${DEV} \
              --script-security 2 \
              --auth-user-pass login.txt \
              --ping-restart 15 \
              --mute-replay-warnings &> openvpn.log &

# Load configuration and run openvpn for CH network
cd /mnt/data/openvpn/nordvpn_ch
source ./vpn.conf
/mnt/data/openvpn/updown.sh ${DEV} pre-up &> pre-up.log
nohup openvpn --config nordvpn_ch.ovpn \
              --route-noexec \
              --up /mnt/data/openvpn/updown.sh \
              --down /mnt/data/openvpn/updown.sh \
              --dev-type tun --dev ${DEV} \
              --script-security 2 \
              --auth-user-pass login.txt \
              --ping-restart 15 \
              --mute-replay-warnings &> openvpn.log &
````

**Comment by peacey** [comment]
Thank you. I think I figured out my mistake in the script. Can you update your script to the preup-fix branch using these commands?

```sh
cd /mnt/data
mkdir /mnt/data/openvpn
curl -L https://github.com/peacey/split-vpn/archive/preup-fix.zip | unzip - "*/openvpn/*" -o -j -d openvpn && chmod +x openvpn/*.sh
```

Then please try your VPNs again and see if the problem is still there.

**Comment by r3claim** [comment]
I did a quick Test and it seems to work with this Version.

Thanks again for your Work!

**Comment by peacey** [comment]
I'm glad the fix worked! Hopefully you don't have any more issues. 

Have a nice day!
