### ISSUE TITLE
Using WireGuard with NordVPN

### ISSUE THREAD

**Issue by oranheim** [peacey/split-vpn#82]
Are there any examples on how to configure WireGuard with NordVPN?

**Comment by peacey** [comment]
Hi @oranheim,

Unlike other wireguard VPN providers, NordVPN doesn't just give you the wireguard configuration file. Instead, they generate it internally in their app and use it to connect via wireguard, but they never let you export it. So they make it a bit difficult. 

It is possible however to extract the information needed to make a wireguard configuration file for NordVPN. Basically, you just need to download the NordVPN app on a Linux system and use it to connect via wireguard, then use `wg showconf nordlynx` to extract the Endpoint and Private & Public keys, and use `ifconfig nordlynx` to extract the Address. Here's a couple of tutorials that have more details ([1](https://gist.github.com/bluewalk/7b3db071c488c82c604baf76a42eaad3), [2](https://forum.openwrt.org/t/instruction-config-nordvpn-wireguard-nordlynx-on-openwrt/89976)).

Once you have a working wireguard configuration, you can just follow the instructions for split-vpn normally. I would test the wireguard configuration on your computer first before trying with split-vpn. 

Also, one caveat I read is that NordVPN uses the same private key for every session and doesn't let you generate multiple ones, so it's basically impossible to have multiple sessions. You can only use one device at a time with their wireguard. In this case, the router is the device, so you can still force multiple clients through the tunnel of course.

**Comment by oranheim** [comment]
Thank you @peacey :) 

This was very helpful information. Does it mean that `ipsets` would work with WineGaurd too? It is very convenient to force domains instead of ips.

**Comment by peacey** [comment]
Yes thats right, everything including ipsets will work fine.

**Comment by oranheim** [comment]
Awesome!
