### ISSUE TITLE
Remote VPN is inaccessible when using split-vpn and ipsets

### ISSUE THREAD

**Issue by oranheim** [peacey/split-vpn#83]
I'm using ipsets with forced domains through split-vpn (using openvpn/nordvpn). I'm also using RemoteVPN to access my private network remotely and my private network is inaccessible when I'm connecting from my Mac or iPhone.

UDM base with UniFi OS version is 1.11.0 and Network 7.0.23.

1) If I disable split-vpn + ipsets and reboots, my RemoteVPN works perfect.

2) If I connect to RemoteVPN while split-vpn is disabled (!) and then re-enable split-vpn + ipsets while keeping my connection persistent, my private network remains accessible. If I disconnect my session and re-connect again, no resources are accessible.

3) If I reboot with split-vpn/ispsets enabled and try to connect, the network is inaccessible.

My config:

ipsets -> VPN_domains.conf -> FORCED_DOMAINS is configured

split-vpn -> vpn.conf:

FORCED_IPSETS="VPN_FORCED:dst"                                                           
EXEMPT_IPSETS="VPN_EXEMPT:dst"
DNS_IPV4_IP="192.168.1.1" 
ROUTE_TABLE=101                                                                     
MARK=0x9                                                                                
PREFIX="VPN_"                                                                              
PREF=99                                                                           
DEV=tun0 

Is there something I am missing in my configuration @peacey?

**Comment by peacey** [comment]
Hi @oranheim,

I'm not familiar with RemoteVPN and couldn't find it from a quick Google search. Can you link me to the software? 

Can you also tell me where you have RemoteVPN setup? On which computer, and whether it's on a VPN-forced network or not. 

Thanks!

**Comment by oranheim** [comment]
Remote VPN is a standard feature in UniFi OS Network App. In the legacy UI you'll find it under Create Network. In the new UniFi OS it is found in UDM Network App under "VPN"-menu. It creates a "Remote VPN" that allows you to connect your device to your private network; as opposed to Site-to-Site Network.

https://help.ui.com/hc/en-us/articles/115005445768-UniFi-USG-UDM-Configuring-L2TP-Remote-Access-VPN

**Comment by peacey** [comment]
Oh sorry @oranheim, I thought RemoteVPN was some app. I see what you mean now.

I will set up a remote VPN on my end and test what happens. 

In the meantime, can you try to change the MARK? Bring down the tunnel first, change the MARK in vpn.conf to `MARK=0x999`, then run the script again? I am wondering if 0x9 mark is being used by the remote VPN and causing issues.

**Comment by oranheim** [comment]
Changed to `MARK=0x999` but it didn't fix the rpoblem. 

After disabling _ipsets_, I was able to connect using _openvpn_ and my private network was working. I think the issue has something to do with _ipsets_.

Here is my log after I enabled _ipsets_:

```
Feb 23 09:00:29 ubnt daemon.info dnsmasq[15468]: exiting on receipt of SIGTERM
Feb 23 09:00:29 ubnt user.info ubios-udapi-server: ubios-udapi-server: Got process exit event for process dnsmasq
Feb 23 09:00:29 ubnt user.info ubios-udapi-server: ubios-udapi-server: Watchdog is restarting process dnsmasq
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: started, version 2.85 cachesize 10000
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: compile time options: IPv6 GNU-getopt DBus no-UBus no-i18n no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile
Feb 23 09:00:29 ubnt daemon.warn dnsmasq[17223]: warning: interface dnsfilter does not currently exist
Feb 23 09:00:29 ubnt daemon.info dnsmasq-dhcp[17223]: DHCP, IP range 192.168.7.6 -- 192.168.7.254, lease time 1d
Feb 23 09:00:29 ubnt daemon.info dnsmasq-dhcp[17223]: DHCP, IP range 192.168.20.6 -- 192.168.20.254, lease time 1d
Feb 23 09:00:29 ubnt daemon.info dnsmasq-dhcp[17223]: DHCP, IP range 192.168.1.6 -- 192.168.1.254, lease time 1d
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: reading /etc/resolv.dnsmasq
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: using nameserver 62.63.0.10#53
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: using nameserver 62.63.63.10#53
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: using nameserver 1.1.1.1#53
Feb 23 09:00:29 ubnt daemon.info dnsmasq[17223]: cleared cache
```
 
Looks like _ipsets_ restarts `dnsqmasq` processes.

**Comment by peacey** [comment]
So I tested this on my end @oranheim, but wasn't able to reproduce the issue. For me, split-vpn with ipsets works fine with the remote VPN active, and I am able to access resources on my internal network whether I connect to the remote VPN before or after I run split-vpn. Are you testing the remote VPN from outside your network?

> Looks like ipsets restarts dnsmasq processes.

Yes, that's expected behaviour. The ipset script adds an extra dnsmasq configuration file, so dnsmasq has to be reloaded. The ipset configuration shouldn't affect any DNS settings. In any case, DNS shouldn't impact ability to access internal resources, so it wouldn't be related to dnsmasq. 

> After disabling ipsets, I was able to connect using openvpn and my private network was working.

How did you disable ipsets? You just removed the ipset from FORCED_IPSETS in vpn.conf?

Can you re-enable that option, and test with an empty FORCED_DOMAINS and EXEMPT_DOMAINS for your VPN_domains.conf? 

When you test, how are you testing? Did you try to ping an internal resource by IP?

**Comment by oranheim** [comment]
> So I tested this on my end @oranheim, but wasn't able to reproduce the issue. For me, split-vpn with ipsets works fine with the remote VPN active, and I am able to access resources on my internal network whether I connect to the remote VPN before or after I run split-vpn. Are you testing the remote VPN from outside your network?

Yes. I am testing outside of my own network using my iPhone.

> > Looks like ipsets restarts dnsmasq processes.
> 
> Yes, that's expected behaviour. The ipset script adds an extra dnsmasq configuration file, so dnsmasq has to be reloaded. The ipset configuration shouldn't affect any DNS settings. In any case, DNS shouldn't impact ability to access internal resources, so it wouldn't be related to dnsmasq.

Ok.

> > After disabling ipsets, I was able to connect using openvpn and my private network was working.
> 
> How did you disable ipsets? You just removed the ipset from FORCED_IPSETS in vpn.conf?

My `VPN_domains.conf` contains:

```
FORCED_DOMAINS="
whatismyip.com
"

# Removed the example exempt domains
EXEMPT_DOMAINS="
"
```

> Can you re-enable that option, and test with an empty FORCED_DOMAINS and EXEMPT_DOMAINS for your VPN_domains.conf?
> 
> When you test, how are you testing? Did you try to ping an internal resource by IP?

I remove the `/mnt/data/on_boot.d/99-run-vpn.sh`, reboot my UDM. After that I start split-vpn manually. If I omit the `add-dnsmasq-ipset.sh` and only run `run-vpn.sh` it works. As soon as I start the `add-dnsmasq-ipset.sh` before `run-vpn.sh`, it doesn't work.

**Comment by peacey** [comment]
Hi @oranheim,

Sorry for the late reply. I have tried again but haven't been able to reproduce the same problem. It works for me with the script. 

UDM 1.11.4 was just released, can you update to that version and see if it helps? Not expecting it to help but just covering all bases. 

If it still doesn't work, we can try to debug it with some tcpdumps to try and see where packets are leaving from and if you are getting replies.

**Comment by oranheim** [comment]
Hii @peacey! Sorry for not responding earlier. I'm a bit busy at the moment, so I get back to you. Cheers, Ove

**Comment by Leempi** [comment]
I seem to be having this issue as well. 

Can I help testing in some way?

UniFi OS UDM Pro 1.11.4
Network 7.0.25

**Comment by peacey** [comment]
Hi @Leempi,

Can you describe your problem more? Also, what MARK are you using in your vpn.conf?

**Comment by peacey** [comment]
@Leempi,

Can you try a MARK of 0x169 instead? 0x9 was found to contlict with features UDM uses internally. 

Also you said USG Pro, but did you mean UDM Pro? This project is for the UDM/UXG/UDR, not USG.

**Comment by peacey** [comment]
Hi @oranheim,

This issue has become stale so I'm closing it. Feel free to re-open if you are still having issues!
