### ISSUE TITLE
Error: mtu less than device minimum

### ISSUE THREAD

**Issue by shaft8472** [peacey/split-vpn#84]
Hello,

I'm trying to setup a split-vpn connection and in the process of configuring for the WireGuard (kernel module). 
Am trying to test it by executing: wg-quick up ./wg0.conf
```
# wg-quick up ./wg0.conf
Warning: `/mnt/data/split-vpn/wireguard/mullvad/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.67.18.229/32 dev wg0
[#] ip -6 address add fc00:bbbb:bbbb:bb01::4:12e4/128 dev wg0
[#] ip link set mtu 1420 up dev wg0
Error: mtu less than device minimum.
[#] ip link delete dev wg0
```

Maybe it has something to do with my WireGuard kernel module:
```
# cd /mnt/data/wireguard
# chmod +x setup_wireguard.sh
# ./setup_wireguard.sh
loading wireguard...
Unsupported Kernel version 4.19.152-edge3
```

Perhaps I don't entirely understand the process. I've installed the custom kernel and want to run WireGuard via de Kernel module. (https://github.com/tusc/wireguard-kmod) As far as I can tell 4.19.152-edge3 is the latest custom Kernel that supports WireGuard this way. Then... why is it giving me problems?

**Comment by shaft8472** [comment]
Thank you, I suspected as much. I am however running a custom -edge kernel now which has in-kernel WireGuard support. I'm not sure how to proceed at the moment to get WireGuard running or what to install.

**Comment by peacey** [comment]
Well, it seems like an issue with how wireguard was compiled for your kernel. Are you able to re-compile the -edge kernel and make changes to it like compiling the latest wireguard for it yourself? Unfortunately, debugging and compiling the wireguard kernel module for a custom kernel is outside the scope of this project, so I can't really help you with that... If you're not familiar with the process, I would switch back to the official kernel and just use that. 

Why are you using the custom kernel? Do you need to use it or can you switch back to official kernel? The official kernel has wireguard built-in since UDM 1.11.0 anyways.

**Comment by shaft8472** [comment]
Sorry, I was a bit busy with other things. I have switched back to the official kernel. My goal was/is to have a split VPN running wireguard to one client and maximize throughput.

**Comment by shaft8472** [comment]
I understand that in the latest firmware wireguard is already present.

If I `modprobe wireguard` nothing happens, that's good.

`ip link add dev wg0 type wireguard`
&
`ip link del wg0` Also works, they give no errors.

I've created wg0.conf in `/etc/wireguard/wg0.conf`
Now I need to start it. `wg-quick up ./wg0.conf` will not work, because wg-quick is not present.
wg gives back: 

```
# wg up ./wg0.conf
Invalid subcommand: `up'
Usage: wg <cmd> [<args>]

Available subcommands:
  show: Shows the current configuration and device information
  showconf: Shows the current configuration of a given WireGuard interface, for use with `setconf'
  set: Change the current configuration, add peers, remove peers, or change peers
  setconf: Applies a configuration file to a WireGuard interface
  addconf: Appends a configuration file to a WireGuard interface
  syncconf: Synchronizes a configuration file to a WireGuard interface
  genkey: Generates a new private key and writes it to stdout
  genpsk: Generates a new preshared key and writes it to stdout
  pubkey: Reads a private key from stdin and writes a public key to stdout
```

I'm wondering how to use the built in Wireguardwith split-vpn, can you help me?

**Comment by peacey** [comment]
Hey @shaft8472,

The kernel module is included in the latest firmware, but the wireguard tools are NOT included. You will still need to install wireguard-kmod and run the setup_wireguard.sh script from that package. It will load the built-in module (by default) and link the tools (wg-quick, wg) so you can use them.
