### ISSUE TITLE
No upload

### ISSUE THREAD

**Issue by tomganleylee** [peacey/split-vpn#87]
I dont think this is a issue with split-vpn more of an issue with myself.

I have setup a wireguard server on a VPS and it appears to all work fine ( when i use wireguard client on my computer for example).

I set up split-vpn on my UDM PRO following the instructions and it appears to connect however when i set it to send data from 1 device on my network I don't get any upload. I am assuming I have set up something wrong and would really appreciate any ideas?
![274229293_517639969790592_3743019811571026227_n](https://user-images.githubusercontent.com/14944091/155877547-36da3456-bfc0-4b25-99b7-ebc1f5c80491.png)
[config.txt](https://github.com/peacey/split-vpn/files/8148446/config.txt)

**Comment by peacey** [comment]
Hi @tomganleylee,

Does the upload not work for all clients, or just one client? Have you tested upload from other clients? 

Are you able to ping the VPS server from your client?

**Comment by peacey** [comment]
Hi @tomganleylee,

This issue has become stale so I'm closing it. Feel free to re-open if you are still having issues!
