### ISSUE TITLE
uploading Nord config files

### ISSUE THREAD

**Issue by ryarber** [peacey/split-vpn#88]
Can you add specific commands as to how to upload the config files from the VPN providers? SFTP doesn't work with these machines.

Also, how do you edit the vpn.conf file? "sudo nano" doesn't work here.

**Comment by ryarber** [comment]
Update. I got the vpn to load just by manually inputting username and password. But the tunnel keeps crashing with a fatal error.

**Comment by peacey** [comment]
Hi @ryarber,

Please post the error you are getting so I can help you. 

For the future, you can use scp (not SFTP) to transfer files to the UDM. Or you can use vim directly on the UDM to text edit in terminal.
