### ISSUE TITLE
quick boot script issue

### ISSUE THREAD

**Issue by lowrisk75** [peacey/split-vpn#91]
my boot script is failing (from template provided)
It's very likely that I misunderstood something from the instruction (barrier language)
/etc/split-vpn/wireguard/mullvad is gone,  /mnt/data/split-vpn/wireguard/mullvad is still there
```
#!/bin/sh

/mnt/data/wireguard/setup_wireguard.sh

cd /etc/split-vpn/wireguard/mullvad
. ./vpn.conf
 /etc/split-vpn/vpn/updown.sh ${DEV} pre-up >pre-up.log 2>&1
wg-quick up ./${DEV}.conf >wireguard.log 2>&1
cat wireguard.log
~
~

# ./run-vpn.sh 
ln: /bin/bash: File exists
ln: /usr/bin/htop: File exists
ln: /usr/sbin/iftop: File exists
ln: /sbin/resolvconf: File exists
./run-vpn.sh: cd: line 7: can't cd to /etc/split-vpn/wireguard/mullvad: No such file or directory
./run-vpn.sh: .: line 8: can't open './vpn.conf': No such file or directory

```

it's seems that the file are still in /mnt/data/split-vpn/wireguard/mullvad
do I just change the boot script to 

 #!/bin/sh
/mnt/data/wireguard/setup_wireguard.sh
cd /mnt/data/split-vpn/wireguard/mullvad ## instead of  /etc/split-vpn/wireguard/mullvad
. ./vpn.conf
 /etc/split-vpn/vpn/updown.sh ${DEV} pre-up >pre-up.log 2>&1
wg-quick up ./${DEV}.conf >wireguard.log 2>&1
cat wireguard.log
~

**Comment by lowrisk75** [comment]
Nevermind, I just need to add /mnt/data/split-vpn/vpn/setup-split-vpn.sh   to my boot script

**Comment by signed2** [comment]
Mr @peacey, what a great work youve done! A UDM newbee as me I thank you and salute you for your good work!

I just have one issue, the boot utility doesnt kick in script 99-run-vpn.sh
`/mnt/data/on_boot.d/99-run-vpn.sh`

If I open the script 99-run-vpn.sh and execute line by line via ssh, Wireguard is connecting flawless.
Can you please help me out with any debug clue?

**Below are commands after a reboot**
I try 'wg' to see if there is any handshake, nope
Try to run run-vpn.sh, nope.
Manually execute script 99-run-vpn.sh line by line, Jackpot!


```
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2022
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  http://www.ui.com

      Welcome to UniFi Dream Machine!
->
# wg
# /etc/split-vpn/run-vpn.sh
-sh: /etc/split-vpn/run-vpn.sh: not found
# rm -f /etc/split-vpn
# ln -sf /mnt/data/split-vpn /etc/split-vpn
# /etc/split-vpn/run-vpn.sh
loading wireguard...
Warning: `/mnt/data/split-vpn/wireguard/mullvad/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
->
[Tue Dec  6 8:44:43 CET 2022] split-vpn: wg0 up: Loading configuration from /etc/split-vpn/wireguard/mullvad/vpn.conf.
[Tue Dec  6 8:44:43 CET 2022] split-vpn: Using IPv4 gateway from table 201: via xx.xxx.xxx.xx dev eth8.


```
Can you please push me in right direction?
Thank you!

**Comment by peacey** [comment]
Hi @signed2,

I've made a new issue for you here (#145). Let's continue there.
