### ISSUE TITLE
WebSocket traffic not going through WireGuard tunnel

### ISSUE THREAD

**Issue by keonji** [peacey/split-vpn#93]
`[2022-03-10T15:37:01,017] <webapi-443> WARN  api    - websocket session error:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method`

`[2022-03-10T15:37:01,028] <ws-notify> WARN  api    - unable to send over websocket java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed`

`[2022-03-10T15:37:01,031] <ws-notify> WARN  api    - unable to send over websocket java.lang.IllegalStateException: The WebSocket session [70] has been closed and no method (apart from close()) may be called on a closed session`

If I use the WireGuard just on the client, then everything works. If I connect a UDM Pro, then the tunnel rises up, traffic goes through tunnel, some sites open, but everything that should work via websocket does not work.

**Comment by peacey** [comment]
Hi @keonji,

I just tested web sockets through the VPN and they're working fine for me. I tested from a forced client and was able to connect to wss://ws.kraken.com/ and get updates. Are you serving the websocket or you're just attempting to communicate with a websocket as a client?

When you say "some sites open", do you mean some sites are NOT working? Have you tried to adjust your MSS clamping settings, for example setting `MSS_CLAMPING_IPV4="1400"` or lower in `vpn.conf`?

**Comment by keonji** [comment]
Hi @peacey,

In my configuration, all clients on the UDM Pro local network are connected via vpn. The tunnel itself is launched on UDM Pro using latest wireguard-kmod and split-vpn. Clients cannot access sites (and programs) that use WebSocket. Slack is not loaded, for example. At the same time, when I connect to the same vpn server directly from the client, everything works.

I'll try to change MSS clamping settings. Thanks for the advice. I'll post the result when I try it.

**Comment by peacey** [comment]
Also, are you able to use the websocket tester at https://www.piesocket.com/websocket-tester ? Just load the page, press connect, and see if it connects. Then send a message and see if it echoes it back to you.

**Comment by keonji** [comment]
Setting the MTU to 1450 solved all the problems. Thank you for your help!
