### ISSUE TITLE
VPN comes online, lose access to client.

### ISSUE THREAD

**Issue by shaft8472** [peacey/split-vpn#94]
It’s probably something very simple I’m overlooking. I’ve forced 1 client to use a split-vpn Mullvad configuration. 

The VPN comes online, I receive a message through Pushover that it is. `wg` tells me it’s running and the data that is used.

When I want to check what the said client tells me I cannot access it anymore. It’s running on a different vlan and is normally accessible as long as the vpn is not running. 

Sidenote: It also takes a while to be able to access said device when I disable the VPN.

**Comment by peacey** [comment]
Hi @shaft8472,

By default, everything goes through the VPN for forced clients, including inter-VLAN communication. In order to allow inter-VLAN access, you need to exempt the other VLAN subnets you want to be able to access by adding them to `EXEMPT_DESTINATIONS_IPV4`.

**Comment by shaft8472** [comment]
Cool, thanks. 
Will try that tomorrow!

**Comment by peacey** [comment]
Sorry @shaft8472, I didn't realize you edited your comment with a new question. 

Can you confirm if it's a DNS issue by trying to ping 1.1.1.1 from a forced client? If that works, then try to ping google.com. If pinging IP works but pinging a hostname doesn't, then we can be sure the issue is DNS.

**Comment by shaft8472** [comment]
No problem!

I've tried ping, that failed.
```
root@Pi-104:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
```
I've tried changing my DNS to 1.1.1.1 and disabled DNS_IPV4_INTERFACE. With no luck. Same with removeing DNS_IPV4_* stuff from the vpn.conf.


For some reason, when I bring down the VPN the forced clients (I've got two, so I know it's not just one) cannot connect to the internet. Even if the VPN is down.

**Comment by peacey** [comment]
So you're using the killswitch and also set `REMOVE_KILLSWITCH_ON_EXIT=0` which means the killswitch and rules will not be removed when you bring the tunnel down. These options are good for when you never want the client to have internet when the tunnel goes down. For testing, I recommend setting `KILLSWITCH=0` and `REMOVE_KILLSWITCH_ON_EXIT=1`. You can enable the killswitch after testing if this is your desired behavior. 

When you do enable the killswitch, you have to force down the script to remove the rules like this (after you already ran wg-quick down of course):

```sh
cd /mnt/data/split-vpn/wireguard/mullvad
/mnt/data/split-vpn/vpn/updown.sh wg0 force-down
```

Then your clients should have access again. 

Once you confirm your clients have access to the Internet again, make sure to disable the killswitch and enable removing on exit as I said above, then start the VPN again. 

After you start the VPN, please ping 1.1.1.1 directly from the UDMP SSH through the wireguard tunnel like this:

```sh
ping -I wg0 1.1.1.1
```

This will tell us if the wireguard tunnel is even working to begin with.

**Comment by shaft8472** [comment]
Doh!
Sometimes when trying to solve something I overlook the most obvious.

Right, disabled the killswitch for now.
Both Pi's had internet access again.

When enabling the VPN the forced clients give:
```
root@Pi-104:~# ping verstappen.nl
PING verstappen.nl (185.103.156.65) 56(84) bytes of data.
^C
--- verstappen.nl ping statistics ---
23 packets transmitted, 0 received, 100% packet loss, time 22532ms

root@Pi-104:~#
```
I can see my request coming in on the Pi-hole. I have to tell you my 10-dns.sh is redirecting all DNS data from different VLAN's to the Pi-hole. That is why the request still comes in on the Pi-hole. It feels like the said device is not able to receive the said DNS data.

While I have enabled: `EXEMPT_DESTINATIONS_IPV4="192.168.200.0/24 192.168.203.101 192.168.199.100/29 192.168.205.101"`

Or am I looking in the 'wrong corner'?

Current vpn.conf settings are:
```
DNS_IPV4_IP="1.1.1.1"
#DNS_IPV4_PORT=53
#DNS_IPV4_INTERFACE="br205"
```

**Comment by peacey** [comment]
DNS is not the problem because you're not even able to ping 1.1.1.1. You need to check if the tunnel is working on the UDMP first like I said. After you run the VPN, can you ping directly through the tunnel in SSH on the UDMP (not the PI) like this: 

```
ping -I wg0 1.1.1.1
```

Make sure you run this on the UDM not your forced client.

**Comment by shaft8472** [comment]
> DNS is not the problem because you're not even able to ping 1.1.1.1, right? You need to check if the tunnel is working on the UDMP first like I said.

Misunderstood you. Running that command on my UDMP when the VPN is enabled works like a charm.
```
# ping -I wg0 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=55 time=26.826 ms
64 bytes from 1.1.1.1: seq=1 ttl=55 time=26.005 ms
```

**Comment by peacey** [comment]
That's great, @shaft8472. So the tunnel is working. But last time you pinged 1.1.1.1 from a forced client, it didn't work. Which is odd. Can. You try to ping 1.1.1.1 from a forced client again?

**Comment by shaft8472** [comment]
Yeah, that doesn't work.

**Comment by peacey** [comment]
Hmm, that's weird. You are able to ping 1.1.1.1 from the client when the VPN is off, right?

Can you change MARK to 0x696af100 and try to ping from the forced client again? If that doesn't work, can you also set `MSS_CLAMPING_IPV4=1400` and try again?

**Comment by shaft8472** [comment]
> Hmm, that's weird. You are able to ping 1.1.1.1 from the client when the VPN is off, right?

Yes.

> Can you change MARK to 0x696af100 and try to ping from the forced client again?

That worked! Ping works and checking my external IP also worked. What did this do?

> If that doesn't work, can you also set `MSS_CLAMPING_IPV4=1400` and try again? Make sure to bring down the VPN before changes, and start it again after changes.

Didn't try this because the above worked.

**Comment by peacey** [comment]
That's great!

Basically, we marks packets we want to reroute using iptables with a mark value (that you define in the config). Then all packets with this mark are routed to the VPN table. However, there are some cases where UDM uses 0x9 internally (like to route to IPS or something). Multiple people reported it was conflicting on their setup (see #73 see #95). So we changed the MARK to something more random so it doesn't conflict with UDMP internal packets. 

Glad that it worked with the DNS!

**Comment by shaft8472** [comment]
Well, you've made me very happy. This was the last on my to do list for the UDM-P for now. Thank you for your help!
