### ISSUE TITLE
MARK=0x9 conflicts with UDMPro

### ISSUE THREAD

**Issue by powellcn** [peacey/split-vpn#95]
I had a very odd problem.
No matter what I did with vpn.conf, all my clients were routed through wg0.
Also, I setup firewall rules to allow br0 to connect to clients on br40 and these were all denied.
I couldn't figure out what was wrong.

Eventually I stumbled across https://github.com/peacey/split-vpn/issues/73.
Changing MARK=0x9 to MARK=0x99 solved both problems.

The MARK=0x9 should be changed in the README and sample configs.  I know this is planned, but it isn't currently in the issue list.   

I created https://github.com/peacey/split-vpn/pull/96

**Comment by peacey** [comment]
Thanks for reminding me @powellcn. I completely forgot about this issue. We can merge the pull request, but would prefer to change it to something more random like 0x696af100 first. Can you modify the pull request?

**Comment by powellcn** [comment]
Hi @peacey.
Not a problem.   All done!
Thanks for all this!
